import type { DocsContent } from './types';

export const docsContent: DocsContent = {
  intro: `Добре дошли в ръководството за потребителя на Original Character Maker!

Това ръководство съдържа подробна документация за всички 7 функционални модула и глобален речник на грешките. Ако срещнете грешка при използване на инструмент или не сте сигурни във функцията на бутон/параметър, отворете това ръководство, за да намерите съответната глава.

Структура на ръководството:
· Ръководство за инструменти — Всеки инструмент има независима глава с преглед на функциите, описания на бутоните, параметрите и грешките с решения
· Речник на грешките — Глобален индекс на грешките, подреден по категории (A~Z, 0~9), позволява бързо търсене като в речник

Как да използвате речника на грешките:
1. Първо проверете кода, показан на панела за грешки (напр. STYLE_TRANSFER_REQUEST_FAILED)
2. Намерете съответната категория според първата буква (S → Система и работен процес)
3. Намерете записа в азбучен ред в рамките на категорията
4. Прочетете "Местоположение", за да потвърдите страницата и областта, където е възникнала грешката
5. Следвайте "Стъпките за решаване", за да разрешите проблема стъпка по стъпка`,

  tools: [
    {
      id: 'face-maker',
      title: 'Създател на лица',
      overview: `The face maker is the entry-point tool of OC Maker. Select hairstyles, eyes, eyebrows, noses, mouths, face shapes, ears, accessories, poses, and clothing from the asset library on the left, then finely adjust proportions, colors, and positions using 16 numeric sliders on the right. Real-time preview on the central canvas. All settings are performed locally — no images or data are uploaded.`,
      buttons: [
        { name: 'Save Draft', description: 'Save current part selections and parameter values to browser local storage.' },
        { name: 'Export', description: 'Export current face configuration as a JSON file (oc-face-maker-config.json).' },
        { name: 'Export PNG', description: 'Export the character image on the current canvas as PNG (oc-character.png).' },
        { name: 'Import Config', description: 'Select a previously exported JSON config file to restore parts and parameters.' },
        { name: 'Reset', description: 'Reset all parameters to defaults and restore parts to original state.' },
      ],
      parameters: [
        { name: 'Head Scale', description: 'Adjust overall head size. Range 40~70.', tips: 'Recommended to adjust together with Face Length to avoid disproportion.' },
        { name: 'Face Length', description: 'Adjust face length. Range 30~70.', tips: 'Closer to 30 is rounder; closer to 70 is longer.' },
        { name: 'Skin Color', description: 'Adjust skin tone. Range 0~100. Implements skin color changes from light to dark via HSL hue shift.' },
        { name: 'Hair Color', description: 'Adjust hair color. Range 0~100. Implements rainbow hair color changes via hue rotation.' },
        { name: 'Eye Size', description: 'Adjust overall eye scale. Range 38~62.' },
        { name: 'Pose', description: 'Select the character full-body pose: standing, arms crossed, hand on hip, waving.', tips: 'Best preview effect when combining pose with clothing.' },
        { name: 'Top', description: 'Select character top: T-shirt, hoodie, suit, sailor uniform, or no clothing.', tips: 'Top color follows the Accessory Color slider.' },
      ],
      errors: [
        {
          code: 'CONFIG_CORRUPTED',
          message: 'Face config loading is abnormal, canvas display incomplete or parameter sliders not working',
          severity: 'error',
          category: 'B. Конфигурация и данни',
          location: 'Page: Създател на лица → Area: Central canvas / Right parameter panel',
          cause: 'The face-maker config data saved in browser local storage is corrupted.',
          solution: 'Reset config and recreate the face.',
          steps: ['Click the Reset button at bottom left', 'Click Confirm Reset in dialog', 'If still abnormal, open DevTools → Application → Local Storage and delete keys starting with face-maker', 'Refresh page and start over'],
          relatedCodes: ['IMPORT_INVALID_JSON', 'STORAGE_READ_ONLY'],
          prevention: 'Do not manually modify localStorage data.',
        },
      ],
    },
    {
      id: 'style-transfer',
      title: 'Прехвърляне на стил',
      overview: `A tool for converting character images into a specified artistic style. After uploading a character image in PNG/JPG format, select an AI model, write a Prompt, and configure additional parameters to call the backend API. Supports automatic cutout, color scheme preservation, pose lock, face lock and other additional features. Requires internet connection and valid API Key.`,
      buttons: [
        { name: 'Select Image / Replace Image', description: 'Upload a character image file. PNG and JPG formats are supported.' },
        { name: 'Start', description: 'Start the style transfer process.' },
        { name: 'Copy JSON', description: 'Copy all current config parameters as JSON text to clipboard.' },
        { name: 'Download Result', description: 'Download the converted result image locally.' },
        { name: 'Reset', description: 'Reset all parameters to defaults, clear uploaded image and results.' },
      ],
      parameters: [
        { name: 'Model', description: 'Select the AI image generation model to use.', tips: 'gpt-image-2 is the default model. claude-4-sonnet performs better in character consistency.' },
        { name: 'Prompt', description: 'Positive prompt describing desired artistic style, scene, and character features.', tips: 'Prompt automatically appends English suffixes converted from additional parameters.' },
        { name: 'Negative Prompt', description: 'Negative prompt describing content you do not want to see.', tips: 'Common negative tags: low quality, extra fingers, deformed body, blur.' },
        { name: 'Temperature', description: 'Sampling temperature, controls generation result randomness. Range 0~2, default 0.7.', tips: 'Lower values give more stable results; higher values are more creative but may deviate from expectations.' },
        { name: 'Strength', description: 'Style strength / redrawing amplitude. Range 0~1. Larger values preserve less of the original image.', tips: '0.4~0.6 is the commonly used range. Can change style while preserving character features.' },
      ],
      errors: [
        {
          code: 'API_KEY_MISSING',
          message: 'Immediately after pressing Start an error occurs, API Key not configured',
          severity: 'critical',
          category: 'A. API и мрежа',
          location: 'Page: Прехвърляне на стил → Area: Bottom-left error panel',
          cause: 'API Key is not configured in Settings → API or the Key was cleared.',
          solution: 'Configure a valid API Key in the settings panel.',
          steps: ['Click Open Settings at top right', 'Switch to API tab', 'Enter valid Key', 'Click Save', 'Return to style transfer page and click Start again'],
          relatedCodes: ['API_KEY_EXPIRED', '401_UNAUTHORIZED'],
          prevention: 'Before first use of any online tool, be sure to configure a valid API Key in Settings → API.',
        },
      ],
    },
    {
      id: 'prompt-suite',
      title: 'Карта на героя / Редактор на свят',
      overview: `PromptSuite is a formatted text editor for organizing character cards, world descriptions, relationship maps, and speech profiles. Supports font, color, emphasis, headings, lists, tables, code blocks, quotes, and image insertion formatting. All content is automatically saved in the browser.`,
      buttons: [
        { name: 'Save Document', description: 'Save current editor HTML content and toolbar state to local storage.' },
        { name: 'Reset', description: 'Clear current document and restore default template.' },
        { name: 'Import Config', description: 'Import a previously exported PromptSuite config JSON file.' },
        { name: 'Export HTML', description: 'Export current document as a standalone HTML file with embedded styles.' },
      ],
      parameters: [
        { name: 'Template Select', description: 'Quickly switch preset templates: World Description, Character Card, Relationship Map, Speech Profile, Timeline.' },
        { name: 'Font', description: 'Set editor body text font family.' },
        { name: 'Font Size', description: 'Set base font size. Supports px/rem units.' },
        { name: 'Text Color', description: 'Set color of currently selected text.' },
        { name: 'Bold / Italic / Underline / Strikethrough', description: 'Basic text formatting buttons.' },
      ],
      errors: [
        {
          code: 'CONFIG_CORRUPTED',
          message: 'After opening editor content is empty or formatting is distorted',
          severity: 'error',
          category: 'B. Конфигурация и данни',
          location: 'Page: Карта на героя / Редактор на свят → Area: Central editor area',
          cause: 'PromptSuite config data saved in browser local storage is corrupted.',
          solution: 'Reset editor or manually clear localStorage.',
          steps: ['Click Reset button', 'Click Confirm Reset', 'If still abnormal delete prompt-suite keys in localStorage', 'Refresh page'],
          relatedCodes: ['IMPORT_INVALID_JSON', 'STORAGE_READ_ONLY'],
          prevention: 'Do not manually modify localStorage data.',
        },
      ],
    },
    {
      id: 'llm-hub',
      title: 'LLM текстов достъп',
      overview: `LLM Hub is a tool for configuring large language model parameters and testing them in real time. You can configure model selection, sampling parameters, system prompts, etc., then conduct multi-turn conversations with AI through the real-time testing panel. Supports saving multiple config presets for quick switching between different creative scenarios.`,
      buttons: [
        { name: 'Save Document', description: 'Save current LLM config to local storage.' },
        { name: 'Reset', description: 'Reset all parameters to defaults.' },
        { name: 'Import Config', description: 'Import a previously exported LLM Hub config JSON file.' },
        { name: 'Send', description: 'Send the entered message to AI on the real-time testing panel.' },
        { name: 'Clear', description: 'Clear current conversation history and output content.' },
        { name: 'Save as Preset', description: 'Save current all parameters as a named preset.' },
      ],
      parameters: [
        { name: 'Model', description: 'Select the large language model to use.', tips: 'gpt-5.4 is the default recommended model. claude-4-sonnet excels at creative writing.' },
        { name: 'Temperature', description: 'Controls generation result randomness. Range 0~2.', tips: 'Creative writing: 0.7~1.0. Character setting supplementation: 0.3~0.5.' },
        { name: 'Max Tokens', description: 'Maximum generation length for a single response. Range 1~8192.', tips: 'Character setting generation: 1024~2048. Short conversation: 512.' },
        { name: 'Response Format', description: 'Specify AI output format: text or json_object.', tips: 'When selecting json_object you must clearly explain expected JSON structure in Prompt.' },
        { name: 'System Prompt', description: 'Global prompt defining AI role and behavioral guidelines.', tips: 'This is the most important parameter affecting output quality.' },
      ],
      errors: [
        {
          code: 'API_KEY_MISSING',
          message: 'Immediately after sending message an error occurs, API Key not configured',
          severity: 'critical',
          category: 'A. API и мрежа',
          location: 'Page: LLM текстов достъп → Area: Real-time testing output panel',
          cause: 'API Key is not configured in Settings → API.',
          solution: 'Configure API Key in the settings panel.',
          steps: ['Click Open Settings at top right', 'Switch to API tab', 'Enter valid API Key', 'Save and close', 'Return to LLM Hub and send again'],
          relatedCodes: ['API_KEY_EXPIRED', '401_UNAUTHORIZED'],
          prevention: 'Before first use of any online tool, be sure to configure a valid API Key.',
        },
      ],
    },
    {
      id: 'tts-export',
      title: 'TTS експорт на глас',
      overview: `A tool for configuring speech synthesis parameters and generating character voice assets. Supports configuring voice, language, speed, pitch, volume and other basic parameters, as well as additional parameters: breath, clarity, expressiveness, pause intensity. Can upload reference audio as voice clone source, supports audio post-processing and pronunciation correction.`,
      buttons: [
        { name: 'Save', description: 'Save current TTS config to local storage.' },
        { name: 'Reset', description: 'Reset all parameters to defaults, clear reference audio and logs.' },
        { name: 'Import Config', description: 'Import a previously exported TTS config JSON file.' },
        { name: 'Download JSON', description: 'Download current TTS config as JSON file.' },
        { name: 'Upload Reference Audio', description: 'Select and upload reference audio (WAV/MP3/FLAC, max 10MB) for voice cloning.' },
        { name: 'Copy Logs', description: 'Copy right-side log panel content to clipboard.' },
      ],
      parameters: [
        { name: 'Voice', description: 'Select preset voice timbre.', tips: 'Hanazora is the default female voice. Mirako is an energetic female voice. Rin is a youth voice.' },
        { name: 'Language', description: 'Target language for synthesized speech.', tips: 'When switching global interface language this field auto-syncs.' },
        { name: 'Speed', description: 'Speech playback speed coefficient. Range 0.6~1.6.', tips: '1.0 is normal speed. When character is emotionally excited can set to 1.2~1.4.' },
        { name: 'Pitch', description: 'Pitch offset. Range -12~12 (semitones).', tips: 'Positive values are higher and brighter; negative values are lower and deeper.' },
        { name: 'Volume', description: 'Output volume percentage. Range 40~140.', tips: '100 is original volume. When background noise is loud can set to 110~120.' },
        { name: 'Breath', description: 'Controls breath intensity in speech. Range 0~100.', tips: 'Higher values sound more natural but too high creates a breathless feeling.' },
        { name: 'Clarity', description: 'Controls pronunciation clarity. Range 0~100.', tips: 'Higher values give clearer pronunciation but may sound mechanical.' },
      ],
      errors: [
        {
          code: 'API_KEY_MISSING',
          message: 'When generating voice it shows API Key not configured',
          severity: 'critical',
          category: 'A. API и мрежа',
          location: 'Page: TTS експорт на глас → Area: Left output panel',
          cause: 'API Key is not configured.',
          solution: 'Configure Key in settings panel.',
          steps: ['Open Settings → API', 'Enter valid Key', 'Save and retry'],
          relatedCodes: ['API_KEY_EXPIRED'],
          prevention: 'Before first use of any online tool configure a valid API Key.',
        },
      ],
    },
    {
      id: 'paper2gal',
      title: 'paper2gal генериране на изображения',
      overview: `Paper2Gal is the main workflow tool of Original Character Maker. Connects to the backend p2g-character-workflow to batch generate character assets in a "one image in, multiple assets out" manner. After uploading a character reference image, the workflow automatically executes 10 steps generating 8 final assets and 5 metadata files.`,
      buttons: [
        { name: 'Back to Home', description: 'Leave paper2gal page and return to home.' },
        { name: 'Open Settings', description: 'Open global settings panel.' },
        { name: 'Save Config', description: 'Save current prompt overrides and AI parallelism settings.' },
        { name: 'Reset Workflow', description: 'Clear all workflow state, images, results and config. This operation is irreversible.' },
        { name: 'Import Config', description: 'Import a previously exported paper2gal config JSON file.' },
        { name: 'Select Image / Replace Image', description: 'Upload a character reference image.' },
        { name: 'Start', description: 'Send image to backend to start the full paper2gal workflow.' },
        { name: 'Retry Workflow', description: 'Restart workflow with the same uploaded image.' },
        { name: 'Download All', description: 'Download ZIP with all generated assets and metadata.' },
        { name: 'Step Card — Open File', description: 'Open generated image in new tab after step completion.' },
        { name: 'Step Card — Retry / Redo', description: 'Retry failed steps or redo successful ones.' },
      ],
      parameters: [
        { name: 'AI Parallelism', description: 'When enabled AI generation steps execute in parallel, significantly reducing total time.', tips: 'Enabling parallelism may increase API costs; on servers with limited config or strict rate limits recommend disabling.' },
        { name: 'Prompt Override — Thinking Expression', description: 'Override prompt for generating the thinking expression.' },
        { name: 'Prompt Override — Surprise Expression', description: 'Override prompt for generating the surprise expression.' },
        { name: 'Prompt Override — Angry Expression', description: 'Override prompt for generating the angry expression.' },
        { name: 'Prompt Override — CG01', description: 'Override prompt for the first CG scene.' },
        { name: 'Input Image', description: 'Original image for the workflow. Only PNG and JPG supported.', tips: 'Recommended size is 1024×1024 ~ 2048×2048.' },
        { name: 'Workflow ID', description: 'Read-only unique identifier.', tips: 'Copy this ID to search for corresponding record in backend logs.' },
        { name: 'Cutout Provider', description: 'Read-only background removal engine name.' },
      ],
      errors: [
        {
          code: 'API_KEY_MISSING',
          message: 'Immediately after starting workflow an error occurs, API Key not configured',
          severity: 'critical',
          category: 'A. API и мрежа',
          location: 'Page: paper2gal генериране на изображения → Area: Top message panel / Right error panel',
          cause: 'API Key is not configured in Settings → API or Key was cleared.',
          solution: 'Configure valid API Key in settings panel.',
          steps: ['Click Open Settings at top right', 'Switch to API tab', 'Enter valid Key', 'Save', 'Return and click Start again'],
          relatedCodes: ['API_KEY_EXPIRED', '401_UNAUTHORIZED'],
          prevention: 'Before first use of any online tool configure a valid API Key.',
        },
        {
          code: 'HOSTED_API_REQUIRED',
          message: 'Current environment is static hosting, custom API must be configured',
          severity: 'critical',
          category: 'A. API и мрежа',
          location: 'Page: paper2gal генериране на изображения → Area: Top message panel',
          cause: 'Page is deployed in static hosting environment, cannot directly access local backend.',
          solution: 'Configure remote API address in settings.',
          steps: ['Open Settings → API', 'Switch Interface Mode to Custom API', 'Enter backend root address', 'Enter API Key', 'Save and retry'],
          relatedCodes: ['API_KEY_MISSING', 'BACKEND_UNAVAILABLE'],
          prevention: 'Deploy backend and configure API address before using paper2gal in static environment.',
        },
        {
          code: 'P2G_WORKFLOW_ERROR',
          message: 'Error panel shows P2G_WORKFLOW_ERROR',
          severity: 'error',
          category: 'E. Работен процес и конвертиране',
          location: 'Page: paper2gal генериране на изображения → Area: Top message panel / Right error panel',
          cause: 'A Paper2Gal workflow step failed. Possible causes: input validation failure, model unavailable, API Key expired, content filtered, network interruption.',
          solution: 'Troubleshoot step by step based on error details.',
          steps: ['Read error details', 'Check image is valid PNG/JPG', 'Check network connection', 'Change sensitive words in prompt overrides', 'Ensure backend is running normally', 'Retry failed step or reset workflow'],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'PROMPT_BLOCKED', 'WORKFLOW_STEP_FAILED'],
          prevention: 'Before starting check image validity, network stability, no sensitive words in prompts, and valid API Key.',
        },
      ],
    },
    {
      id: 'image-converter',
      title: 'Конвертор на формати на изображения',
      overview: `Image format converter is a purely frontend tool for uploading images and converting them to PNG or JPG format. Supports six filter settings: brightness, contrast, saturation, blur, hue rotation, and grayscale. Can control output quality and maximum size, supports preserving original aspect ratio. All processing is done locally in the browser; images are not uploaded to server.`,
      buttons: [
        { name: 'Select Image', description: 'Upload an image file. Supports PNG, JPG, and WEBP formats.' },
        { name: 'Convert', description: 'Apply all filter parameters and generate output image. Processing is entirely local in browser.' },
        { name: 'Download Result', description: 'Download converted image locally. Filename format: converted-{timestamp}.{ext}.' },
        { name: 'Reset', description: 'Clear uploaded image and results, reset all filter parameters to defaults.' },
      ],
      parameters: [
        { name: 'Output Format', description: 'Output image MIME type: image/png or image/jpeg.', tips: 'PNG supports transparent channel but files are larger. JPG files are smaller but transparency is not supported.' },
        { name: 'Quality', description: 'JPG output compression quality. Range 10~100. Only applies to JPG format.', tips: '90~95 is the optimal balance between quality and file size.' },
        { name: 'Max Width', description: 'Maximum output image width (pixels). If original is wider it will proportionally scale down.', tips: '2048 satisfies upload requirements of most social platforms.' },
        { name: 'Max Height', description: 'Maximum output image height (pixels).' },
        { name: 'Preserve Aspect Ratio', description: 'Whether to preserve original aspect ratio when scaling.', tips: 'Always recommended to enable to avoid image distortion.' },
        { name: 'Brightness', description: 'Adjust overall image brightness. Range 0~200, 100 is original brightness.', tips: 'Below 50 is noticeably darker; above 150 may cause overexposure and loss of detail.' },
        { name: 'Contrast', description: 'Adjust image contrast. Range 0~200, 100 is original contrast.', tips: 'Higher values give stronger light-shadow contrast, good for emphasizing lines.' },
      ],
      errors: [
        {
          code: 'CONVERT_ERROR',
          message: 'Error panel shows CONVERT_ERROR',
          severity: 'error',
          category: 'E. Работен процес и конвертиране',
          location: 'Page: Конвертор на формати на изображения → Area: Right error panel',
          cause: 'Exception occurred during image conversion. Original image may be corrupted, browser may not support Canvas 2D filter, or insufficient memory.',
          solution: 'Check image and browser compatibility.',
          steps: ['Ensure original image opens normally in browser', 'Refresh page and re-upload', 'Check if image is too large', 'Turn off filters one by one to find unsupported ones', 'Try another browser'],
          relatedCodes: ['FILE_CORRUPTED', 'DEVICE_MEMORY_LOW'],
          prevention: 'Ensure image opens normally in browser before converting. Do not enable too many filters simultaneously.',
        },
      ],
    },
  ],
  errorDictionary: [
    {
      id: 'A',
      name: 'A. API и мрежа',
      description: 'Errors related to API Key, network connection, backend service, request timeout, rate limiting and other external dependencies.',
      errors: [
        {
          code: 'API_KEY_EXPIRED',
          message: 'Request returns 401 or shows Key is invalid/expired',
          severity: 'critical',
          category: 'A. API и мрежа',
          location: 'Page: Any online tool → Area: Error panel or output area',
          cause: 'Configured API Key has expired, been revoked, or quota exhausted.',
          solution: 'Replace with a valid API Key.',
          steps: ['Open Settings → API panel', 'Delete current Key and enter new valid one', 'Save and retry'],
          relatedCodes: ['API_KEY_MISSING', '401_UNAUTHORIZED'],
          prevention: 'Regularly check API Key expiration date and remaining quota.',
        },
        {
          code: 'API_KEY_MISSING',
          message: 'Immediately after pressing start/send/generate an error occurs, API Key not configured',
          severity: 'critical',
          category: 'A. API и мрежа',
          location: 'Page: Any online tool → Area: Error panel or output area',
          cause: 'API Key is not configured in Settings → API.',
          solution: 'Configure a valid API Key in the settings panel.',
          steps: ['Click Open Settings at top right', 'Switch to API tab', 'Enter valid Key', 'Click Save', 'Return and retry operation'],
          relatedCodes: ['API_KEY_EXPIRED', '401_UNAUTHORIZED'],
          prevention: 'Before first use of any online tool be sure to configure a valid API Key.',
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: 'Backend unavailable, Cannot connect to server, or request cannot be sent',
          severity: 'critical',
          category: 'A. API и мрежа',
          location: 'Page: Any online tool → Area: Error panel',
          cause: 'Backend server is not running, has crashed, or configured API Base URL is incorrect.',
          solution: 'Check backend service status and API configuration.',
          steps: ['Open browser DevTools → Network', 'Retry operation and check request status', 'If request not sent check Settings → API → API Base URL', 'If 502/503 contact administrator', 'For local deployment check if process is running'],
          relatedCodes: ['NETWORK_DISCONNECTED', '502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
          prevention: 'For local deployment run backend process. For remote service check URL.',
        },
      ],
    },
    {
      id: 'B',
      name: 'B. Конфигурация и данни',
      description: 'Errors related to config import/export, localStorage, data corruption, and unsaved changes warnings.',
      errors: [
        {
          code: 'CONFIG_CORRUPTED',
          message: 'Config loading is abnormal, interface displays incompletely or functions do not work',
          severity: 'error',
          category: 'B. Конфигурация и данни',
          location: 'Page: Any tool → Area: Entire page or specific functional area',
          cause: 'Config data in browser local storage is corrupted.',
          solution: 'Reset config and clear localStorage.',
          steps: ['Click Reset button', 'Confirm in dialog', 'If necessary delete keys in Local Storage', 'Refresh page'],
          relatedCodes: ['IMPORT_INVALID_JSON', 'STORAGE_READ_ONLY'],
          prevention: 'Do not manually modify localStorage data.',
        },
        {
          code: 'STORAGE_READ_ONLY',
          message: 'Save operation does not respond, data is lost after refresh',
          severity: 'critical',
          category: 'B. Конфигурация и данни',
          location: 'Page: Any tool → Area: Save button',
          cause: 'Browser is in private/incognito mode, or localStorage is disabled, or disk is full.',
          solution: 'Exit private mode or free up disk space.',
          steps: ['Ensure not in incognito mode', 'Check disk space', 'Open app in normal window', 'Use Export as alternative if needed'],
          relatedCodes: ['LOCAL_STORAGE_FULL'],
          prevention: 'Do not use this app in browser private mode. Regularly export config to local file.',
        },
      ],
    },
    {
      id: 'C',
      name: 'C. Файлове и вход',
      description: 'Errors related to image/audio file upload, unsupported formats, corrupted files, and files that are too large.',
      errors: [
        {
          code: 'FILE_FORMAT_UNSUPPORTED',
          message: 'When uploading shows Unsupported file format',
          severity: 'warning',
          category: 'C. Файлове и вход',
          location: 'Page: Any tool with upload → Area: Select File button',
          cause: 'Selected file format is not supported by the tool.',
          solution: 'Convert file to supported format.',
          steps: ['Check supported format list', 'Convert file', 'Re-upload'],
          relatedCodes: ['FILE_CORRUPTED', 'UPLOAD_FORMAT'],
        },
        {
          code: 'FILE_TOO_LARGE',
          message: 'After upload preview does not work or memory error during processing',
          severity: 'warning',
          category: 'C. Файлове и вход',
          location: 'Page: Any tool with upload → Area: Preview area',
          cause: 'Uploaded file size exceeds tool or browser limit.',
          solution: 'Compress or reduce file before uploading.',
          steps: ['Compress file', 'For images reduce max side to 2048 or 4096', 'For audio reduce sample rate', 'Re-upload'],
          relatedCodes: ['DEVICE_MEMORY_LOW', 'FILE_FORMAT_UNSUPPORTED'],
        },
      ],
    },
    {
      id: 'D',
      name: 'D. Модели и генериране',
      description: 'Errors related to AI model unavailability, content filtering, prompt too long, and generation failure.',
      errors: [
        {
          code: 'MODEL_NOT_FOUND',
          message: 'Backend returns 404, model not found',
          severity: 'error',
          category: 'D. Модели и генериране',
          location: 'Page: Any online tool → Area: Error panel',
          cause: 'Model ID is misspelled or model has been deprecated.',
          solution: 'Fix model ID or select another model.',
          steps: ['Check model ID spelling', 'Select known available model from list', 'For custom API check documentation', 'Retry'],
          relatedCodes: ['LLM_MODEL_UNAVAILABLE'],
          prevention: 'Select known available models from the list.',
        },
        {
          code: 'PROMPT_BLOCKED',
          message: 'Content blocked by safety filter',
          severity: 'error',
          category: 'D. Модели и генериране',
          location: 'Page: Any AI generation tool → Area: Error panel',
          cause: 'Prompt contains words blocked by platform safety policy.',
          solution: 'Modify prompt, remove or replace potentially problematic words.',
          steps: ['Check error details for keyword identification', 'Replace sensitive words with synonyms', 'Simplify prompt', 'Gradually add modifiers'],
          relatedCodes: ['403_FORBIDDEN'],
          prevention: 'Avoid sensitive words when modifying prompts.',
        },
      ],
    },
    {
      id: 'E',
      name: 'E. Работен процес и конвертиране',
      description: 'Errors related to workflow execution, image conversion, step failure, and workflow cancellation.',
      errors: [
        {
          code: 'P2G_WORKFLOW_ERROR',
          message: 'Paper2Gal workflow execution error',
          severity: 'error',
          category: 'E. Работен процес и конвертиране',
          location: 'Page: paper2gal → Area: Error panel',
          cause: 'A workflow step failed. Possible causes: input validation failure, model unavailable, Key expired, content filtered, network interruption.',
          solution: 'Troubleshoot step by step based on error details.',
          steps: ['Read error details', 'Check PNG/JPG image', 'Check network', 'Change sensitive words in prompt overrides', 'Ensure backend is running', 'Retry step or reset workflow'],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'PROMPT_BLOCKED'],
          prevention: 'Before starting check image, network, prompts, and API Key.',
        },
        {
          code: 'STYLE_TRANSFER_REQUEST_FAILED',
          message: 'Style transfer request error',
          severity: 'error',
          category: 'E. Работен процес и конвертиране',
          location: 'Page: Style Transfer → Area: Error panel',
          cause: 'Backend API request error. Possible causes: network interruption, invalid API Key, model unavailable, server internal error.',
          solution: 'Troubleshoot based on error details.',
          steps: ['Check error details', '401: check API Key', '404: check model', '429: wait', '500/502/503: check backend', 'Network error: check connection'],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'BACKEND_UNAVAILABLE'],
          prevention: 'Before starting check API Key, network, and model availability.',
        },
      ],
    },
    {
      id: 'F',
      name: 'F. Система и права',
      description: 'System-level issues: browser compatibility, insufficient memory, permission restrictions, and export failures.',
      errors: [
        {
          code: 'DEVICE_MEMORY_LOW',
          message: 'Browser tab crashes, freezes, or becomes unresponsive',
          severity: 'critical',
          category: 'F. Система и права',
          location: 'Page: Any tool → Area: Entire page',
          cause: 'Device memory is insufficient and browser forcibly terminated the tab process.',
          solution: 'Close other tabs, reduce data scale, or use a device with more memory.',
          steps: ['Save current work', 'Close other tabs', 'Reduce image size', 'Restart browser', 'Use device with more memory'],
          relatedCodes: ['FILE_TOO_LARGE'],
          prevention: 'Close other tabs before processing large files. Reduce images to 2048.',
        },
        {
          code: 'EXPORT_FAILED',
          message: 'After pressing export button no response',
          severity: 'error',
          category: 'F. Система и права',
          location: 'Page: Any tool → Area: Export button',
          cause: 'Browser blocked download popup, or content is too large to generate Blob.',
          solution: 'Check browser download settings or export in batches.',
          steps: ['Check if browser blocks popups', 'Allow popups', 'If many images delete some before exporting', 'Use Copy as temporary alternative'],
          relatedCodes: ['DEVICE_MEMORY_LOW'],
          prevention: 'Allow browser popups. For large documents delete some images before exporting.',
        },
      ],
    },
    {
      id: '0',
      name: '0~9. HTTP кодове за състояние',
      description: 'Common backend errors classified by HTTP status codes.',
      errors: [
        {
          code: '401_UNAUTHORIZED',
          message: 'Backend returns 401 Unauthorized',
          severity: 'critical',
          category: '0~9. HTTP кодове за състояние',
          location: 'Page: Any online tool → Area: Error panel',
          cause: 'API Key is invalid, expired, or revoked.',
          solution: 'Replace with a valid API Key.',
          steps: ['Open Settings → API', 'Replace with new valid Key', 'Save and retry'],
          relatedCodes: ['API_KEY_EXPIRED', 'API_KEY_MISSING'],
          prevention: 'Regularly check API Key expiration date.',
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: 'Backend returns 429 Too Many Requests',
          severity: 'warning',
          category: '0~9. HTTP кодове за състояние',
          location: 'Page: Any online tool → Area: Error panel',
          cause: 'Too many requests sent in short time, exceeding provider rate limit.',
          solution: 'Wait and retry.',
          steps: ['Check Retry-After hint', 'Wait 30~60 seconds', 'Reduce request frequency'],
          relatedCodes: ['API_RATE_LIMIT'],
        },
        {
          code: '500_INTERNAL_ERROR',
          message: 'Backend returns 500 Internal Server Error',
          severity: 'error',
          category: '0~9. HTTP кодове за състояние',
          location: 'Page: Any online tool → Area: Error panel',
          cause: 'Backend service encountered an internal exception while processing request.',
          solution: 'Retry later or contact backend administrator.',
          steps: ['Wait 1~2 minutes', 'Reduce request scale', 'If problem persists contact backend administrator'],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
          prevention: 'Reduce request scale. Do not send large tasks when server is under high load.',
        },
      ],
    },
  ],
};
