import type { DocsToolSection } from './types';

/* ─── Extra tool documentation for modules not covered in the original docs ─── */

const en: DocsToolSection[] = [
  {
    id: 'asset-gallery',
    title: 'Asset Gallery',
    overview: `The Asset Gallery is a centralized media management hub for all character creation assets. It stores images, audio, GIFs, and videos generated by other tools (Face Maker, Style Transfer, Character Gif, etc.) and makes them available for reuse in Relationship Web, Character Card, Chronicle, and other modules.

[Supported Formats]
- Images: PNG, JPG, WebP, BMP, SVG
- GIF: Animated and static GIFs
- Audio: MP3, WAV, OGG, FLAC, M4A, AAC, WebM
- Video: MP4, MOV, AVI, MKV
- Max single file size: 15 MB
- Max total assets: 200

[Storage Architecture]
Assets are stored in a two-tier system:
1. IndexedDB (primary): Large binary data (data URLs) are stored in the browser's IndexedDB, which supports hundreds of megabytes.
2. localStorage (legacy fallback): If IndexedDB is unavailable or full, small assets fall back to localStorage. The system automatically migrates legacy localStorage data to IndexedDB on read.

[Key Features]
- Grid and list view modes
- Type filtering (All / Image / Audio / GIF / Video)
- Tag-based organization
- Bulk select, delete, and download
- Drag-and-drop import
- Clipboard paste import
- Cross-origin URL import (CORS-permitting)
- Search by name

[Performance Tips]
- Use grid view for quick visual scanning; use list view for detailed metadata inspection.
- Tag assets immediately after import to keep large galleries organized.
- Bulk delete unused assets periodically to free IndexedDB quota.`,
    buttons: [
      { name: 'Upload Image', description: 'Opens the system file picker to import one or more files from local disk.' },
      { name: 'Import from URL', description: 'Downloads an image from a given URL and adds it to the gallery. Requires CORS headers on the remote server.' },
      { name: 'Paste from Clipboard', description: 'Reads image data from the clipboard and creates a new asset. Works with screenshots and copied images.' },
      { name: 'Delete Asset', description: 'Removes the selected asset from storage. This action is irreversible.' },
      { name: 'Download Asset', description: 'Exports the asset back to your local downloads folder.' },
      { name: 'Copy to Clipboard', description: 'Copies the asset data URL to the clipboard for pasting into other apps.' },
      { name: 'Add Tag', description: 'Assigns a custom text tag to an asset for filtering and organization.' },
      { name: 'Filter by Type', description: 'Narrows the visible assets to a specific media type.' },
      { name: 'Toggle View Mode', description: 'Switches between grid thumbnail view and compact list view.' },
      { name: 'Bulk Select', description: 'Enables multi-select mode to perform actions on many assets at once.' },
      { name: 'Bulk Delete', description: 'Deletes all currently selected assets in one operation.' },
    ],
    parameters: [
      { name: 'Sort Order', description: 'Controls the display order: by upload date, file name, or file size.' },
      { name: 'Filter by Type', description: 'Restricts the gallery to show only images, audio, GIFs, or videos.' },
      { name: 'Max Display Count', description: 'Limits how many assets are rendered at once to improve performance on large galleries.' },
      { name: 'Thumbnail Size', description: 'Adjusts the size of grid thumbnails (small / medium / large).' },
      { name: 'Auto-import on Paste', description: 'When enabled, pasting an image anywhere in the app automatically imports it into the gallery.' },
    ],
    errors: [
      { code: 'ASSET_IMPORT_CORS_BLOCKED', message: 'Cross-origin image blocked by CORS policy.', severity: 'error', category: 'Import', location: 'AssetGalleryPage → handleUrlImport', cause: 'The remote server does not send Access-Control-Allow-Origin headers, so the browser refuses to read the image data into a canvas.', solution: 'Download the image manually and upload it from disk, or use a CORS proxy.', steps: ['Right-click the image and choose "Save image as..."', 'Return to Asset Gallery and click Upload Image', 'Select the downloaded file'], relatedCodes: ['ASSET_IMPORT_URL_INVALID'], prevention: 'Always prefer local upload over hot-linking when CORS status is unknown.' },
      { code: 'ASSET_IMPORT_URL_INVALID', message: 'The provided URL is not a valid image.', severity: 'warning', category: 'Import', location: 'AssetGalleryPage → handleUrlImport', cause: 'The URL does not point to a supported image format or returned a non-image MIME type.', solution: 'Verify the URL is a direct link to an image file (ends with .png, .jpg, etc.).', steps: ['Open the URL in a new tab', 'Confirm it displays an image', 'Copy the direct image URL (not a gallery page URL)'], relatedCodes: ['ASSET_IMPORT_CORS_BLOCKED'], prevention: 'Use browser DevTools Network panel to check the Content-Type header before importing.' },
      { code: 'ASSET_CLIPBOARD_EMPTY', message: 'Clipboard contains no image data.', severity: 'info', category: 'Import', location: 'AssetGalleryPage → handlePaste', cause: 'The clipboard either holds text/non-image data or the browser denied clipboard read access.', solution: 'Copy an actual image (not a file path) to the clipboard and try again.', steps: ['Take a screenshot or copy an image from an image viewer', 'Click inside the Asset Gallery page', 'Press Ctrl+V / Cmd+V'], relatedCodes: [], prevention: 'Ensure the page has focus before pasting; some browsers require user interaction before granting clipboard access.' },
      { code: 'ASSET_STORAGE_QUOTA_EXCEEDED', message: 'Browser storage quota is full.', severity: 'error', category: 'Storage', location: 'AssetGalleryPage → saveAssetDataUrl', cause: 'IndexedDB or localStorage has reached the browser-imposed quota limit for this origin.', solution: 'Delete old or large assets to free space, or export assets to local disk and re-import later.', steps: ['Go to Asset Gallery', 'Select unused assets', 'Click Bulk Delete', 'Retry the import'], relatedCodes: [], prevention: 'Regularly archive assets to local disk and delete them from the browser. Use external storage for long-term preservation.' },
      { code: 'ASSET_DECODE_FAILED', message: 'Image file is corrupted or uses an unsupported format.', severity: 'error', category: 'Import', location: 'AssetGalleryPage → handleFileImport', cause: 'The file header does not match any known image signature, or the file is truncated.', solution: 'Open the file in an image viewer to verify integrity, then re-export it in a standard format.', steps: ['Open the file locally in an image viewer', 'If it opens, re-save as PNG', 'Re-import the re-saved file'], relatedCodes: ['ASSET_IMPORT_URL_INVALID'], prevention: 'Avoid renaming file extensions manually; always use proper export from the source application.' },
    ],
  },
  {
    id: 'character-battle-card',
    title: 'Character Battle Card',
    overview: `The Character Battle Card generator creates RPG-style battle/trading cards from character data. It pulls stats from the Character Stats Designer and skills from the Skill Tree to produce visually rich cards suitable for game design, character showcases, or tabletop RPG sessions.

[Card Templates]
- Standard TCG: Horizontal layout resembling trading card games
- Vertical Stat Card: Tall portrait-oriented layout with stacked stats
- Minimal Badge: Compact circular or square badge for quick reference

[Data Integration]
- Character profile (name, alias, theme color) from Character Card
- Stats (HP, MP, ATK, DEF, SPD, CRT) from Character Stats Designer
- Skills from Character Skill Tree (up to 6 active + 4 passive)
- Auto-calculated combat power score based on weighted stat formula

[Export Formats]
- PNG (1x / 2x / 4x resolution)
- JSON (structured data for game engines)
- Print-ready PDF (A4 sheet with multiple cards)

[Customization]
- Frame theme (metal, wood, magic, tech, paper)
- Background style (gradient, pattern, transparent)
- Stat display mode (numeric value, progress bar, tier badge)
- Rarity stars (1~5★) with color-coded borders`,
    buttons: [
      { name: 'Generate Card', description: 'Renders the battle card using current linked character data.' },
      { name: 'Randomize Stats', description: 'Applies random but balanced stat values for quick prototyping.' },
      { name: 'Import from Character Profile', description: 'Pulls the latest data from Character Card, Stats, and Skill Tree modules.' },
      { name: 'Export as PNG', description: 'Downloads the card as a high-resolution PNG image.' },
      { name: 'Export as JSON', description: 'Exports structured card data compatible with game engines.' },
      { name: 'Toggle Layout', description: 'Cycles through Standard TCG, Vertical Stat, and Minimal Badge layouts.' },
      { name: 'Toggle Frame Style', description: 'Changes the card border/frame visual theme.' },
      { name: 'Edit Stat Values', description: 'Manually override auto-calculated stats for fine-tuning.' },
      { name: 'Add Skill Icon', description: 'Assigns a visual icon to a skill slot on the card.' },
    ],
    parameters: [
      { name: 'Card Template', description: 'Selects the overall layout and proportions of the card.', tips: 'Standard TCG works best for horizontal portraits; Vertical Stat suits full-body art.' },
      { name: 'Frame Theme', description: 'Determines the visual style of the card border and decorations.', tips: 'Metal for sci-fi characters, Wood for fantasy rangers, Magic for mages, Tech for cyborgs.' },
      { name: 'Stat Display Mode', description: 'Controls how numeric stats are presented: plain numbers, progress bars, or tier badges.', tips: 'Progress bars are most intuitive for quick comparison; tier badges work well in minimal layouts.' },
      { name: 'Resolution', description: 'Export resolution multiplier: 1x (standard), 2x (retina), 4x (print quality).', tips: '2x is recommended for social media sharing; 4x produces very large files.' },
      { name: 'Rarity', description: 'Sets the star rating (1~5★) which affects border glow and color.', tips: '5★ cards use gold borders; 1★ cards use gray.' },
    ],
    errors: [
      { code: 'BATTLE_CARD_NO_CHARACTER_DATA', message: 'No linked character profile found.', severity: 'error', category: 'Data', location: 'CharacterBattleCardPage → generateCard', cause: 'The battle card requires a character profile, but none has been created or linked.', solution: 'Create a character in the Character Card module first, then return to Battle Card and click "Import from Character Profile".', steps: ['Open Character Card module', 'Create or edit a character', 'Save the profile', 'Return to Battle Card and import'], relatedCodes: [], prevention: 'Always establish a character profile before designing battle cards.' },
      { code: 'BATTLE_CARD_EXPORT_FAILED', message: 'Canvas export failed.', severity: 'error', category: 'Export', location: 'CharacterBattleCardPage → exportPng', cause: 'The generated card is too large for the browser canvas, or the canvas is tainted by cross-origin images.', solution: 'Reduce the resolution multiplier or ensure all images are from the same origin.', steps: ['Set resolution to 1x', 'Remove custom background images', 'Retry export'], relatedCodes: [], prevention: 'Avoid using external background images; use built-in gradients and patterns instead.' },
      { code: 'BATTLE_CARD_FONT_LOAD_FAILED', message: 'Card font failed to load.', severity: 'warning', category: 'Rendering', location: 'CharacterBattleCardPage → renderCard', cause: 'The custom card font (Noto Sans SC / JetBrains Mono) could not be loaded from the Google Fonts CDN.', solution: 'Check your internet connection and retry. The card will fall back to system fonts.', steps: ['Verify internet connectivity', 'Wait a few seconds for fonts to load', 'Regenerate the card'], relatedCodes: [], prevention: 'Fonts are cached after first load; subsequent card generations will not encounter this issue.' },
      { code: 'BATTLE_CARD_IMAGE_TOO_LARGE', message: 'Background image exceeds canvas limit.', severity: 'error', category: 'Import', location: 'CharacterBattleCardPage → setBackgroundImage', cause: 'The uploaded background image is larger than the browser canvas maximum size (typically 32,768 pixels in either dimension).', solution: 'Resize the image to under 4096x4096 pixels before uploading.', steps: ['Open the image in an editor', 'Scale down to 2048x2048 or smaller', 'Re-upload as background'], relatedCodes: ['BATTLE_CARD_EXPORT_FAILED'], prevention: 'Pre-scale background images before importing them into the battle card designer.' },
    ],
  },
];

const zh: DocsToolSection[] = [
  {
    id: 'asset-gallery',
    title: '素材图库',
    overview: `素材图库是所有角色创作资源的集中管理中心。它存储由其他工具（捏脸、转画风、角色GIF等）生成的图片、音频、GIF 和视频，并使其可在角色关系网、角色设定卡、编年史等模块中复用。

[支持的格式]
- 图片：PNG、JPG、WebP、BMP、SVG
- GIF：动态和静态 GIF
- 音频：MP3、WAV、OGG、FLAC、M4A、AAC、WebM
- 视频：MP4、MOV、AVI、MKV
- 单个文件最大：15 MB
- 资源总数上限：200

[存储架构]
资源采用双层存储系统：
1. IndexedDB（主存储）：大型二进制数据（data URL）存储在浏览器的 IndexedDB 中，支持数百兆容量。
2. localStorage（兼容降级）：如果 IndexedDB 不可用或已满，小资源会降级到 localStorage。系统在读取时会自动将旧版 localStorage 数据迁移到 IndexedDB。

[主要功能]
- 网格视图和列表视图
- 按类型筛选（全部/图片/音频/GIF/视频）
- 标签分类管理
- 批量选择、删除和下载
- 拖拽导入
- 剪贴板粘贴导入
- 跨域 URL 导入（需 CORS 许可）
- 按名称搜索

[性能提示]
- 网格视图适合快速视觉浏览；列表视图适合查看详细元数据。
- 导入后立即为资源打标签，以便大型图库保持有序。
- 定期批量删除未使用的资源以释放 IndexedDB 配额。`,
    buttons: [
      { name: '上传图片', description: '打开系统文件选择器，从本地磁盘导入一个或多个文件。' },
      { name: '从 URL 导入', description: '从给定 URL 下载图片并添加到图库。远程服务器需要发送 CORS 头。' },
      { name: '从剪贴板粘贴', description: '从剪贴板读取图片数据并创建新资源。适用于截图和复制的图片。' },
      { name: '删除资源', description: '从存储中删除选定的资源。此操作不可撤销。' },
      { name: '下载资源', description: '将资源导出到本地下载文件夹。' },
      { name: '复制到剪贴板', description: '将资源 data URL 复制到剪贴板，以便粘贴到其他应用中。' },
      { name: '添加标签', description: '为资源分配自定义文本标签，用于筛选和分类。' },
      { name: '按类型筛选', description: '将可见资源限定为特定媒体类型。' },
      { name: '切换视图模式', description: '在网格缩略图视图和紧凑列表视图之间切换。' },
      { name: '批量选择', description: '启用多选模式，对多个资源同时执行操作。' },
      { name: '批量删除', description: '一次性删除所有当前选中的资源。' },
    ],
    parameters: [
      { name: '排序方式', description: '控制显示顺序：按上传日期、文件名或文件大小。' },
      { name: '按类型筛选', description: '限制图库仅显示图片、音频、GIF 或视频。' },
      { name: '最大显示数量', description: '限制一次性渲染的资源数量，以提升大型图库性能。' },
      { name: '缩略图尺寸', description: '调整网格缩略图的大小（小/中/大）。' },
      { name: '粘贴自动导入', description: '启用后，在应用任何位置粘贴图片都会自动导入到图库。' },
    ],
    errors: [
      { code: 'ASSET_IMPORT_CORS_BLOCKED', message: '跨域图片被 CORS 策略阻止。', severity: 'error', category: '导入', location: 'AssetGalleryPage → handleUrlImport', cause: '远程服务器未发送 Access-Control-Allow-Origin 头，浏览器拒绝将图片数据读入 canvas。', solution: '手动下载图片后从磁盘上传，或使用 CORS 代理。', steps: ['右键点击图片并选择"图片另存为..."', '返回素材图库并点击上传图片', '选择下载的文件'], relatedCodes: ['ASSET_IMPORT_URL_INVALID'], prevention: '在 CORS 状态未知时，优先使用本地上传而非热链接。' },
      { code: 'ASSET_IMPORT_URL_INVALID', message: '提供的 URL 不是有效的图片。', severity: 'warning', category: '导入', location: 'AssetGalleryPage → handleUrlImport', cause: 'URL 不指向支持的图片格式，或返回了非图片 MIME 类型。', solution: '确认 URL 是图片文件的直链（以 .png、.jpg 等结尾）。', steps: ['在新标签页打开 URL', '确认它显示为图片', '复制直链图片 URL（而非图库页面 URL）'], relatedCodes: ['ASSET_IMPORT_CORS_BLOCKED'], prevention: '导入前使用浏览器开发者工具网络面板检查 Content-Type 头。' },
      { code: 'ASSET_CLIPBOARD_EMPTY', message: '剪贴板中不包含图片数据。', severity: 'info', category: '导入', location: 'AssetGalleryPage → handlePaste', cause: '剪贴板中包含文本/非图片数据，或浏览器拒绝了剪贴板读取权限。', solution: '复制实际图片（而非文件路径）到剪贴板后重试。', steps: ['截图或从图片查看器复制图片', '点击素材图库页面获取焦点', '按 Ctrl+V / Cmd+V'], relatedCodes: [], prevention: '粘贴前确保页面有焦点；部分浏览器需要用户交互后才授予剪贴板访问权限。' },
      { code: 'ASSET_STORAGE_QUOTA_EXCEEDED', message: '浏览器存储配额已满。', severity: 'error', category: '存储', location: 'AssetGalleryPage → saveAssetDataUrl', cause: 'IndexedDB 或 localStorage 已达到浏览器对该来源施加的配额限制。', solution: '删除旧资源或大资源释放空间，或将资源导出到本地磁盘后重新导入。', steps: ['进入素材图库', '选择未使用的资源', '点击批量删除', '重试导入'], relatedCodes: [], prevention: '定期将资源归档到本地磁盘并从浏览器中删除。长期保存请使用外部存储。' },
      { code: 'ASSET_DECODE_FAILED', message: '图片文件损坏或使用了不支持的格式。', severity: 'error', category: '导入', location: 'AssetGalleryPage → handleFileImport', cause: '文件头不匹配任何已知的图片签名，或文件被截断。', solution: '在图片查看器中打开文件验证完整性，然后以标准格式重新导出。', steps: ['在本地图片查看器中打开文件', '如果能打开，另存为 PNG', '重新导入另存后的文件'], relatedCodes: ['ASSET_IMPORT_URL_INVALID'], prevention: '避免手动重命名文件扩展名；始终使用源应用程序的正确导出功能。' },
    ],
  },
  {
    id: 'character-battle-card',
    title: '角色战斗卡',
    overview: `角色战斗卡生成器根据角色数据创建 RPG 风格的战斗/交易卡。它从角色属性设计器提取属性，从技能树提取技能，生成视觉效果丰富的卡片，适用于游戏设计、角色展示或桌面 RPG 跑团。

[卡片模板]
- 标准 TCG：横向布局，类似集换式卡牌游戏
- 纵向属性卡：竖向人像布局，属性堆叠显示
- 极简徽章：紧凑的圆形或方形徽章，用于快速参考

[数据联动]
- 角色档案（名称、别名、主题色）来自角色设定卡
- 属性（HP、MP、ATK、DEF、SPD、CRT）来自角色属性设计器
- 技能来自角色技能树（最多 6 个主动 + 4 个被动）
- 基于加权属性公式自动计算战斗力评分

[导出格式]
- PNG（1x / 2x / 4x 分辨率）
- JSON（结构化数据，供游戏引擎使用）
- 打印就绪 PDF（A4 纸，可排布多张卡片）

[自定义选项]
- 边框主题（金属、木质、魔法、科技、纸张）
- 背景样式（渐变、图案、透明）
- 属性显示模式（数值、进度条、等级徽章）
- 稀有度星级（1~5★）及对应颜色边框`,
    buttons: [
      { name: '生成卡片', description: '使用当前关联的角色数据渲染战斗卡。' },
      { name: '随机属性', description: '应用随机但平衡的属性值，用于快速原型设计。' },
      { name: '从角色档案导入', description: '从角色设定卡、属性、技能树模块拉取最新数据。' },
      { name: '导出为 PNG', description: '以高分辨率 PNG 图片下载卡片。' },
      { name: '导出为 JSON', description: '导出与游戏引擎兼容的结构化卡片数据。' },
      { name: '切换布局', description: '在标准 TCG、纵向属性和极简徽章布局之间循环切换。' },
      { name: '切换边框样式', description: '更改卡片边框/装饰的视觉主题。' },
      { name: '编辑属性值', description: '手动覆盖自动计算的属性进行精细调整。' },
      { name: '添加技能图标', description: '为卡片上的技能槽分配视觉图标。' },
    ],
    parameters: [
      { name: '卡片模板', description: '选择卡片的整体布局和比例。', tips: '标准 TCG 适合横向人像；纵向属性适合全身 artwork。' },
      { name: '边框主题', description: '决定卡片边框和装饰的视觉风格。', tips: '科幻角色用金属，奇幻游侠用木质，法师用魔法，赛博格用科技。' },
      { name: '属性显示模式', description: '控制数值属性的呈现方式：纯数字、进度条或等级徽章。', tips: '进度条最便于快速比较；等级徽章在极简布局中效果很好。' },
      { name: '分辨率', description: '导出分辨率倍数：1x（标准）、2x（视网膜）、4x（印刷质量）。', tips: '2x 推荐用于社交媒体分享；4x 会产生非常大的文件。' },
      { name: '稀有度', description: '设置星级评分（1~5★），影响边框发光和颜色。', tips: '5★ 卡片使用金色边框；1★ 卡片使用灰色边框。' },
    ],
    errors: [
      { code: 'BATTLE_CARD_NO_CHARACTER_DATA', message: '未找到关联的角色档案。', severity: 'error', category: '数据', location: 'CharacterBattleCardPage → generateCard', cause: '战斗卡需要角色档案，但尚未创建或关联任何档案。', solution: '先在角色设定卡模块创建角色，然后返回战斗卡并点击"从角色档案导入"。', steps: ['打开角色设定卡模块', '创建或编辑角色', '保存档案', '返回战斗卡并导入'], relatedCodes: [], prevention: '设计战斗卡前务必先建立角色档案。' },
      { code: 'BATTLE_CARD_EXPORT_FAILED', message: 'Canvas 导出失败。', severity: 'error', category: '导出', location: 'CharacterBattleCardPage → exportPng', cause: '生成的卡片太大超出浏览器 canvas 限制，或 canvas 被跨域图片污染。', solution: '降低分辨率倍数，或确保所有图片来自同一来源。', steps: ['将分辨率设为 1x', '移除自定义背景图片', '重试导出'], relatedCodes: [], prevention: '避免使用外部背景图片；使用内置渐变和图案。' },
      { code: 'BATTLE_CARD_FONT_LOAD_FAILED', message: '卡片字体加载失败。', severity: 'warning', category: '渲染', location: 'CharacterBattleCardPage → renderCard', cause: '自定义卡片字体（Noto Sans SC / JetBrains Mono）无法从 Google Fonts CDN 加载。', solution: '检查网络连接后重试。卡片将回退到系统字体。', steps: ['确认网络连接正常', '等待几秒让字体加载', '重新生成卡片'], relatedCodes: [], prevention: '字体在首次加载后会被缓存；后续卡片生成不会遇到此问题。' },
      { code: 'BATTLE_CARD_IMAGE_TOO_LARGE', message: '背景图片超出 canvas 限制。', severity: 'error', category: '导入', location: 'CharacterBattleCardPage → setBackgroundImage', cause: '上传的背景图片大于浏览器 canvas 最大尺寸（通常任一维度为 32,768 像素）。', solution: '上传前将图片缩放至 4096x4096 像素以下。', steps: ['在编辑器中打开图片', '缩放至 2048x2048 或更小', '重新上传为背景'], relatedCodes: ['BATTLE_CARD_EXPORT_FAILED'], prevention: '导入战斗卡设计器前预先缩放背景图片。' },
    ],
  },
];

export function getExtraTools(language: string): DocsToolSection[] {
  if (language === 'zh' || language === 'zh-CN' || language === 'zh-TW') return zh;
  return en;
}
