#!/usr/bin/env python3
"""Batch update index-tts errors in docsContent files for 5 main languages."""
import re
import glob
import os

ZH_ERRORS_TEXT = """      errors: [
        {
          code: 'API_KEY_MISSING',
          message: '点击「生成语音」后立刻报错，错误面板显示 API Key 相关错误',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '未在「设置 → API」中配置 API Key，或 Key 被清空。IndexTTS 生成需要有效的 API Key 才能调用后端语音合成服务。',
          solution: '在设置面板中配置有效的 API Key。',
          steps: ['点击右上角「打开设置」或按对应快捷键', '切换到「API」标签页', '在「API Key」输入框中填入你的有效 Key', '点击「保存」后关闭设置面板', '返回 IndexTTS 页面重新点击「生成语音」'],
          relatedCodes: ['API_KEY_EXPIRED', 'INDEX_TTS_NOT_CONFIGURED'],
          prevention: '首次使用任何联网工具前，务必先在「设置 → API」中配置有效的 API Key。',
        },
        {
          code: 'API_KEY_EXPIRED',
          message: '生成请求返回 401 或提示 Key 无效',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '配置的 API Key 已过期、被吊销、或额度已用完。',
          solution: '更换有效的 API Key。',
          steps: ['打开「设置 → API」面板', '删除当前 Key，填入新的有效 Key', '如果不确定 Key 是否有效，可在 LLM Hub 的实时测试面板中先测试', '保存后返回 IndexTTS 重试'],
          relatedCodes: ['API_KEY_MISSING', '401_UNAUTHORIZED'],
          prevention: '定期检查 API Key 的有效期和剩余额度；在 LLM Hub 中通过实时测试快速验证 Key 是否有效。',
        },
        {
          code: 'API_TIMEOUT',
          message: '请求长时间无响应，最终提示超时',
          severity: 'error',
          category: 'A. API 与网络',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板 / 进度条',
          cause: '后端生成耗时过长，超过了前端设置的超时时间。TTS 生成对 GPU 性能要求较高，长文本或高采样率时更耗时。',
          solution: '缩短文本长度、降低采样率或检查网络连接。',
          steps: ['缩短输入文本长度（建议控制在 200 字以内）', '降低采样率（如从 48000Hz 降至 22050Hz）', '检查网络连接是否稳定', '如果使用 CPU 推理，考虑切换到 GPU 模式', '重试生成'],
          relatedCodes: ['NETWORK_TIMEOUT', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: '长文本生成耗时更长；提前缩短文本长度；网络不稳定时增加超时设置。',
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: '提示「后端不可用」或「无法连接到服务器」',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '后端服务器未启动、崩溃、或前端配置的 API Base URL 不正确。',
          solution: '检查后端服务状态和 API 配置。',
          steps: ['打开浏览器开发者工具 → Network 标签页', '重新点击「生成语音」，观察请求是否发出以及响应状态码', '如果请求未发出，检查「设置 → API → API Base URL」是否正确', '如果请求返回 502/503，联系后端管理员确认服务状态', '如果是本地部署，确认后端进程是否在运行（npm start）'],
          relatedCodes: ['NETWORK_DISCONNECTED', '502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
          prevention: '本地部署时确保后端进程已启动（npm start）；使用远程服务时确认 URL 配置正确。',
        },
        {
          code: 'NETWORK_DISCONNECTED',
          message: '提示网络断开或无法访问互联网',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '设备未连接网络、Wi-Fi 断开、或防火墙阻止了请求。',
          solution: '恢复网络连接。',
          steps: ['检查设备的网络连接状态', '尝试访问其他网站确认网络是否正常', '如果使用代理/VPN，检查代理设置是否正确', '如果是公司/校园网络，确认是否限制了 API 访问'],
          relatedCodes: ['BACKEND_UNAVAILABLE', 'API_TIMEOUT'],
          prevention: '使用联网工具前确认网络连接正常；避免在网络波动大的环境下进行长时间工作流。',
        },
        {
          code: 'AUDIO_FORMAT_UNSUPPORTED',
          message: '上传时提示「不支持的音频格式」',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：IndexTTS 语音合成 → 区域：参考音频上传区',
          cause: '选择了 FLAC、OGG、AAC、WMA 或其他不支持的格式。IndexTTS 仅支持 WAV 和 MP3 格式的参考音频。',
          solution: '将音频转换为 WAV 或 MP3 格式。',
          steps: ['使用音频转换工具将文件转为 WAV 或 MP3', '或使用系统自带的音频编辑工具导出为 WAV/MP3', '确保采样率为 22050Hz 或以上', '重新在 IndexTTS 页面上传转换后的文件'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_TOO_LONG'],
          prevention: '确认文件格式是 WAV 或 MP3 后再上传。',
        },
        {
          code: 'AUDIO_TOO_SHORT',
          message: '提示「参考音频太短」',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：IndexTTS 语音合成 → 区域：参考音频上传区',
          cause: '参考音频时长不足 3 秒。零样本音色克隆需要至少 3 秒的音频才能提取有效的音色特征。',
          solution: '上传更长的参考音频。',
          steps: ['录制或截取一段 5~10 秒的音频', '确保音频中只有一个说话人', '重新上传音频文件'],
          relatedCodes: ['AUDIO_TOO_LONG', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: '准备 5~10 秒的参考音频，确保内容清晰完整。',
        },
        {
          code: 'AUDIO_TOO_LONG',
          message: '提示「参考音频太长」或处理超时',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：IndexTTS 语音合成 → 区域：参考音频上传区',
          cause: '参考音频时长超过 10 秒。过长的参考音频会增加处理时间和后端负载，且对克隆效果的提升有限。',
          solution: '截取音频至 3~10 秒。',
          steps: ['使用音频编辑工具截取音频的中间 5~7 秒', '确保截取部分包含清晰的说话声', '保存为 WAV 或 MP3 后重新上传'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: '准备 5~10 秒的参考音频；过长的音频对克隆效果提升有限，反而增加处理时间。',
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: '错误面板显示「模型不可用」或 404',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '选择的模型在后端不存在、已被下架、或当前 API Key 无权访问该模型。',
          solution: '切换到其他可用模型。',
          steps: ['在「模型」下拉框中选择其他模型（如 index-tts-1.5）', '确认模型名称拼写正确', '在「设置 → API」中确认当前 Key 支持所选模型', '重试生成'],
          relatedCodes: ['INDEX_TTS_NOT_CONFIGURED', 'API_KEY_EXPIRED'],
          prevention: '从下拉列表选择已知可用的模型；使用自定义 API 时查阅服务商文档确认模型列表。',
        },
        {
          code: 'INDEX_TTS_TEXT_MISSING',
          message: '点击「生成语音」后立刻报错，提示未输入文本',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '文本输入框为空。IndexTTS 需要有效的文本输入才能生成语音。',
          solution: '在文本输入框中输入要合成的内容。',
          steps: ['点击文本输入区域', '输入或粘贴要合成的文本', '确认文本不为空', '点击「生成语音」'],
          relatedCodes: ['INDEX_TTS_TEXT_TOO_LONG', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: '生成前始终确认文本输入包含有效内容。',
        },
        {
          code: 'INDEX_TTS_TEXT_TOO_LONG',
          message: '提示「文本过长」或生成超时',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：IndexTTS 语音合成 → 区域：文本输入框 / 左栏底部错误面板',
          cause: '输入文本过长（超过 500 字），超过了后端模型的最大处理限制。',
          solution: '缩短输入文本。',
          steps: ['将长文本拆分为多段，每段不超过 200 字', '删除冗余描述和重复内容', '分段生成后使用音频编辑工具合并', '重试'],
          relatedCodes: ['INDEX_TTS_TEXT_MISSING', 'API_TIMEOUT'],
          prevention: '单段文本控制在 500 字以内；长内容建议分段生成。',
        },
        {
          code: 'INDEX_TTS_TEXT_BLOCKED',
          message: '请求被拦截，提示「内容策略违规」或「sensitive words」',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '输入文本中包含了后端服务商的安全过滤器拦截的词汇。',
          solution: '修改文本，移除或替换可能触发过滤器的词汇。',
          steps: ['查看错误详情中的具体提示信息，找出被拦截的关键词', '将敏感词汇用同义词替换或删除', '先用简单的测试文本确认服务正常', '逐步添加内容，找出具体触发拦截的词汇'],
          relatedCodes: ['403_FORBIDDEN'],
          prevention: '避免在文本中使用敏感词汇；先用默认文本测试通过后再自定义。',
        },
        {
          code: 'INDEX_TTS_REQUEST_FAILED',
          message: '错误面板上显示「INDEX_TTS_REQUEST_FAILED」',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '后端 API 请求失败。可能是网络中断、API Key 无效、模型不可用、GPU 显存不足、文本过长、或服务器内部错误。',
          solution: '根据错误详情中的具体信息排查。',
          steps: ['展开错误面板查看详细错误信息（HTTP 状态码、后端返回的消息）', '如果是 401：检查 API Key 是否有效', '如果是 404：检查模型是否可用', '如果是 429：等待一段时间后重试', '如果是 500/502/503：检查后端服务状态', '如果是 GPU 错误：降低文本长度或采样率', '如果是网络错误：检查网络连接'],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: '开始生成前确认 API Key 有效、网络连接正常、模型可用；首次生成建议先用短文本测试。',
        },
        {
          code: 'INDEX_TTS_NOT_CONFIGURED',
          message: 'IndexTTS 后端未配置',
          severity: 'error',
          category: 'E. 配置与数据',
          location: '服务器 → /api/index-tts',
          cause: '后端没有配置 IndexTTS 提供商。后端路由返回了明确的未配置错误。',
          solution: '在后端配置 IndexTTS 提供商。',
          steps: ['检查后端 .env 文件是否包含 IndexTTS 相关配置', '配置 IndexTTS API 密钥（如 SiliconFlow）', '将提供商配置添加到后端 .env', '重启后端服务器', '返回前端重试'],
          relatedCodes: ['INDEX_TTS_REQUEST_FAILED', 'BACKEND_UNAVAILABLE'],
          prevention: '部署后端时配置好 IndexTTS 提供商；使用前确认后端已正确配置。',
        },
        {
          code: 'INDEX_TTS_GPU_OUT_OF_MEMORY',
          message: '后端返回 GPU 显存不足错误',
          severity: 'error',
          category: 'F. 系统与权限',
          location: '服务器 → GPU 推理进程',
          cause: 'GPU 显存不足以加载模型或处理当前请求。长文本、高采样率、大尺寸模型会占用更多显存。',
          solution: '缩短文本、降低采样率、切换到 CPU 模式，或升级 GPU。',
          steps: ['缩短输入文本长度', '降低采样率（如 48000Hz → 22050Hz）', '切换到 CPU 推理模式', '关闭其他占用显存的程序', '如果问题持续，联系后端管理员升级 GPU 显存'],
          relatedCodes: ['500_INTERNAL_ERROR', 'API_TIMEOUT'],
          prevention: '长文本和高采样率消耗更多显存；建议文本控制在 200 字以内，使用 22050Hz 采样率。',
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: '提示请求过于频繁（Rate Limit）',
          severity: 'warning',
          category: 'A. API 与网络',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '短时间内发送了过多请求，超过了服务商的速率限制。',
          solution: '等待一段时间后重试。',
          steps: ['查看错误详情中的 Retry-After 提示（如果有）', '等待 60~120 秒后重试', '如果频繁遇到此问题，缩短文本长度', '考虑升级 API 套餐以获得更高的速率限制'],
          relatedCodes: ['API_RATE_LIMIT', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: '适当降低请求频率；避免在短时间内多次重试。',
        },
        {
          code: '500_INTERNAL_ERROR',
          message: '后端返回 500 内部服务器错误',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '后端服务在处理请求时发生内部异常。可能是模型加载失败、GPU 内存不足、或代码 Bug。',
          solution: '稍后重试或联系后端管理员。',
          steps: ['等待 1~2 分钟后重试', '缩短文本长度、降低采样率，减少后端负载', '切换到 CPU 推理模式', '如果问题持续，联系后端管理员查看服务器日志'],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: '降低请求规模（文本长度、采样率等）；避免在服务器高负载时提交大任务。',
        },
        {
          code: '502_BAD_GATEWAY',
          message: '后端返回 502 Bad Gateway',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '反向代理（如 Nginx）无法连接到后端应用服务器。可能是后端进程崩溃或未启动。',
          solution: '检查后端服务状态。',
          steps: ['如果是本地部署，确认后端进程是否在运行', '检查后端服务端口是否被占用', '查看后端日志确认是否有启动错误', '重启后端服务后重试'],
          relatedCodes: ['503_SERVICE_UNAVAILABLE', 'BACKEND_UNAVAILABLE'],
          prevention: '本地部署时确认后端进程在运行；检查反向代理配置。',
        },
        {
          code: '503_SERVICE_UNAVAILABLE',
          message: '后端返回 503 Service Unavailable',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：IndexTTS 语音合成 → 区域：左栏底部错误面板',
          cause: '后端服务暂时不可用，可能正在进行维护、重启、或过载保护。',
          solution: '稍后重试。',
          steps: ['等待 2~3 分钟后重试', '检查后端服务状态页面（如果有）', '联系后端管理员确认是否在维护'],
          relatedCodes: ['502_BAD_GATEWAY', 'BACKEND_UNAVAILABLE'],
          prevention: '避开服务器维护时段操作；高负载时降低请求频率。',
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '导入配置时提示「无效的 JSON 格式」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：IndexTTS 语音合成 → 区域：顶部「导入配置」按钮',
          cause: '文件内容损坏、不是 JSON 格式、或被其他程序修改过。',
          solution: '检查文件是否为有效的 UTF-8 编码文本文件。',
          steps: ['用文本编辑器打开文件查看是否有乱码', '确认文件顶部包含 "tool": "index-tts"', '尝试用 JSON 在线格式化工具验证'],
          relatedCodes: ['IMPORT_TOOL_MISMATCH'],
          prevention: '妥善保存导出的配置文件，避免用非文本编辑器修改。',
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '导入配置时提示「工具类型不匹配」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：IndexTTS 语音合成 → 区域：顶部「导入配置」按钮',
          cause: '导入的 JSON 文件中 tool 字段不是 index-tts。',
          solution: '确认导入的是 IndexTTS 页面导出的配置文件。',
          steps: ['用文本编辑器打开文件', '确认 tool 字段值为 "index-tts"', '如果不是，找到正确的配置文件或从对应工具页面导入'],
          relatedCodes: ['IMPORT_INVALID_JSON'],
          prevention: '不同工具的配置文件不通用；从对应工具页面导出和导入配置。',
        },
      ],"""

EN_ERRORS_TEXT = """      errors: [
        {
          code: 'API_KEY_MISSING',
          message: 'Immediate error after clicking Generate Speech, error panel shows API Key related error',
          severity: 'critical',
          category: 'A. API & Network',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'No API Key configured in Settings → API, or the Key was cleared. IndexTTS generation requires a valid API Key to call the backend speech synthesis service.',
          solution: 'Configure a valid API Key in the settings panel.',
          steps: ['Click Open Settings in the top right or use the shortcut', 'Switch to the API tab', 'Enter your valid Key in the API Key input', 'Click Save and close the settings panel', 'Return to IndexTTS page and click Generate Speech again'],
          relatedCodes: ['API_KEY_EXPIRED', 'INDEX_TTS_NOT_CONFIGURED'],
          prevention: 'Always configure a valid API Key in Settings → API before using any networked tool for the first time.',
        },
        {
          code: 'API_KEY_EXPIRED',
          message: 'Generation request returns 401 or indicates Key is invalid',
          severity: 'critical',
          category: 'A. API & Network',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'The configured API Key has expired, been revoked, or run out of quota.',
          solution: 'Replace with a valid API Key.',
          steps: ['Open Settings → API panel', 'Delete the current Key and enter a new valid Key', 'If unsure whether the Key is valid, test it first in the LLM Hub real-time test panel', 'Save and return to IndexTTS to retry'],
          relatedCodes: ['API_KEY_MISSING', '401_UNAUTHORIZED'],
          prevention: 'Regularly check API Key validity and remaining quota; use LLM Hub real-time testing to quickly verify Key validity.',
        },
        {
          code: 'API_TIMEOUT',
          message: 'Request takes too long and eventually times out',
          severity: 'error',
          category: 'A. API & Network',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel / progress bar',
          cause: 'Backend generation took too long, exceeding the frontend timeout. TTS generation has high GPU requirements; long text or high sample rates take more time.',
          solution: 'Shorten text length, lower sample rate, or check network connection.',
          steps: ['Shorten input text (suggest within 200 characters)', 'Lower sample rate (e.g., from 48000Hz to 22050Hz)', 'Check if network connection is stable', 'If using CPU inference, consider switching to GPU mode', 'Retry generation'],
          relatedCodes: ['NETWORK_TIMEOUT', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: 'Long text takes longer to generate; shorten text in advance; increase timeout settings when network is unstable.',
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: 'Prompt says Backend Unavailable or Cannot connect to server',
          severity: 'critical',
          category: 'A. API & Network',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Backend server is not started, crashed, or the API Base URL configured in frontend is incorrect.',
          solution: 'Check backend service status and API configuration.',
          steps: ['Open browser dev tools → Network tab', 'Click Generate Speech again, observe if request is sent and the response status code', 'If request is not sent, check Settings → API → API Base URL is correct', 'If request returns 502/503, contact backend admin to confirm service status', 'If local deployment, confirm backend process is running (npm start)'],
          relatedCodes: ['NETWORK_DISCONNECTED', '502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
          prevention: 'For local deployment ensure backend process is started (npm start); for remote services confirm URL configuration is correct.',
        },
        {
          code: 'NETWORK_DISCONNECTED',
          message: 'Prompt says network disconnected or cannot access internet',
          severity: 'critical',
          category: 'A. API & Network',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Device is not connected to network, Wi-Fi disconnected, or firewall is blocking requests.',
          solution: 'Restore network connection.',
          steps: ['Check device network connection status', 'Try accessing other websites to confirm network is normal', 'If using proxy/VPN, check proxy settings are correct', 'If on company/campus network, confirm API access is not restricted'],
          relatedCodes: ['BACKEND_UNAVAILABLE', 'API_TIMEOUT'],
          prevention: 'Confirm network connection is normal before using networked tools; avoid operating in environments with high network fluctuation.',
        },
        {
          code: 'AUDIO_FORMAT_UNSUPPORTED',
          message: 'Upload prompt says Unsupported audio format',
          severity: 'warning',
          category: 'C. Files & Input',
          location: 'Page: IndexTTS Voice Synthesis → Area: Reference audio upload zone',
          cause: 'Selected FLAC, OGG, AAC, WMA, or other unsupported format. IndexTTS only supports WAV and MP3 reference audio.',
          solution: 'Convert audio to WAV or MP3 format.',
          steps: ['Use an audio conversion tool to convert file to WAV or MP3', 'Or use system built-in audio editing tool to export as WAV/MP3', 'Ensure sample rate is 22050Hz or above', 'Re-upload the converted file on the IndexTTS page'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_TOO_LONG'],
          prevention: 'Confirm file format is WAV or MP3 before uploading.',
        },
        {
          code: 'AUDIO_TOO_SHORT',
          message: 'Prompt says Reference audio too short',
          severity: 'warning',
          category: 'C. Files & Input',
          location: 'Page: IndexTTS Voice Synthesis → Area: Reference audio upload zone',
          cause: 'Reference audio duration is less than 3 seconds. Zero-shot voice cloning requires at least 3 seconds of audio to extract valid voice characteristics.',
          solution: 'Upload a longer reference audio.',
          steps: ['Record or clip a 5~10 second audio segment', 'Ensure the audio contains only one speaker', 'Re-upload the audio file'],
          relatedCodes: ['AUDIO_TOO_LONG', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: 'Prepare 5~10 seconds of reference audio; ensure content is clear and complete.',
        },
        {
          code: 'AUDIO_TOO_LONG',
          message: 'Prompt says Reference audio too long or processing timed out',
          severity: 'warning',
          category: 'C. Files & Input',
          location: 'Page: IndexTTS Voice Synthesis → Area: Reference audio upload zone',
          cause: 'Reference audio duration exceeds 10 seconds. Overly long reference audio increases processing time and backend load, with diminishing returns on cloning quality.',
          solution: 'Clip audio to 3~10 seconds.',
          steps: ['Use audio editing tool to clip the middle 5~7 seconds of the audio', 'Ensure the clipped portion contains clear speech', 'Save as WAV or MP3 and re-upload'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: 'Prepare 5~10 seconds of reference audio; overly long audio has limited improvement on cloning quality but increases processing time.',
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: 'Error panel shows Model unavailable or 404',
          severity: 'error',
          category: 'D. Model & Generation',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Selected model does not exist on backend, has been removed, or current API Key has no access to this model.',
          solution: 'Switch to another available model.',
          steps: ['Select another model from the Model dropdown (e.g., index-tts-1.5)', 'Confirm model name spelling is correct', 'In Settings → API confirm current Key supports the selected model', 'Retry generation'],
          relatedCodes: ['INDEX_TTS_NOT_CONFIGURED', 'API_KEY_EXPIRED'],
          prevention: 'Select known available models from the dropdown list; consult service provider documentation for model list when using custom API.',
        },
        {
          code: 'INDEX_TTS_TEXT_MISSING',
          message: 'Immediate error after clicking Generate Speech, prompt says no text entered',
          severity: 'warning',
          category: 'C. Files & Input',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Text input box is empty. IndexTTS requires valid text input to generate speech.',
          solution: 'Enter content to synthesize in the text input box.',
          steps: ['Click the text input area', 'Type or paste the text to synthesize', 'Confirm text is not empty', 'Click Generate Speech'],
          relatedCodes: ['INDEX_TTS_TEXT_TOO_LONG', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: 'Always confirm text input contains valid content before generating.',
        },
        {
          code: 'INDEX_TTS_TEXT_TOO_LONG',
          message: 'Prompt says Text too long or generation timed out',
          severity: 'warning',
          category: 'C. Files & Input',
          location: 'Page: IndexTTS Voice Synthesis → Area: Text input box / Left panel bottom error panel',
          cause: 'Input text is too long (over 500 characters), exceeding the backend model maximum processing limit.',
          solution: 'Shorten the input text.',
          steps: ['Split long text into multiple segments, each under 200 characters', 'Remove redundant descriptions and duplicate content', 'Generate segment by segment and merge with audio editing tool', 'Retry'],
          relatedCodes: ['INDEX_TTS_TEXT_MISSING', 'API_TIMEOUT'],
          prevention: 'Keep single-segment text within 500 characters; long content should be generated in segments.',
        },
        {
          code: 'INDEX_TTS_TEXT_BLOCKED',
          message: 'Request blocked, prompt says Content policy violation or sensitive words',
          severity: 'error',
          category: 'D. Model & Generation',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Input text contains words blocked by the backend service provider safety filter.',
          solution: 'Modify text, remove or replace words that may trigger the filter.',
          steps: ['Check error details for specific hints to identify blocked keywords', 'Replace sensitive words with synonyms or delete them', 'First test with simple text to confirm service is normal', 'Gradually add content to identify the specific trigger word'],
          relatedCodes: ['403_FORBIDDEN'],
          prevention: 'Avoid using sensitive words in text; test with default text first before customizing.',
        },
        {
          code: 'INDEX_TTS_REQUEST_FAILED',
          message: 'Error panel shows INDEX_TTS_REQUEST_FAILED',
          severity: 'error',
          category: 'D. Model & Generation',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Backend API request failed. Could be network interruption, invalid API Key, model unavailable, GPU out of memory, text too long, or server internal error.',
          solution: 'Troubleshoot based on specific information in error details.',
          steps: ['Expand error panel to view detailed error info (HTTP status code, backend message)', 'If 401: check if API Key is valid', 'If 404: check if model is available', 'If 429: wait and retry after some time', 'If 500/502/503: check backend service status', 'If GPU error: lower text length or sample rate', 'If network error: check network connection'],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: 'Before generating confirm API Key is valid, network is connected, and model is available; first generation should use short text for testing.',
        },
        {
          code: 'INDEX_TTS_NOT_CONFIGURED',
          message: 'IndexTTS backend not configured',
          severity: 'error',
          category: 'E. Config & Data',
          location: 'Server → /api/index-tts',
          cause: 'Backend has no IndexTTS provider configured. The backend route returned an explicit not-configured error.',
          solution: 'Configure an IndexTTS provider in the backend.',
          steps: ['Check if backend .env file contains IndexTTS related configuration', 'Configure IndexTTS API key (e.g., SiliconFlow)', 'Add provider configuration to backend .env', 'Restart backend server', 'Return to frontend and retry'],
          relatedCodes: ['INDEX_TTS_REQUEST_FAILED', 'BACKEND_UNAVAILABLE'],
          prevention: 'Configure IndexTTS provider when deploying backend; confirm backend is correctly configured before use.',
        },
        {
          code: 'INDEX_TTS_GPU_OUT_OF_MEMORY',
          message: 'Backend returns GPU out of memory error',
          severity: 'error',
          category: 'F. System & Permissions',
          location: 'Server → GPU inference process',
          cause: 'GPU VRAM is insufficient to load the model or process the current request. Long text, high sample rates, and large models consume more VRAM.',
          solution: 'Shorten text, lower sample rate, switch to CPU mode, or upgrade GPU.',
          steps: ['Shorten input text length', 'Lower sample rate (e.g., 48000Hz → 22050Hz)', 'Switch to CPU inference mode', 'Close other programs consuming VRAM', 'If problem persists, contact backend admin to upgrade GPU VRAM'],
          relatedCodes: ['500_INTERNAL_ERROR', 'API_TIMEOUT'],
          prevention: 'Long text and high sample rates consume more VRAM; keep text within 200 characters and use 22050Hz sample rate.',
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: 'Prompt says Too many requests (Rate Limit)',
          severity: 'warning',
          category: 'A. API & Network',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Too many requests sent in a short time, exceeding the service provider rate limit.',
          solution: 'Wait and retry after some time.',
          steps: ['Check error details for Retry-After hint if available', 'Wait 60~120 seconds and retry', 'If frequently encountered, shorten text length', 'Consider upgrading API plan for higher rate limits'],
          relatedCodes: ['API_RATE_LIMIT', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: 'Lower request frequency appropriately; avoid multiple retries in short time.',
        },
        {
          code: '500_INTERNAL_ERROR',
          message: 'Backend returns 500 Internal Server Error',
          severity: 'error',
          category: '0~9. HTTP Status Codes',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Backend service encountered an internal exception while processing the request. Could be model loading failure, GPU memory shortage, or code bug.',
          solution: 'Retry later or contact backend administrator.',
          steps: ['Wait 1~2 minutes and retry', 'Shorten text length, lower sample rate to reduce backend load', 'Switch to CPU inference mode', 'If problem persists, contact backend admin to check server logs'],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: 'Reduce request scale (text length, sample rate, etc.); avoid submitting large tasks during high server load.',
        },
        {
          code: '502_BAD_GATEWAY',
          message: 'Backend returns 502 Bad Gateway',
          severity: 'error',
          category: '0~9. HTTP Status Codes',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Reverse proxy (e.g., Nginx) cannot connect to backend application server. Backend process may have crashed or not started.',
          solution: 'Check backend service status.',
          steps: ['If local deployment, confirm backend process is running', 'Check if backend service port is occupied', 'Check backend logs for startup errors', 'Restart backend service and retry'],
          relatedCodes: ['503_SERVICE_UNAVAILABLE', 'BACKEND_UNAVAILABLE'],
          prevention: 'For local deployment confirm backend process is running; check reverse proxy configuration.',
        },
        {
          code: '503_SERVICE_UNAVAILABLE',
          message: 'Backend returns 503 Service Unavailable',
          severity: 'error',
          category: '0~9. HTTP Status Codes',
          location: 'Page: IndexTTS Voice Synthesis → Area: Left panel bottom error panel',
          cause: 'Backend service is temporarily unavailable, possibly undergoing maintenance, restart, or overload protection.',
          solution: 'Retry later.',
          steps: ['Wait 2~3 minutes and retry', 'Check backend service status page if available', 'Contact backend admin to confirm if maintenance is in progress'],
          relatedCodes: ['502_BAD_GATEWAY', 'BACKEND_UNAVAILABLE'],
          prevention: 'Avoid operating during server maintenance windows; lower request frequency during high load.',
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: 'Import config prompt says Invalid JSON format',
          severity: 'warning',
          category: 'B. Config & Data',
          location: 'Page: IndexTTS Voice Synthesis → Area: Top Import Config button',
          cause: 'File content is corrupted, not in JSON format, or was modified by another program.',
          solution: 'Check if file is a valid UTF-8 encoded text file.',
          steps: ['Open file in text editor to check for garbled characters', 'Confirm file header contains "tool": "index-tts"', 'Try validating with an online JSON formatting tool'],
          relatedCodes: ['IMPORT_TOOL_MISMATCH'],
          prevention: 'Properly save exported config files; avoid modifying with non-text editors.',
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: 'Import config prompt says Tool type mismatch',
          severity: 'warning',
          category: 'B. Config & Data',
          location: 'Page: IndexTTS Voice Synthesis → Area: Top Import Config button',
          cause: 'The tool field in imported JSON file is not index-tts.',
          solution: 'Confirm the imported file is exported from the IndexTTS page.',
          steps: ['Open file in text editor', 'Confirm tool field value is "index-tts"', 'If not, find the correct config file or import from the corresponding tool page'],
          relatedCodes: ['IMPORT_INVALID_JSON'],
          prevention: 'Config files from different tools are not interchangeable; export and import from the corresponding tool page.',
        },
      ],"""

JA_ERRORS_TEXT = """      errors: [
        {
          code: 'API_KEY_MISSING',
          message: '「音声を生成」をクリックするとすぐにエラーが表示され、エラーパネルに API Key 関連のエラーが表示される',
          severity: 'critical',
          category: 'A. API とネットワーク',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: '「設定 → API」で API Key が設定されていないか、Key が空になっています。IndexTTS の生成には有効な API Key が必要です。',
          solution: '設定パネルで有効な API Key を設定します。',
          steps: ['右上の「設定を開く」をクリックするかショートカットを使用', '「API」タブに切り替え', '「API Key」入力欄に有効な Key を入力', '「保存」をクリックして設定パネルを閉じる', 'IndexTTS ページに戻って「音声を生成」を再度クリック'],
          relatedCodes: ['API_KEY_EXPIRED', 'INDEX_TTS_NOT_CONFIGURED'],
          prevention: '初めてネットワークツールを使用する前に、必ず「設定 → API」で有効な API Key を設定してください。',
        },
        {
          code: 'API_KEY_EXPIRED',
          message: '生成リクエストが 401 を返すか、Key が無効と表示される',
          severity: 'critical',
          category: 'A. API とネットワーク',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: '設定された API Key の有効期限が切れたか、失効したか、クォータが使い果たされています。',
          solution: '有効な API Key に交換します。',
          steps: ['「設定 → API」パネルを開く', '現在の Key を削除し、新しい有効な Key を入力', 'Key が有効かどうか不明な場合は、LLM Hub のリアルタイムテストパネルで先にテスト', '保存して IndexTTS に戻って再試行'],
          relatedCodes: ['API_KEY_MISSING', '401_UNAUTHORIZED'],
          prevention: 'API Key の有効期限と残りクォータを定期的に確認；LLM Hub のリアルタイムテストで Key の有効性を迅速に確認してください。',
        },
        {
          code: 'API_TIMEOUT',
          message: 'リクエストが長時間応答せず、最終的にタイムアウトする',
          severity: 'error',
          category: 'A. API とネットワーク',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル / プログレスバー',
          cause: 'バックエンドの生成に時間がかかりすぎ、フロントエンドのタイムアウト時間を超えました。TTS 生成は GPU 性能を要求し、長いテキストや高サンプリングレートではさらに時間がかかります。',
          solution: 'テキストを短くするか、サンプリングレートを下げるか、ネットワーク接続を確認します。',
          steps: ['入力テキストを短くする（200文字以内を推奨）', 'サンプリングレートを下げる（例：48000Hz から 22050Hz）', 'ネットワーク接続が安定しているか確認', 'CPU 推論を使用している場合は GPU モードへの切り替えを検討', '再生成を試行'],
          relatedCodes: ['NETWORK_TIMEOUT', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: '長いテキストは生成に時間がかかります；事前にテキストを短くしてください；ネットワークが不安定な場合はタイムアウト設定を増やしてください。',
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: '「バックエンドが利用できません」または「サーバーに接続できません」と表示される',
          severity: 'critical',
          category: 'A. API とネットワーク',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: 'バックエンドサーバーが起動していないか、クラッシュしたか、フロントエンドに設定された API Base URL が正しくありません。',
          solution: 'バックエンドサービスの状態と API 設定を確認します。',
          steps: ['ブラウザの開発者ツール → Network タブを開く', '「音声を生成」を再度クリックし、リクエストが送信されたかおよび応答ステータスコードを確認', 'リクエストが送信されていない場合は「設定 → API → API Base URL」が正しいか確認', 'リクエストが 502/503 を返す場合は、バックエンド管理者にサービス状態を確認', 'ローカルデプロイの場合は、バックエンドプロセスが実行中か確認（npm start）'],
          relatedCodes: ['NETWORK_DISCONNECTED', '502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
          prevention: 'ローカルデプロイの場合はバックエンドプロセスが起動していることを確認（npm start）；リモートサービスの場合は URL 設定が正しいことを確認してください。',
        },
        {
          code: 'NETWORK_DISCONNECTED',
          message: 'ネットワークが切断されたか、インターネットにアクセスできないと表示される',
          severity: 'critical',
          category: 'A. API とネットワーク',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: 'デバイスがネットワークに接続されていないか、Wi-Fi が切断されたか、ファイアウォールがリクエストをブロックしています。',
          solution: 'ネットワーク接続を復元します。',
          steps: ['デバイスのネットワーク接続状態を確認', '他のウェブサイトにアクセスしてネットワークが正常か確認', 'プロキシ/VPN を使用している場合はプロキシ設定が正しいか確認', '会社/学校のネットワークの場合は API アクセスが制限されていないか確認'],
          relatedCodes: ['BACKEND_UNAVAILABLE', 'API_TIMEOUT'],
          prevention: 'ネットワークツールを使用する前にネットワーク接続が正常であることを確認；ネットワーク変動が大きい環境での長時間操作は避けてください。',
        },
        {
          code: 'AUDIO_FORMAT_UNSUPPORTED',
          message: 'アップロード時に「サポートされていない音声形式」と表示される',
          severity: 'warning',
          category: 'C. ファイルと入力',
          location: 'ページ：IndexTTS 音声合成 → 領域：参照音声アップロードエリア',
          cause: 'FLAC、OGG、AAC、WMA などのサポートされていない形式を選択しました。IndexTTS は WAV と MP3 形式の参照音声のみをサポートしています。',
          solution: '音声を WAV または MP3 形式に変換します。',
          steps: ['音声変換ツールを使用してファイルを WAV または MP3 に変換', 'またはシステム付属の音声編集ツールで WAV/MP3 としてエクスポート', 'サンプリングレートが 22050Hz 以上であることを確認', 'IndexTTS ページで変換後のファイルを再アップロード'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_TOO_LONG'],
          prevention: 'アップロード前にファイル形式が WAV または MP3 であることを確認してください。',
        },
        {
          code: 'AUDIO_TOO_SHORT',
          message: '「参照音声が短すぎる」と表示される',
          severity: 'warning',
          category: 'C. ファイルと入力',
          location: 'ページ：IndexTTS 音声合成 → 領域：参照音声アップロードエリア',
          cause: '参照音声の長さが 3 秒未満です。ゼロショット音声クローニングには、有効な音色特性を抽出するために最低 3 秒の音声が必要です。',
          solution: 'より長い参照音声をアップロードします。',
          steps: ['5〜10秒の音声を録音またはクリップ', '音声に単一の話者のみが含まれていることを確認', '音声ファイルを再アップロード'],
          relatedCodes: ['AUDIO_TOO_LONG', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: '5〜10秒の参照音声を準備し、内容がクリアで完全であることを確認してください。',
        },
        {
          code: 'AUDIO_TOO_LONG',
          message: '「参照音声が長すぎる」または処理がタイムアウトする',
          severity: 'warning',
          category: 'C. ファイルと入力',
          location: 'ページ：IndexTTS 音声合成 → 領域：参照音声アップロードエリア',
          cause: '参照音声の長さが 10 秒を超えています。長すぎる参照音声は処理時間とバックエンド負荷を増加させ、クローニング品質の向上は限定的です。',
          solution: '音声を 3〜10 秒にクリップします。',
          steps: ['音声編集ツールを使用して音声の中央 5〜7 秒をクリップ', 'クリップ部分にクリアな音声が含まれていることを確認', 'WAV または MP3 として保存して再アップロード'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: '5〜10秒の参照音声を準備；長すぎる音声はクローニング品質の向上が限定的で、処理時間が増加します。',
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: 'エラーパネルに「モデルが利用できません」または 404 が表示される',
          severity: 'error',
          category: 'D. モデルと生成',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: '選択したモデルがバックエンドに存在しないか、削除されたか、現在の API Key がこのモデルにアクセスできません。',
          solution: '別の利用可能なモデルに切り替えます。',
          steps: ['「モデル」ドロップダウンから別のモデルを選択（例：index-tts-1.5）', 'モデル名のスペルが正しいか確認', '「設定 → API」で現在の Key が選択したモデルをサポートしているか確認', '再生成を試行'],
          relatedCodes: ['INDEX_TTS_NOT_CONFIGURED', 'API_KEY_EXPIRED'],
          prevention: '既知の利用可能なモデルをドロップダウンリストから選択；カスタム API を使用する場合はサービスプロバイダーのドキュメントでモデルリストを確認してください。',
        },
        {
          code: 'INDEX_TTS_TEXT_MISSING',
          message: '「音声を生成」をクリックするとすぐにエラーが表示され、テキストが入力されていないと表示される',
          severity: 'warning',
          category: 'C. ファイルと入力',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: 'テキスト入力欄が空です。IndexTTS は音声を生成するために有効なテキスト入力が必要です。',
          solution: 'テキスト入力欄に合成する内容を入力します。',
          steps: ['テキスト入力エリアをクリック', '合成するテキストを入力または貼り付け', 'テキストが空でないことを確認', '「音声を生成」をクリック'],
          relatedCodes: ['INDEX_TTS_TEXT_TOO_LONG', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: '生成前に必ずテキスト入力に有効な内容が含まれていることを確認してください。',
        },
        {
          code: 'INDEX_TTS_TEXT_TOO_LONG',
          message: '「テキストが長すぎる」または生成がタイムアウトする',
          severity: 'warning',
          category: 'C. ファイルと入力',
          location: 'ページ：IndexTTS 音声合成 → 領域：テキスト入力欄 / 左パネル下部エラーパネル',
          cause: '入力テキストが長すぎます（500文字を超え）、バックエンドモデルの最大処理制限を超えています。',
          solution: '入力テキストを短くします。',
          steps: ['長いテキストを複数のセグメントに分割し、各セグメントは200文字以内', '冗長な説明と重複した内容を削除', 'セグメントごとに生成して音声編集ツールで結合', '再試行'],
          relatedCodes: ['INDEX_TTS_TEXT_MISSING', 'API_TIMEOUT'],
          prevention: '1セグメントのテキストは500文字以内に収める；長い内容はセグメントごとに生成することを推奨します。',
        },
        {
          code: 'INDEX_TTS_TEXT_BLOCKED',
          message: 'リクエストがブロックされ、「コンテンツポリシー違反」または「sensitive words」と表示される',
          severity: 'error',
          category: 'D. モデルと生成',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: '入力テキストに、バックエンドサービスプロバイダーの安全フィルターがブロックする語句が含まれています。',
          solution: 'テキストを修正し、フィルターをトリガーする可能性のある語句を削除または置換します。',
          steps: ['エラーの詳細で具体的なヒントを確認し、ブロックされたキーワードを特定', '敏感な語句を同義語に置換または削除', 'まず単純なテキストでサービスが正常か確認', 'コンテンツを徐々に追加して、具体的にトリガーする語句を特定'],
          relatedCodes: ['403_FORBIDDEN'],
          prevention: 'テキストで敏感な語句を使用しない；まずデフォルトのテキストでテストしてからカスタマイズしてください。',
        },
        {
          code: 'INDEX_TTS_REQUEST_FAILED',
          message: 'エラーパネルに「INDEX_TTS_REQUEST_FAILED」が表示される',
          severity: 'error',
          category: 'D. モデルと生成',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: 'バックエンド API リクエストが失敗しました。ネットワーク切断、無効な API Key、モデルが利用できない、GPU メモリ不足、テキストが長すぎる、またはサーバー内部エラーの可能性があります。',
          solution: 'エラーの詳細にある具体的な情報に基づいてトラブルシューティングを行います。',
          steps: ['エラーパネルを展開して詳細なエラー情報を確認（HTTP ステータスコード、バックエンドメッセージ）', '401 の場合：API Key が有効か確認', '404 の場合：モデルが利用可能か確認', '429 の場合：しばらく待ってから再試行', '500/502/503 の場合：バックエンドサービス状態を確認', 'GPU エラーの場合：テキストの長さまたはサンプリングレートを下げる', 'ネットワークエラーの場合：ネットワーク接続を確認'],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: '生成前に API Key が有効で、ネットワークが接続され、モデルが利用可能であることを確認；初回生成は短いテキストでテストすることを推奨します。',
        },
        {
          code: 'INDEX_TTS_NOT_CONFIGURED',
          message: 'IndexTTS バックエンドが設定されていない',
          severity: 'error',
          category: 'E. 設定とデータ',
          location: 'サーバー → /api/index-tts',
          cause: 'バックエンドに IndexTTS プロバイダーが設定されていません。バックエンドルートは明示的な未設定エラーを返しました。',
          solution: 'バックエンドで IndexTTS プロバイダーを設定します。',
          steps: ['バックエンド .env ファイルに IndexTTS 関連の設定が含まれているか確認', 'IndexTTS API キーを設定（例：SiliconFlow）', 'プロバイダー設定をバックエンド .env に追加', 'バックエンドサーバーを再起動', 'フロントエンドに戻って再試行'],
          relatedCodes: ['INDEX_TTS_REQUEST_FAILED', 'BACKEND_UNAVAILABLE'],
          prevention: 'バックエンドをデプロイする際に IndexTTS プロバイダーを設定；使用前にバックエンドが正しく設定されていることを確認してください。',
        },
        {
          code: 'INDEX_TTS_GPU_OUT_OF_MEMORY',
          message: 'バックエンドから GPU メモリ不足エラーが返される',
          severity: 'error',
          category: 'F. システムと権限',
          location: 'サーバー → GPU 推論プロセス',
          cause: 'GPU VRAM がモデルの読み込みや現在のリクエストの処理に不十分です。長いテキスト、高サンプリングレート、大きなモデルはより多くの VRAM を消費します。',
          solution: 'テキストを短くするか、サンプリングレートを下げるか、CPU モードに切り替えるか、GPU をアップグレードします。',
          steps: ['入力テキストの長さを短くする', 'サンプリングレートを下げる（例：48000Hz → 22050Hz）', 'CPU 推論モードに切り替える', 'VRAM を消費する他のプログラムを閉じる', '問題が続く場合は、バックエンド管理者に連絡して GPU VRAM をアップグレード'],
          relatedCodes: ['500_INTERNAL_ERROR', 'API_TIMEOUT'],
          prevention: '長いテキストと高サンプリングレートはより多くの VRAM を消費します；テキストは200文字以内、22050Hz サンプリングレートを使用することを推奨します。',
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: 'リクエストが多すぎると表示される（Rate Limit）',
          severity: 'warning',
          category: 'A. API とネットワーク',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: '短時間に多すぎるリクエストを送信し、サービスプロバイダーのレート制限を超えました。',
          solution: 'しばらく待ってから再試行します。',
          steps: ['エラーの詳細で Retry-After ヒントがあれば確認', '60〜120秒待ってから再試行', '頻繁に発生する場合はテキストの長さを短くする', 'より高いレート制限を得るために API プランのアップグレードを検討'],
          relatedCodes: ['API_RATE_LIMIT', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: '適切にリクエスト頻度を下げる；短時間に複数回再試行しないでください。',
        },
        {
          code: '500_INTERNAL_ERROR',
          message: 'バックエンドから 500 内部サーバーエラーが返される',
          severity: 'error',
          category: '0~9. HTTP ステータスコード',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: 'バックエンドサービスがリクエストの処理中に内部例外を発生しました。モデルの読み込み失敗、GPU メモリ不足、またはコードのバグの可能性があります。',
          solution: '後で再試行するか、バックエンド管理者に連絡します。',
          steps: ['1〜2分待ってから再試行', 'テキストの長さを短くし、サンプリングレートを下げてバックエンド負荷を軽減', 'CPU 推論モードに切り替える', '問題が続く場合は、バックエンド管理者にサーバーログの確認を依頼'],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: 'リクエスト規模（テキストの長さ、サンプリングレートなど）を縮小；サーバー高負荷時に大きなタスクを送信しないでください。',
        },
        {
          code: '502_BAD_GATEWAY',
          message: 'バックエンドから 502 Bad Gateway が返される',
          severity: 'error',
          category: '0~9. HTTP ステータスコード',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: 'リバースプロキシ（例：Nginx）がバックエンドアプリケーションサーバーに接続できません。バックエンドプロセスがクラッシュしたか起動していない可能性があります。',
          solution: 'バックエンドサービスの状態を確認します。',
          steps: ['ローカルデプロイの場合は、バックエンドプロセスが実行中か確認', 'バックエンドサービスのポートが占有されていないか確認', 'バックエンドログで起動エラーがないか確認', 'バックエンドサービスを再起動して再試行'],
          relatedCodes: ['503_SERVICE_UNAVAILABLE', 'BACKEND_UNAVAILABLE'],
          prevention: 'ローカルデプロイの場合はバックエンドプロセスが実行中であることを確認；リバースプロキシ設定を確認してください。',
        },
        {
          code: '503_SERVICE_UNAVAILABLE',
          message: 'バックエンドから 503 Service Unavailable が返される',
          severity: 'error',
          category: '0~9. HTTP ステータスコード',
          location: 'ページ：IndexTTS 音声合成 → 領域：左パネル下部エラーパネル',
          cause: 'バックエンドサービスが一時的に利用できません。メンテナンス中、再起動中、または過負荷保護中の可能性があります。',
          solution: '後で再試行します。',
          steps: ['2〜3分待ってから再試行', 'バックエンドサービスのステータスページがあれば確認', 'バックエンド管理者にメンテナンス中か確認'],
          relatedCodes: ['502_BAD_GATEWAY', 'BACKEND_UNAVAILABLE'],
          prevention: 'サーバーのメンテナンス時間帯は避けて操作；高負荷時はリクエスト頻度を下げてください。',
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '設定のインポート時に「無効な JSON 形式」と表示される',
          severity: 'warning',
          category: 'B. 設定とデータ',
          location: 'ページ：IndexTTS 音声合成 → 領域：上部「設定をインポート」ボタン',
          cause: 'ファイルの内容が破損しているか、JSON 形式ではないか、または他のプログラムによって変更されています。',
          solution: 'ファイルが有効な UTF-8 エンコーディングのテキストファイルであるか確認します。',
          steps: ['テキストエディタでファイルを開いて文字化けがないか確認', 'ファイルの先頭に "tool": "index-tts" が含まれているか確認', 'オンライン JSON フォーマットツールで検証してみる'],
          relatedCodes: ['IMPORT_TOOL_MISMATCH'],
          prevention: 'エクスポートした設定ファイルを適切に保存；テキストエディタ以外で変更しないでください。',
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '設定のインポート時に「ツールタイプが一致しない」と表示される',
          severity: 'warning',
          category: 'B. 設定とデータ',
          location: 'ページ：IndexTTS 音声合成 → 領域：上部「設定をインポート」ボタン',
          cause: 'インポートした JSON ファイルの tool フィールドが index-tts ではありません。',
          solution: 'インポートするファイルが IndexTTS ページからエクスポートされたものであることを確認します。',
          steps: ['テキストエディタでファイルを開く', 'tool フィールドの値が "index-tts" であることを確認', 'そうでない場合は、正しい設定ファイルを探すか、対応するツールページからインポートする'],
          relatedCodes: ['IMPORT_INVALID_JSON'],
          prevention: '異なるツールの設定ファイルは互換性がありません；対応するツールページからエクスポートおよびインポートしてください。',
        },
      ],"""

RU_ERRORS_TEXT = """      errors: [
        {
          code: 'API_KEY_MISSING',
          message: 'Немедленная ошибка после нажатия «Синтезировать речь», панель ошибок показывает ошибку, связанную с API Key',
          severity: 'critical',
          category: 'A. API и сеть',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'API Key не настроен в «Настройки → API» или Key был очищен. Для генерации IndexTTS требуется действительный API Key.',
          solution: 'Настройте действительный API Key в панели настроек.',
          steps: ['Нажмите «Открыть настройки» в правом верхнем углу или используйте ярлык', 'Переключитесь на вкладку «API»', 'Введите действительный Key в поле «API Key»', 'Нажмите «Сохранить» и закройте панель настроек', 'Вернитесь на страницу IndexTTS и снова нажмите «Синтезировать речь»'],
          relatedCodes: ['API_KEY_EXPIRED', 'INDEX_TTS_NOT_CONFIGURED'],
          prevention: 'Перед первым использованием любого сетевого инструмента обязательно настройте действительный API Key в «Настройки → API».',
        },
        {
          code: 'API_KEY_EXPIRED',
          message: 'Запрос на генерацию возвращает 401 или указывает, что Key недействителен',
          severity: 'critical',
          category: 'A. API и сеть',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Настроенный API Key истёк, был отозван или исчерпана квота.',
          solution: 'Замените на действительный API Key.',
          steps: ['Откройте панель «Настройки → API»', 'Удалите текущий Key и введите новый действительный Key', 'Если не уверены в действительности Key, сначала протестируйте его в панели реального времени LLM Hub', 'Сохраните и вернитесь в IndexTTS для повторной попытки'],
          relatedCodes: ['API_KEY_MISSING', '401_UNAUTHORIZED'],
          prevention: 'Регулярно проверяйте срок действия и оставшуюся квоту API Key; используйте реальное тестирование в LLM Hub для быстрой проверки действительности Key.',
        },
        {
          code: 'API_TIMEOUT',
          message: 'Запрос долго не отвечает и в итоге истекает по таймауту',
          severity: 'error',
          category: 'A. API и сеть',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели / индикатор прогресса',
          cause: 'Генерация на бэкенде заняла слишком много времени, превысив таймаут фронтенда. Генерация TTS требовательна к GPU; длинный текст или высокая частота дискретизации занимают больше времени.',
          solution: 'Сократите длину текста, понизьте частоту дискретизации или проверьте сетевое соединение.',
          steps: ['Сократите входной текст (рекомендуется в пределах 200 символов)', 'Понизьте частоту дискретизации (например, с 48000Гц до 22050Гц)', 'Проверьте стабильность сетевого соединения', 'Если используется CPU-вывод, рассмотрите переключение на GPU-режим', 'Повторите генерацию'],
          relatedCodes: ['NETWORK_TIMEOUT', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: 'Длинный текст требует больше времени на генерацию; заранее сократите текст; увеличьте настройки таймаута при нестабильной сети.',
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: 'Сообщение «Бэкенд недоступен» или «Не удаётся подключиться к серверу»',
          severity: 'critical',
          category: 'A. API и сеть',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Бэкенд-сервер не запущен, упал или API Base URL, настроенный во фронтенде, неверен.',
          solution: 'Проверьте состояние бэкенд-сервиса и конфигурацию API.',
          steps: ['Откройте инструменты разработчика браузера → вкладку Network', 'Снова нажмите «Синтезировать речь», наблюдайте, отправляется ли запрос и каков код состояния ответа', 'Если запрос не отправлен, проверьте правильность «Настройки → API → API Base URL»', 'Если запрос возвращает 502/503, свяжитесь с администратором бэкенда для подтверждения состояния сервиса', 'При локальном развёртывании убедитесь, что бэкенд-процесс запущен (npm start)'],
          relatedCodes: ['NETWORK_DISCONNECTED', '502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
          prevention: 'При локальном развёртывании убедитесь, что бэкенд-процесс запущен (npm start); для удалённых сервисов подтвердите правильность настройки URL.',
        },
        {
          code: 'NETWORK_DISCONNECTED',
          message: 'Сообщение о разрыве сети или невозможности доступа в интернет',
          severity: 'critical',
          category: 'A. API и сеть',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Устройство не подключено к сети, Wi-Fi отключён или брандмауэр блокирует запросы.',
          solution: 'Восстановите сетевое соединение.',
          steps: ['Проверьте состояние сетевого подключения устройства', 'Попробуйте открыть другие сайты, чтобы подтвердить нормальность сети', 'Если используется прокси/VPN, проверьте правильность настроек прокси', 'В корпоративной/университетской сети убедитесь, что доступ к API не ограничен'],
          relatedCodes: ['BACKEND_UNAVAILABLE', 'API_TIMEOUT'],
          prevention: 'Перед использованием сетевых инструментов убедитесь в нормальности сетевого подключения; избегайте длительных операций в условиях сильных сетевых колебаний.',
        },
        {
          code: 'AUDIO_FORMAT_UNSUPPORTED',
          message: 'При загрузке сообщение «Неподдерживаемый формат аудио»',
          severity: 'warning',
          category: 'C. Файлы и ввод',
          location: 'Страница: IndexTTS Синтез речи → Область: Зона загрузки образца голоса',
          cause: 'Выбран неподдерживаемый формат (FLAC, OGG, AAC, WMA и т.д.). IndexTTS поддерживает только WAV и MP3.',
          solution: 'Преобразуйте аудио в формат WAV или MP3.',
          steps: ['Используйте инструмент конвертации аудио для преобразования файла в WAV или MP3', 'Или используйте встроенный аудиоредактор системы для экспорта в WAV/MP3', 'Убедитесь, что частота дискретизации 22050Гц и выше', 'Повторно загрузите преобразованный файл на странице IndexTTS'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_TOO_LONG'],
          prevention: 'Перед загрузкой убедитесь, что формат файла — WAV или MP3.',
        },
        {
          code: 'AUDIO_TOO_SHORT',
          message: 'Сообщение «Образец голоса слишком короткий»',
          severity: 'warning',
          category: 'C. Файлы и ввод',
          location: 'Страница: IndexTTS Синтез речи → Область: Зона загрузки образца голоса',
          cause: 'Длительность образца голоса менее 3 секунд. Для клонирования голоса zero-shot требуется минимум 3 секунды аудио для извлечения валидных характеристик голоса.',
          solution: 'Загрузите более длинный образец голоса.',
          steps: ['Запишите или обрежьте аудиосегмент длительностью 5~10 секунд', 'Убедитесь, что в аудио только один диктор', 'Повторно загрузите аудиофайл'],
          relatedCodes: ['AUDIO_TOO_LONG', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: 'Подготовьте образец голоса длительностью 5~10 секунд; убедитесь, что содержание чистое и полное.',
        },
        {
          code: 'AUDIO_TOO_LONG',
          message: 'Сообщение «Образец голоса слишком длинный» или таймаут обработки',
          severity: 'warning',
          category: 'C. Файлы и ввод',
          location: 'Страница: IndexTTS Синтез речи → Область: Зона загрузки образца голоса',
          cause: 'Длительность образца голоса превышает 10 секунд. Слишком длинный образец увеличивает время обработки и нагрузку на бэкенд, при этом улучшение качества клонирования ограничено.',
          solution: 'Обрежьте аудио до 3~10 секунд.',
          steps: ['Используйте аудиоредактор, чтобы обрезать центральные 5~7 секунд аудио', 'Убедитесь, что обрезанная часть содержит чистую речь', 'Сохраните как WAV или MP3 и повторно загрузите'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: 'Подготовьте образец голоса длительностью 5~10 секунд; слишком длинный аудио имеет ограниченное улучшение качества клонирования, но увеличивает время обработки.',
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: 'Панель ошибок показывает «Модель недоступна» или 404',
          severity: 'error',
          category: 'D. Модель и генерация',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Выбранная модель не существует на бэкенде, была удалена, или текущий API Key не имеет доступа к этой модели.',
          solution: 'Переключитесь на другую доступную модель.',
          steps: ['Выберите другую модель из выпадающего списка «Модель» (например, index-tts-1.5)', 'Убедитесь, что название модели написано правильно', 'В «Настройки → API» подтвердите, что текущий Key поддерживает выбранную модель', 'Повторите генерацию'],
          relatedCodes: ['INDEX_TTS_NOT_CONFIGURED', 'API_KEY_EXPIRED'],
          prevention: 'Выбирайте известные доступные модели из выпадающего списка; при использовании пользовательского API сверьтесь с документацией провайдера.',
        },
        {
          code: 'INDEX_TTS_TEXT_MISSING',
          message: 'Немедленная ошибка после нажатия «Синтезировать речь», сообщение о незаполненном тексте',
          severity: 'warning',
          category: 'C. Файлы и ввод',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Текстовое поле пустое. Для генерации речи IndexTTS требуется валидный текст.',
          solution: 'Введите содержание для синтеза в текстовое поле.',
          steps: ['Нажмите на текстовую область', 'Введите или вставьте текст для синтеза', 'Убедитесь, что текст не пустой', 'Нажмите «Синтезировать речь»'],
          relatedCodes: ['INDEX_TTS_TEXT_TOO_LONG', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: 'Всегда проверяйте, что текстовое поле содержит валидное содержимое, перед генерацией.',
        },
        {
          code: 'INDEX_TTS_TEXT_TOO_LONG',
          message: 'Сообщение «Текст слишком длинный» или таймаут генерации',
          severity: 'warning',
          category: 'C. Файлы и ввод',
          location: 'Страница: IndexTTS Синтез речи → Область: Текстовое поле / Нижняя панель ошибок левой панели',
          cause: 'Входной текст слишком длинный (более 500 символов), превышая максимальный лимит обработки бэкенд-модели.',
          solution: 'Сократите входной текст.',
          steps: ['Разбейте длинный текст на несколько сегментов, каждый не более 200 символов', 'Удалите избыточные описания и повторяющееся содержимое', 'Генерируйте по сегментам и объединяйте с помощью аудиоредактора', 'Повторите попытку'],
          relatedCodes: ['INDEX_TTS_TEXT_MISSING', 'API_TIMEOUT'],
          prevention: 'Один сегмент текста — не более 500 символов; длинное содержимое рекомендуется генерировать по сегментам.',
        },
        {
          code: 'INDEX_TTS_TEXT_BLOCKED',
          message: 'Запрос заблокирован, сообщение «Нарушение политики контента» или «sensitive words»',
          severity: 'error',
          category: 'D. Модель и генерация',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Входной текст содержит слова, заблокированные фильтром безопасности бэкенд-провайдера.',
          solution: 'Измените текст, удалите или замените слова, которые могут сработать на фильтр.',
          steps: ['Проверьте детали ошибки на конкретные подсказки для выявления заблокированных ключевых слов', 'Замените чувствительные слова синонимами или удалите их', 'Сначала протестируйте с простым текстом, чтобы убедиться, что сервис работает', 'Постепенно добавляйте содержимое, чтобы выявить конкретное триггер-слово'],
          relatedCodes: ['403_FORBIDDEN'],
          prevention: 'Избегайте использования чувствительных слов в тексте; сначала протестируйте с текстом по умолчанию, прежде чем настраивать.',
        },
        {
          code: 'INDEX_TTS_REQUEST_FAILED',
          message: 'Панель ошибок показывает INDEX_TTS_REQUEST_FAILED',
          severity: 'error',
          category: 'D. Модель и генерация',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Запрос к бэкенд API не удался. Возможные причины: разрыв сети, неверный API Key, модель недоступна, нехватка GPU VRAM, текст слишком длинный или внутренняя ошибка сервера.',
          solution: 'Устраните неполадки на основе конкретной информации в деталях ошибки.',
          steps: ['Разверните панель ошибок для просмотра детальной информации (HTTP код состояния, сообщение бэкенда)', 'Если 401: проверьте действительность API Key', 'Если 404: проверьте доступность модели', 'Если 429: подождите и повторите попытку позже', 'Если 500/502/503: проверьте состояние бэкенд-сервиса', 'Если ошибка GPU: сократите длину текста или частоту дискретизации', 'Если сетевая ошибка: проверьте сетевое подключение'],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: 'Перед генерацией убедитесь, что API Key действителен, сеть подключена и модель доступна; первую генерацию рекомендуется выполнять с коротким текстом.',
        },
        {
          code: 'INDEX_TTS_NOT_CONFIGURED',
          message: 'Бэкенд IndexTTS не настроен',
          severity: 'error',
          category: 'E. Конфигурация и данные',
          location: 'Сервер → /api/index-tts',
          cause: 'На бэкенде не настроен провайдер IndexTTS. Маршрут бэкенда вернул явную ошибку о неправильной конфигурации.',
          solution: 'Настройте провайдера IndexTTS на бэкенде.',
          steps: ['Проверьте, содержит ли файл .env бэкенда конфигурацию, связанную с IndexTTS', 'Настройте ключ API IndexTTS (например, SiliconFlow)', 'Добавьте конфигурацию провайдера в .env бэкенда', 'Перезапустите бэкенд-сервер', 'Вернитесь во фронтенд и повторите попытку'],
          relatedCodes: ['INDEX_TTS_REQUEST_FAILED', 'BACKEND_UNAVAILABLE'],
          prevention: 'Настройте провайдера IndexTTS при развёртывании бэкенда; убедитесь, что бэкенд правильно настроен перед использованием.',
        },
        {
          code: 'INDEX_TTS_GPU_OUT_OF_MEMORY',
          message: 'Бэкенд возвращает ошибку нехватки GPU VRAM',
          severity: 'error',
          category: 'F. Система и права доступа',
          location: 'Сервер → GPU-процесс вывода',
          cause: 'GPU VRAM недостаточно для загрузки модели или обработки текущего запроса. Длинный текст, высокая частота дискретизации и большие модели потребляют больше VRAM.',
          solution: 'Сократите текст, понизьте частоту дискретизации, переключитесь в CPU-режим или обновите GPU.',
          steps: ['Сократите длину входного текста', 'Понизьте частоту дискретизации (например, 48000Гц → 22050Гц)', 'Переключитесь в режим CPU-вывода', 'Закройте другие программы, потребляющие VRAM', 'Если проблема сохраняется, свяжитесь с администратором бэкенда для обновления GPU VRAM'],
          relatedCodes: ['500_INTERNAL_ERROR', 'API_TIMEOUT'],
          prevention: 'Длинный текст и высокая частота дискретизации потребляют больше VRAM; рекомендуется текст в пределах 200 символов и частота дискретизации 22050Гц.',
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: 'Сообщение «Слишком много запросов» (Rate Limit)',
          severity: 'warning',
          category: 'A. API и сеть',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Отправлено слишком много запросов за короткое время, превышен лимит скорости провайдера.',
          solution: 'Подождите и повторите попытку позже.',
          steps: ['Проверьте детали ошибки на подсказку Retry-After, если доступна', 'Подождите 60~120 секунд и повторите попытку', 'Если проблема возникает часто, сократите длину текста', 'Рассмотрите обновление тарифа API для получения более высокого лимита скорости'],
          relatedCodes: ['API_RATE_LIMIT', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: 'Соответствующим образом снижайте частоту запросов; избегайте многократных повторных попыток за короткое время.',
        },
        {
          code: '500_INTERNAL_ERROR',
          message: 'Бэкенд возвращает 500 Internal Server Error',
          severity: 'error',
          category: '0~9. HTTP-коды состояния',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Бэкенд-сервис столкнулся с внутренним исключением при обработке запроса. Возможные причины: сбой загрузки модели, нехватка GPU-памяти или ошибка в коде.',
          solution: 'Повторите попытку позже или свяжитесь с администратором бэкенда.',
          steps: ['Подождите 1~2 минуты и повторите попытку', 'Сократите длину текста, понизьте частоту дискретизации, чтобы уменьшить нагрузку на бэкенд', 'Переключитесь в режим CPU-вывода', 'Если проблема сохраняется, свяжитесь с администратором бэкенда для проверки журналов сервера'],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: 'Сокращайте масштаб запросов (длина текста, частота дискретизации и т.д.); избегайте отправки больших задач при высокой нагрузке на сервер.',
        },
        {
          code: '502_BAD_GATEWAY',
          message: 'Бэкенд возвращает 502 Bad Gateway',
          severity: 'error',
          category: '0~9. HTTP-коды состояния',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Обратный прокси (например, Nginx) не может подключиться к бэкенд-серверу приложений. Бэкенд-процесс мог упасть или не быть запущен.',
          solution: 'Проверьте состояние бэкенд-сервиса.',
          steps: ['При локальном развёртывании убедитесь, что бэкенд-процесс запущен', 'Проверьте, не занят ли порт бэкенд-сервиса', 'Проверьте журналы бэкенда на наличие ошибок запуска', 'Перезапустите бэкенд-сервис и повторите попытку'],
          relatedCodes: ['503_SERVICE_UNAVAILABLE', 'BACKEND_UNAVAILABLE'],
          prevention: 'При локальном развёртывании убедитесь, что бэкенд-процесс запущен; проверьте конфигурацию обратного прокси.',
        },
        {
          code: '503_SERVICE_UNAVAILABLE',
          message: 'Бэкенд возвращает 503 Service Unavailable',
          severity: 'error',
          category: '0~9. HTTP-коды состояния',
          location: 'Страница: IndexTTS Синтез речи → Область: Нижняя панель ошибок левой панели',
          cause: 'Бэкенд-сервис временно недоступен, возможно, проводится техническое обслуживание, перезагрузка или защита от перегрузки.',
          solution: 'Повторите попытку позже.',
          steps: ['Подождите 2~3 минуты и повторите попытку', 'Проверьте страницу состояния бэкенд-сервиса, если доступна', 'Свяжитесь с администратором бэкенда, чтобы уточнить, идёт ли техническое обслуживание'],
          relatedCodes: ['502_BAD_GATEWAY', 'BACKEND_UNAVAILABLE'],
          prevention: 'Избегайте работы во время технического обслуживания сервера; снижайте частоту запросов при высокой нагрузке.',
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: 'При импорте конфигурации сообщение «Недопустимый формат JSON»',
          severity: 'warning',
          category: 'B. Конфигурация и данные',
          location: 'Страница: IndexTTS Синтез речи → Область: Кнопка «Импортировать конфигурацию» вверху',
          cause: 'Содержимое файла повреждено, не в формате JSON или было изменено другой программой.',
          solution: 'Проверьте, является ли файл допустимым текстовым файлом в кодировке UTF-8.',
          steps: ['Откройте файл в текстовом редакторе, чтобы проверить наличие искажённых символов', 'Убедитесь, что в начале файла содержится "tool": "index-tts"', 'Попробуйте проверить с помощью онлайн-инструмента форматирования JSON'],
          relatedCodes: ['IMPORT_TOOL_MISMATCH'],
          prevention: 'Правильно сохраняйте экспортированные файлы конфигурации; избегайте изменений в нетекстовых редакторах.',
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: 'При импорте конфигурации сообщение «Несоответствие типа инструмента»',
          severity: 'warning',
          category: 'B. Конфигурация и данные',
          location: 'Страница: IndexTTS Синтез речи → Область: Кнопка «Импортировать конфигурацию» вверху',
          cause: 'Поле tool в импортированном JSON-файле не равно index-tts.',
          solution: 'Убедитесь, что импортируемый файл экспортирован со страницы IndexTTS.',
          steps: ['Откройте файл в текстовом редакторе', 'Убедитесь, что значение поля tool равно "index-tts"', 'Если нет, найдите правильный файл конфигурации или импортируйте со страницы соответствующего инструмента'],
          relatedCodes: ['IMPORT_INVALID_JSON'],
          prevention: 'Файлы конфигурации разных инструментов не взаимозаменяемы; экспортируйте и импортируйте со страницы соответствующего инструмента.',
        },
      ],"""

KO_ERRORS_TEXT = """      errors: [
        {
          code: 'API_KEY_MISSING',
          message: '「음성 생성」을 클릭하면 즉시 오류가 표시되고 오류 패널에 API Key 관련 오류가 표시됨',
          severity: 'critical',
          category: 'A. API 및 네트워크',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '「설정 → API」에서 API Key가 설정되지 않았거나 Key가 비어 있습니다. IndexTTS 생성에는 유효한 API Key가 필요합니다.',
          solution: '설정 패널에서 유효한 API Key를 설정합니다.',
          steps: ['오른쪽 상단의 「설정 열기」를 클릭하거나 단축키를 사용', '「API」탭으로 전환', '「API Key」입력란에 유효한 Key 입력', '「저장」을 클릭하고 설정 패널 닫기', 'IndexTTS 페이지로 돌아가서 「음성 생성」을 다시 클릭'],
          relatedCodes: ['API_KEY_EXPIRED', 'INDEX_TTS_NOT_CONFIGURED'],
          prevention: '처음으로 네트워크 도구를 사용하기 전에 반드시 「설정 → API」에서 유효한 API Key를 설정하세요.',
        },
        {
          code: 'API_KEY_EXPIRED',
          message: '생성 요청이 401을 반환하거나 Key가 무효하다고 표시됨',
          severity: 'critical',
          category: 'A. API 및 네트워크',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '설정된 API Key의 유효 기간이 만료되었거나, 취소되었거나, 할당량이 소진되었습니다.',
          solution: '유효한 API Key로 교체합니다.',
          steps: ['「설정 → API」패널 열기', '현재 Key를 삭제하고 새로운 유효한 Key 입력', 'Key가 유효한지 확실하지 않은 경우 LLM Hub의 실시간 테스트 패널에서 먼저 테스트', '저장하고 IndexTTS로 돌아가서 재시도'],
          relatedCodes: ['API_KEY_MISSING', '401_UNAUTHORIZED'],
          prevention: 'API Key의 유효 기간과 남은 할당량을 정기적으로 확인; LLM Hub의 실시간 테스트를 통해 Key의 유효성을 신속하게 확인하세요.',
        },
        {
          code: 'API_TIMEOUT',
          message: '요청이 오랫동안 응답하지 않고 최종적으로 타임아웃됨',
          severity: 'error',
          category: 'A. API 및 네트워크',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널 / 진행률 표시줄',
          cause: '백엔드 생성에 너무 오랜 시간이 소요되어 프론트엔드 타임아웃을 초과했습니다. TTS 생성은 GPU 성능을 요구하며, 긴 텍스트나 높은 샘플링 레이트일 때 더 오래 걸립니다.',
          solution: '텍스트 길이를 줄이거나, 샘플링 레이트를 낮추거나, 네트워크 연결을 확인합니다.',
          steps: ['입력 텍스트를 줄입니다(200자 이내 권장)', '샘플링 레이트를 낮춥니다(예: 48000Hz → 22050Hz)', '네트워크 연결이 안정적인지 확인', 'CPU 추론을 사용하는 경우 GPU 모드로 전환 고려', '재생성 시도'],
          relatedCodes: ['NETWORK_TIMEOUT', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: '긴 텍스트는 생성에 더 오랜 시간이 걸립니다; 사전에 텍스트를 줄이세요; 네트워크가 불안정한 경우 타임아웃 설정을 늘리세요.',
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: '「백엔드를 사용할 수 없음」또는 「서버에 연결할 수 없음」표시됨',
          severity: 'critical',
          category: 'A. API 및 네트워크',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '백엔드 서버가 시작되지 않았거나, 충돌했거나, 프론트엔드에 구성된 API Base URL이 올바르지 않습니다.',
          solution: '백엔드 서비스 상태와 API 구성을 확인합니다.',
          steps: ['브라우저 개발자 도구 → Network 탭 열기', '「음성 생성」을 다시 클릭하고 요청이 전송되었는지 및 응답 상태 코드 확인', '요청이 전송되지 않은 경우 「설정 → API → API Base URL」이 올바른지 확인', '요청이 502/503을 반환하는 경우 백엔드 관리자에게 서비스 상태 확인', '로컬 배포의 경우 백엔드 프로세스가 실행 중인지 확인(npm start)'],
          relatedCodes: ['NETWORK_DISCONNECTED', '502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
          prevention: '로컬 배포 시 백엔드 프로세스가 시작되었는지 확인(npm start); 원격 서비스의 경우 URL 구성이 올바른지 확인하세요.',
        },
        {
          code: 'NETWORK_DISCONNECTED',
          message: '네트워크가 연결되지 않았거나 인터넷에 액세스할 수 없음',
          severity: 'critical',
          category: 'A. API 및 네트워크',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '장치가 네트워크에 연결되지 않았거나, Wi-Fi가 연결 해제되었거나, 방화벽이 요청을 차단하고 있습니다.',
          solution: '네트워크 연결을 복원합니다.',
          steps: ['장치의 네트워크 연결 상태 확인', '다른 웹사이트에 액세스하여 네트워크가 정상인지 확인', '프록시/VPN을 사용하는 경우 프록시 설정이 올바른지 확인', '회사/학교 네트워크의 경우 API 액세스가 제한되지 않았는지 확인'],
          relatedCodes: ['BACKEND_UNAVAILABLE', 'API_TIMEOUT'],
          prevention: '네트워크 도구를 사용하기 전에 네트워크 연결이 정상임을 확인; 네트워크 변동이 큰 환경에서 장시간 작업을 피하세요.',
        },
        {
          code: 'AUDIO_FORMAT_UNSUPPORTED',
          message: '업로드 시「지원되지 않는 오디오 형식」표시됨',
          severity: 'warning',
          category: 'C. 파일 및 입력',
          location: '페이지: IndexTTS 음성 합성 → 영역: 참조 오디오 업로드 영역',
          cause: 'FLAC, OGG, AAC, WMA 등 지원되지 않는 형식을 선택했습니다. IndexTTS는 WAV 및 MP3 형식의 참조 오디오만 지원합니다.',
          solution: '오디오를 WAV 또는 MP3 형식으로 변환합니다.',
          steps: ['오디오 변환 도구를 사용하여 파일을 WAV 또는 MP3로 변환', '또는 시스템 내장 오디오 편집 도구로 WAV/MP3로 내보내기', '샘플링 레이트가 22050Hz 이상인지 확인', 'IndexTTS 페이지에서 변환된 파일을 다시 업로드'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_TOO_LONG'],
          prevention: '업로드 전에 파일 형식이 WAV 또는 MP3인지 확인하세요.',
        },
        {
          code: 'AUDIO_TOO_SHORT',
          message: '「참조 오디오가 너무 짧음」표시됨',
          severity: 'warning',
          category: 'C. 파일 및 입력',
          location: '페이지: IndexTTS 음성 합성 → 영역: 참조 오디오 업로드 영역',
          cause: '참조 오디오 길이가 3초 미만입니다. 제로샷 음성 클로닝에는 유효한 음색 특성을 추출하기 위해 최소 3초의 오디오가 필요합니다.',
          solution: '더 긴 참조 오디오를 업로드합니다.',
          steps: ['5~10초의 오디오를 녹음하거나 클립', '오디오에 단일 화자만 포함되어 있는지 확인', '오디오 파일을 다시 업로드'],
          relatedCodes: ['AUDIO_TOO_LONG', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: '5~10초의 참조 오디오를 준비하고 내용이 선명하고 완전한지 확인하세요.',
        },
        {
          code: 'AUDIO_TOO_LONG',
          message: '「참조 오디오가 너무 김」또는 처리가 타임아웃됨',
          severity: 'warning',
          category: 'C. 파일 및 입력',
          location: '페이지: IndexTTS 음성 합성 → 영역: 참조 오디오 업로드 영역',
          cause: '참조 오디오 길이가 10초를 초과합니다. 너무 긴 참조 오디오는 처리 시간과 백엔드 부하를 증가시키며, 클로닝 품질 향상은 제한적입니다.',
          solution: '오디오를 3~10초로 클립합니다.',
          steps: ['오디오 편집 도구를 사용하여 오디오 중간 5~7초를 클립', '클립 부분에 선명한 음성이 포함되어 있는지 확인', 'WAV 또는 MP3로 저장하여 다시 업로드'],
          relatedCodes: ['AUDIO_TOO_SHORT', 'AUDIO_FORMAT_UNSUPPORTED'],
          prevention: '5~10초의 참조 오디오를 준비; 너무 긴 오디오는 클로닝 품질 향상이 제한적이며 처리 시간이 증가합니다.',
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: '오류 패널에「모델을 사용할 수 없음」또는 404가 표시됨',
          severity: 'error',
          category: 'D. 모델 및 생성',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '선택한 모델이 백엔드에 존재하지 않거나, 제거되었거나, 현재 API Key가 이 모델에 액세스할 수 없습니다.',
          solution: '다른 사용 가능한 모델로 전환합니다.',
          steps: ['「모델」드롭다운에서 다른 모델 선택(예: index-tts-1.5)', '모델 이름 철자가 올바른지 확인', '「설정 → API」에서 현재 Key가 선택한 모델을 지원하는지 확인', '재생성 시도'],
          relatedCodes: ['INDEX_TTS_NOT_CONFIGURED', 'API_KEY_EXPIRED'],
          prevention: '드롭다운 목록에서 알려진 사용 가능한 모델을 선택; 사용자 지정 API를 사용하는 경우 서비스 제공업체 문서에서 모델 목록을 확인하세요.',
        },
        {
          code: 'INDEX_TTS_TEXT_MISSING',
          message: '「음성 생성」을 클릭하면 즉시 오류가 표시되고 텍스트가 입력되지 않았다고 표시됨',
          severity: 'warning',
          category: 'C. 파일 및 입력',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '텍스트 입력란이 비어 있습니다. IndexTTS는 음성을 생성하기 위해 유효한 텍스트 입력이 필요합니다.',
          solution: '텍스트 입력란에 합성할 내용을 입력합니다.',
          steps: ['텍스트 입력 영역을 클릭', '합성할 텍스트를 입력하거나 붙여넣기', '텍스트가 비어 있지 않은지 확인', '「음성 생성」을 클릭'],
          relatedCodes: ['INDEX_TTS_TEXT_TOO_LONG', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: '생성 전에 항상 텍스트 입력에 유효한 내용이 포함되어 있는지 확인하세요.',
        },
        {
          code: 'INDEX_TTS_TEXT_TOO_LONG',
          message: '「텍스트가 너무 김」또는 생성이 타임아웃됨',
          severity: 'warning',
          category: 'C. 파일 및 입력',
          location: '페이지: IndexTTS 음성 합성 → 영역: 텍스트 입력란 / 왼쪽 패널 하단 오류 패널',
          cause: '입력 텍스트가 너무 깁니다(500자를 초과). 백엔드 모델의 최대 처리 제한을 초과했습니다.',
          solution: '입력 텍스트를 줄입니다.',
          steps: ['긴 텍스트를 여러 세그먼트로 분할하고, 각 세그먼트는 200자 이내', '불필요한 설명과 중복된 내용 삭제', '세그먼트별로 생성하여 오디오 편집 도구로 병합', '재시도'],
          relatedCodes: ['INDEX_TTS_TEXT_MISSING', 'API_TIMEOUT'],
          prevention: '단일 세그먼트 텍스트는 500자 이내로 제한; 긴 내용은 세그먼트별로 생성하는 것을 권장합니다.',
        },
        {
          code: 'INDEX_TTS_TEXT_BLOCKED',
          message: '요청이 차단되고「콘텐츠 정책 위반」또는「sensitive words」가 표시됨',
          severity: 'error',
          category: 'D. 모델 및 생성',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '입력 텍스트에 백엔드 서비스 제공업체의 안전 필터가 차단하는 단어가 포함되어 있습니다.',
          solution: '텍스트를 수정하고, 필터를 트리거할 수 있는 단어를 제거하거나 대체합니다.',
          steps: ['오류 세부 정보에서 구체적인 힌트를 확인하고 차단된 키워드를 식별', '민감한 단어를 동의어로 대체하거나 삭제', '먼저 간단한 테스트 텍스트로 서비스가 정상인지 확인', '콘텐츠를 점진적으로 추가하여 구체적으로 트리거하는 단어를 식별'],
          relatedCodes: ['403_FORBIDDEN'],
          prevention: '텍스트에서 민감한 단어를 사용하지 마세요; 먼저 기본 텍스트로 테스트를 통과한 후 사용자 지정하세요.',
        },
        {
          code: 'INDEX_TTS_REQUEST_FAILED',
          message: '오류 패널에「INDEX_TTS_REQUEST_FAILED」가 표시됨',
          severity: 'error',
          category: 'D. 모델 및 생성',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '백엔드 API 요청이 실패했습니다. 네트워크 중단, 잘못된 API Key, 모델을 사용할 수 없음, GPU 메모리 부족, 텍스트가 너무 김, 또는 서버 내부 오류일 수 있습니다.',
          solution: '오류 세부 정보의 구체적인 정보를 기반으로 문제를 해결합니다.',
          steps: ['오류 패널을 펼쳐 자세한 오류 정보 확인(HTTP 상태 코드, 백엔드 메시지)', '401인 경우: API Key가 유효한지 확인', '404인 경우: 모델을 사용할 수 있는지 확인', '429인 경우: 잠시 기다렸다가 다시 시도', '500/502/503인 경우: 백엔드 서비스 상태 확인', 'GPU 오류인 경우: 텍스트 길이 또는 샘플링 레이트 낮추기', '네트워크 오류인 경우: 네트워크 연결 확인'],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'BACKEND_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: '생성 전에 API Key가 유효하고, 네트워크가 연결되어 있으며, 모델을 사용할 수 있는지 확인; 처음 생성은 짧은 텍스트로 테스트하는 것을 권장합니다.',
        },
        {
          code: 'INDEX_TTS_NOT_CONFIGURED',
          message: 'IndexTTS 백엔드가 구성되지 않음',
          severity: 'error',
          category: 'E. 구성 및 데이터',
          location: '서버 → /api/index-tts',
          cause: '백엔드에 IndexTTS 제공업체가 구성되어 있지 않습니다. 백엔드 경로는 명시적인 미구성 오류를 반환했습니다.',
          solution: '백엔드에서 IndexTTS 제공업체를 구성합니다.',
          steps: ['백엔드 .env 파일에 IndexTTS 관련 구성이 포함되어 있는지 확인', 'IndexTTS API 키 구성(예: SiliconFlow)', '제공업체 구성을 백엔드 .env에 추가', '백엔드 서버 재시작', '프론트엔드로 돌아가서 재시도'],
          relatedCodes: ['INDEX_TTS_REQUEST_FAILED', 'BACKEND_UNAVAILABLE'],
          prevention: '백엔드를 배포할 때 IndexTTS 제공업체를 구성; 사용 전에 백엔드가 올바르게 구성되었는지 확인하세요.',
        },
        {
          code: 'INDEX_TTS_GPU_OUT_OF_MEMORY',
          message: '백엔드에서 GPU 메모리 부족 오류가 반환됨',
          severity: 'error',
          category: 'F. 시스템 및 권한',
          location: '서버 → GPU 추론 프로세스',
          cause: 'GPU VRAM이 모델을 로드하거나 현재 요청을 처리하기에 부족합니다. 긴 텍스트, 높은 샘플링 레이트, 큰 모델은 더 많은 VRAM을 소비합니다.',
          solution: '텍스트를 줄이거나, 샘플링 레이트를 낮추거나, CPU 모드로 전환하거나, GPU를 업그레이드합니다.',
          steps: ['입력 텍스트 길이를 줄입니다', '샘플링 레이트를 낮춥니다(예: 48000Hz → 22050Hz)', 'CPU 추론 모드로 전환', 'VRAM을 소비하는 다른 프로그램을 닫습니다', '문제가 지속되면 백엔드 관리자에게 연락하여 GPU VRAM 업그레이드'],
          relatedCodes: ['500_INTERNAL_ERROR', 'API_TIMEOUT'],
          prevention: '긴 텍스트와 높은 샘플링 레이트는 더 많은 VRAM을 소비합니다; 텍스트는 200자 이내, 22050Hz 샘플링 레이트를 사용하는 것을 권장합니다.',
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: '「요청이 너무 많음」(Rate Limit)이 표시됨',
          severity: 'warning',
          category: 'A. API 및 네트워크',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '짧은 시간에 너무 많은 요청을 보내 서비스 제공업체의 속도 제한을 초과했습니다.',
          solution: '잠시 기다렸다가 다시 시도합니다.',
          steps: ['오류 세부 정보에서 Retry-After 힌트가 있으면 확인', '60~120초 기다린 후 재시도', '자주 발생하는 경우 텍스트 길이를 줄입니다', '더 높은 속도 제한을 얻기 위해 API 플랜 업그레이드 고려'],
          relatedCodes: ['API_RATE_LIMIT', 'INDEX_TTS_REQUEST_FAILED'],
          prevention: '적절히 요청 빈도를 낮추세요; 짧은 시간에 여러 번 재시도하지 마세요.',
        },
        {
          code: '500_INTERNAL_ERROR',
          message: '백엔드에서 500 내부 서버 오류가 반환됨',
          severity: 'error',
          category: '0~9. HTTP 상태 코드',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '백엔드 서비스가 요청을 처리하는 동안 내부 예외가 발생했습니다. 모델 로드 실패, GPU 메모리 부족, 또는 코드 버그일 수 있습니다.',
          solution: '나중에 다시 시도하거나 백엔드 관리자에게 문의합니다.',
          steps: ['1~2분 기다린 후 재시도', '텍스트 길이를 줄이고 샘플링 레이트를 낮춰 백엔드 부하를 줄입니다', 'CPU 추론 모드로 전환', '문제가 지속되면 백엔드 관리자에게 서버 로그 확인을 요청'],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE', 'INDEX_TTS_GPU_OUT_OF_MEMORY'],
          prevention: '요청 규모(텍스트 길이, 샘플링 레이트 등)를 줄이세요; 서버가 높은 부하 상태일 때 큰 작업을 제출하지 마세요.',
        },
        {
          code: '502_BAD_GATEWAY',
          message: '백엔드에서 502 Bad Gateway가 반환됨',
          severity: 'error',
          category: '0~9. HTTP 상태 코드',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '리버스 프록시(예: Nginx)가 백엔드 애플리케이션 서버에 연결할 수 없습니다. 백엔드 프로세스가 충돌했거나 시작되지 않았을 수 있습니다.',
          solution: '백엔드 서비스 상태를 확인합니다.',
          steps: ['로컬 배포의 경우 백엔드 프로세스가 실행 중인지 확인', '백엔드 서비스 포트가 점유되지 않았는지 확인', '백엔드 로그에서 시작 오류가 없는지 확인', '백엔드 서비스를 재시작하고 재시도'],
          relatedCodes: ['503_SERVICE_UNAVAILABLE', 'BACKEND_UNAVAILABLE'],
          prevention: '로컬 배포 시 백엔드 프로세스가 실행 중인지 확인; 리버스 프록시 구성을 확인하세요.',
        },
        {
          code: '503_SERVICE_UNAVAILABLE',
          message: '백엔드에서 503 Service Unavailable이 반환됨',
          severity: 'error',
          category: '0~9. HTTP 상태 코드',
          location: '페이지: IndexTTS 음성 합성 → 영역: 왼쪽 패널 하단 오류 패널',
          cause: '백엔드 서비스가 일시적으로 사용할 수 없습니다. 유지 관리 중, 재시작 중, 또는 과부하 보호 중일 수 있습니다.',
          solution: '나중에 다시 시도합니다.',
          steps: ['2~3분 기다린 후 재시도', '백엔드 서비스 상태 페이지가 있으면 확인', '백엔드 관리자에게 유지 관리 중인지 확인'],
          relatedCodes: ['502_BAD_GATEWAY', 'BACKEND_UNAVAILABLE'],
          prevention: '서버 유지 관리 시간대를 피해 작업하세요; 높은 부하 시 요청 빈도를 낮추세요.',
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '구성을 가져올 때「잘못된 JSON 형식」이 표시됨',
          severity: 'warning',
          category: 'B. 구성 및 데이터',
          location: '페이지: IndexTTS 음성 합성 → 영역: 상단「구성 가져오기」버튼',
          cause: '파일 내용이 손상되었거나, JSON 형식이 아니거나, 다른 프로그램에서 수정되었습니다.',
          solution: '파일이 유효한 UTF-8 인코딩 텍스트 파일인지 확인합니다.',
          steps: ['텍스트 편집기에서 파일을 열어 깨진 문자가 없는지 확인', '파일 상단에 "tool": "index-tts"가 포함되어 있는지 확인', '온라인 JSON 형식 도구로 검증해 보세요'],
          relatedCodes: ['IMPORT_TOOL_MISMATCH'],
          prevention: '내보낸 구성 파일을 적절히 저장하세요; 텍스트 편집기 이외의 도구로 수정하지 마세요.',
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '구성을 가져올 때「도구 유형이 일치하지 않음」이 표시됨',
          severity: 'warning',
          category: 'B. 구성 및 데이터',
          location: '페이지: IndexTTS 음성 합성 → 영역: 상단「구성 가져오기」버튼',
          cause: '가져온 JSON 파일의 tool 필드가 index-tts가 아닙니다.',
          solution: '가져온 파일이 IndexTTS 페이지에서 내보낸 것인지 확인합니다.',
          steps: ['텍스트 편집기에서 파일 열기', 'tool 필드 값이 "index-tts"인지 확인', '그렇지 않은 경우 올바른 구성 파일을 찾거나 해당 도구 페이지에서 가져오기'],
          relatedCodes: ['IMPORT_INVALID_JSON'],
          prevention: '다른 도구의 구성 파일은 호환되지 않습니다; 해당 도구 페이지에서 내보내기 및 가져오기를 수행하세요.',
        },
      ],"""


def find_errors_bounds(text, section_id):
    """Find start and end of errors array within a tool section."""
    pattern = rf"id: '{section_id}'"
    start = text.find(pattern)
    if start == -1:
        return None, None
    # Find errors: [ after start
    err_start = text.find('errors: [', start)
    if err_start == -1:
        return None, None
    # Find matching ]
    bracket_depth = 0
    in_string = False
    string_char = None
    i = err_start + len('errors: [')
    while i < len(text):
        c = text[i]
        if in_string:
            if c == '\\' and i + 1 < len(text):
                i += 2
                continue
            if c == string_char:
                in_string = False
                string_char = None
        elif c in "'\"":
            in_string = True
            string_char = c
        elif c == '[':
            bracket_depth += 1
        elif c == ']':
            if bracket_depth == 0:
                break
            bracket_depth -= 1
        i += 1
    err_end = i + 1  # Include ]
    return err_start, err_end


def replace_errors(content, section_id, new_errors_text):
    err_start, err_end = find_errors_bounds(content, section_id)
    if err_start is None:
        print(f"  WARNING: could not find errors for {section_id}")
        return content
    return content[:err_start] + new_errors_text + content[err_end:]


LANG_ERRORS = {
    'zh': ZH_ERRORS_TEXT,
    'en': EN_ERRORS_TEXT,
    'ja': JA_ERRORS_TEXT,
    'ru': RU_ERRORS_TEXT,
    'ko': KO_ERRORS_TEXT,
}


def main():
    base = 'src/docsContent'
    for lang, errors_text in LANG_ERRORS.items():
        filepath = f'{base}/{lang}.ts'
        if not os.path.exists(filepath):
            print(f"SKIP: {filepath} not found")
            continue
        content = open(filepath).read()
        new_content = replace_errors(content, 'index-tts', errors_text)
        if new_content is content:
            print(f"SKIP: {lang} - no replacement made")
            continue
        open(filepath, 'w').write(new_content)
        print(f"UPDATED: {lang}.ts")

    print("\nDone updating 5 main languages.")


if __name__ == '__main__':
    main()
