import { useCallback, useEffect, useMemo, useState } from 'react';
import { playSound } from './audioEngine';
import type { AppLanguage, BaseCharacter, CoreStat, SettingsState } from './types';

// ─── Types ───

type SharedPageProps = {
  appSubtitle: string;
  backHome: string;
  openSettings: string;
  privacyNote: string;
  pageTitle: string;
  pageDescription: string;
  settings: SettingsState;
  language: AppLanguage;
  onBack: () => void;
  onOpenSettings: () => void;
  onSwitchTool?: (toolId: string) => void;
  onOpenDocs?: (toolId?: string, section?: string, errorCode?: string) => void;
};

function useMaybeConfirm(settings: SettingsState) {
  return useCallback((message: string, action: () => void) => {
    if (!settings.others.confirmDestructiveActions || window.confirm(message)) {
      action();
    }
  }, [settings.others.confirmDestructiveActions]);
}



export type AuTemplateId =
  | 'modern-school'
  | 'cyberpunk'
  | 'medieval'
  | 'post-apocalypse'
  | 'magic-academy'
  | 'space-colony'
  | 'steampunk'
  | 'horror-mansion';

export type AuVersion = {
  id: string;
  baseName: string;
  templateId: AuTemplateId;
  generatedStats: Record<CoreStat, number>;
  outfit: string;
  background: string;
  flavor: string;
  createdAt: string;
};

export type AuGeneratorState = {
  base: BaseCharacter;
  versions: AuVersion[];
  activeVersionId: string | null;
};

// ─── Localization ───

const UI_COPY: Record<string, Record<string, string>> = {
  zh: {
    baseCharacter: '基础角色',
    name: '角色名',
    personality: '性格描述',
    stats: '核心属性',
    str: '力量',
    dex: '敏捷',
    int: '智力',
    cha: '魅力',
    vit: '体质',
    luk: '幸运',
    generate: '生成 AU 版本',
    template: 'AU 模板',
    outfit: '服装',
    background: '背景',
    flavor: '风味描述',
    comparison: '原版 vs AU',
    original: '原版',
    auVersion: 'AU 版本',
    save: '保存',
    delete: '删除',
    deleteConfirm: '确定删除这个 AU 版本吗？',
    emptyVersions: '暂无 AU 版本，输入基础角色信息后点击生成',
    versionCount: '个 AU 版本',
    statUp: '↑',
    statDown: '↓',
    statSame: '→',
    exportText: '导出文本',
    close: '关闭',
    untitledScene: '未命名角色',
    copied: '已复制',
    copy: '复制',
    generatedBy: '生成自 Original Character Maker',
  },
  ja: {
    baseCharacter: 'ベースキャラ',
    name: 'キャラ名',
    personality: '性格',
    stats: 'コアステータス',
    str: '筋力',
    dex: '敏捷',
    int: '知性',
    cha: '魅力',
    vit: '体力',
    luk: '運',
    generate: 'AU版を生成',
    template: 'AUテンプレート',
    outfit: '服装',
    background: '背景',
    flavor: 'フレーバーテキスト',
    comparison: '原版 vs AU',
    original: '原版',
    auVersion: 'AU版',
    save: '保存',
    delete: '削除',
    deleteConfirm: 'このAU版を削除しますか？',
    emptyVersions: 'まだAU版がありません。ベース情報を入力して生成してください。',
    versionCount: '個のAU版',
    statUp: '↑',
    statDown: '↓',
    statSame: '→',
    exportText: 'テキスト出力',
    close: '閉じる',
    untitledScene: '無名キャラ',
    copied: 'コピー完了',
    copy: 'コピー',
    generatedBy: 'Original Character Maker で生成',
  },
  en: {
    baseCharacter: 'Base Character',
    name: 'Name',
    personality: 'Personality',
    stats: 'Core Stats',
    str: 'STR',
    dex: 'DEX',
    int: 'INT',
    cha: 'CHA',
    vit: 'VIT',
    luk: 'LUK',
    generate: 'Generate AU',
    template: 'AU Template',
    outfit: 'Outfit',
    background: 'Background',
    flavor: 'Flavor Text',
    comparison: 'Original vs AU',
    original: 'Original',
    auVersion: 'AU Version',
    save: 'Save',
    delete: 'Delete',
    deleteConfirm: 'Delete this AU version?',
    emptyVersions: 'No AU versions yet. Enter base info and click generate.',
    versionCount: 'AU versions',
    statUp: '↑',
    statDown: '↓',
    statSame: '→',
    exportText: 'Export Text',
    close: 'Close',
    untitledScene: 'Unnamed Character',
    copied: 'Copied',
    copy: 'Copy',
    generatedBy: 'Generated by Original Character Maker',
  },
  ru: {
    baseCharacter: 'Базовый персонаж',
    name: 'Имя',
    personality: 'Характер',
    stats: 'Основные характеристики',
    str: 'СИЛ',
    dex: 'ЛОВ',
    int: 'ИНТ',
    cha: 'ХАР',
    vit: 'ЖИВ',
    luk: 'УДА',
    generate: 'Сгенерировать АВ',
    template: 'Шаблон АВ',
    outfit: 'Одежда',
    background: 'Предыстория',
    flavor: 'Описание',
    comparison: 'Оригинал vs АВ',
    original: 'Оригинал',
    auVersion: 'АВ-версия',
    save: 'Сохранить',
    delete: 'Удалить',
    deleteConfirm: 'Удалить эту АВ-версию?',
    emptyVersions: 'Пока нет АВ-версий. Введите базовую информацию и нажмите «Сгенерировать».',
    versionCount: 'АВ-версий',
    statUp: '↑',
    statDown: '↓',
    statSame: '→',
    exportText: 'Экспорт текста',
    close: 'Закрыть',
    untitledScene: 'Безымянный персонаж',
    copied: 'Скопировано',
    copy: 'Копировать',
    generatedBy: 'Создано в Original Character Maker',
  },
  ko: {
    baseCharacter: '베이스 캐릭터',
    name: '이름',
    personality: '성격',
    stats: '핵심 스탯',
    str: '힘',
    dex: '민첩',
    int: '지능',
    cha: '매력',
    vit: '활력',
    luk: '행운',
    generate: 'AU 생성',
    template: 'AU 템플릿',
    outfit: '의상',
    background: '배경',
    flavor: '플레이버 텍스트',
    comparison: '원판 vs AU',
    original: '원판',
    auVersion: 'AU 버전',
    save: '저장',
    delete: '삭제',
    deleteConfirm: '이 AU 버전을 삭제하시겠습니까?',
    emptyVersions: '아직 AU 버전이 없습니다. 베이스 정보를 입력하고 생성하세요.',
    versionCount: '개 AU 버전',
    statUp: '↑',
    statDown: '↓',
    statSame: '→',
    exportText: '텍스트 내보내기',
    close: '닫기',
    untitledScene: '이름 없는 캐릭터',
    copied: '복사됨',
    copy: '복사',
    generatedBy: 'Original Character Maker 에서 생성됨',
  },
};

// ─── AU Templates ───

type TemplateData = {
  id: AuTemplateId;
  name: Record<string, string>;
  description: Record<string, string>;
  statMods: Partial<Record<CoreStat, number>>;
  outfit: Record<string, string[]>;
  background: Record<string, string[]>;
  flavor: Record<string, string[]>;
};

const AU_TEMPLATES: TemplateData[] = [
  {
    id: 'modern-school',
    name: { zh: '现代校园', ja: '現代学園', en: 'Modern School', ru: 'Современная школа', ko: '현대 학원' },
    description: { zh: '角色是一名普通高中生，隐藏身份在校园中生活。', ja: 'キャラクターは正体を隠した普通の高校生。', en: 'The character is an ordinary high school student hiding their true identity.', ru: 'Персонаж — обычный старшеклассник, скрывающий свою истинную личность.', ko: '캐릭터는 정체를 숨긴 평범한 고등학생입니다.' },
    statMods: { str: -2, dex: +1, int: +2, cha: +1, vit: 0, luk: 0 },
    outfit: {
      zh: ['整洁的校服', '运动鞋', '双肩包', '运动服', '夏季短袖制服'],
      ja: ['清潔な制服', '運動靴', 'リュックサック', '体操服', '夏用半袖制服'],
      en: ['Clean school uniform', 'Sneakers', 'Backpack', 'Gym clothes', 'Summer short-sleeve uniform'],
      ru: ['Чистая школьная форма', 'Кроссовки', 'Рюкзак', 'Спортивная форма', 'Летняя форма с короткими рукавами'],
      ko: ['깔끔한 교복', '운동화', '백팩', '체육복', '여름 반팔 교복'],
    },
    background: {
      zh: ['转学到新城市的高中', '是某个秘密社团的唯一成员', '每天放学后会去打工', '在学校屋顶上独自午餐', '成绩优异但社交困难'],
      ja: ['新しい街の高校に転校してきた', '秘密サークルの唯一のメンバー', '放課後はアルバイト', '屋上で一人お昼ご飯', '成績優秀だが人付き合いが苦手'],
      en: ['Transferred to a new city high school', 'The only member of a secret club', 'Works part-time after school', 'Eats lunch alone on the rooftop', 'Top grades but socially awkward'],
      ru: ['Перевёлся в старшую школу нового города', 'Единственный член тайного клуба', 'Подрабатывает после школы', 'Обедает в одиночестве на крыше', 'Отличная успеваемость, но социально неуклюжий'],
      ko: ['새 도시의 고등학교로 전학', '비밀 동아리의 유일한 멤버', '방과 후 아르바이트', '옥상에서 혼자 점심', '성적은 우수하지만 사교적 어려움'],
    },
    flavor: {
      zh: ['在平凡日常中隐藏着不平凡的命运。', '课桌抽屉里藏着一把神秘的钥匙。', '没有人注意到他们眼中闪过的光芒。'],
      ja: ['平凡な日常の中に非凡な運命が隠されている。', '机の引き出しには謎の鍵が隠されている。', '誰も彼らの目に宿る光に気づかない。'],
      en: ['An extraordinary destiny hidden within an ordinary daily life.', 'A mysterious key hidden in the desk drawer.', 'No one notices the gleam in their eyes.'],
      ru: ['Необычная судьба, скрытая в обычной повседневной жизни.', 'Таинственный ключ, спрятанный в ящике парты.', 'Никто не замечает блеска в их глазах.'],
      ko: ['평범한 일상 속에 숨겨진 비범한 운명.', '책상 서랍에 숨겨진 신비한 열쇠.', '아무도 그들 눈에 비친 빛을 알아차리지 못한다.'],
    },
  },
  {
    id: 'cyberpunk',
    name: { zh: '赛博朋克', ja: 'サイバーパンク', en: 'Cyberpunk', ru: 'Киберпанк', ko: '사이버펑크' },
    description: { zh: '角色是霓虹都市中的边缘人，在高科技与低生活的夹缝中求存。', ja: 'キャラクターはネオン都市のはみ出し者。', en: 'The character is an outcast in a neon-drenched metropolis.', ru: 'Персонаж — изгой в залитом неоном мегаполисе.', ko: '캐릭터는 네온 도시의 소외자입니다.' },
    statMods: { str: 0, dex: +3, int: +3, cha: -1, vit: -1, luk: 0 },
    outfit: {
      zh: ['光学迷彩夹克', '神经接口头带', '机械义肢手臂', '全息投影围巾', '反光战斗靴'],
      ja: ['光学迷彩ジャケット', '神経インターフェースヘッドバンド', '義手アーム', 'ホログラフィックスカーフ', '反光戦闘靴'],
      en: ['Optical-camo jacket', 'Neural-interface headband', 'Prosthetic arm', 'Holographic scarf', 'Reflective combat boots'],
      ru: ['Куртка с оптическим камуфляжем', 'Нейроинтерфейсная повязка', 'Протез руки', 'Голографический шарф', 'Светоотражающие боевые ботинки'],
      ko: ['광학 위장 재킷', '신경 인터페이스 헤드밴드', '의수 팔', '홀로그램 스카프', '반사 전투화'],
    },
    background: {
      zh: ['地下黑客组织的成员', '被大公司通缉的逃犯', '在废墟酒吧做调酒师', '依靠改造身体维持生命', '掌握着能颠覆城市的机密数据'],
      ja: ['地下ハッカー集団のメンバー', '大企業に指名手配されている逃亡者', '廃墟バーでバーテンダー', '肉体改造で命を繋いでいる', '都市を覆す機密データを握っている'],
      en: ['Member of an underground hacker collective', 'Fugitive wanted by megacorps', 'Bartender at a ruined bar', 'Keeps alive through body mods', 'Holds classified data that could topple the city'],
      ru: ['Член подпольной хакерской группировки', 'Беглец, разыскиваемый мегакорпорациями', 'Бармен в заброшенном баре', 'Поддерживает жизнь с помощью имплантов', 'Владеет секретными данными, способными свергнуть город'],
      ko: ['지하 해커 집단의 멤버', '대기업에 지명수배된 도주자', '폐허 바에서 바텐더', '신체 개조로 생명을 유지', '도시를 뒤흔들 기밀 데이터를 보유'],
    },
    flavor: {
      zh: ['在数据流的海洋中，他们是唯一保持人性温度的幽灵。', '霓虹灯光照不到的地方，才是真实的城市。', '每一次呼吸都伴随着电路的嗡鸣。'],
      ja: ['データの海の中で、彼らだけが人間の温度を保つ幽霊。', 'ネオンの光が届かない場所に、本当の都市がある。', '每一次の呼吸に回路のうなりが伴う。'],
      en: ['In the ocean of data streams, they are the only ghosts still warm with humanity.', 'The real city lies where neon light cannot reach.', 'Every breath is accompanied by the hum of circuits.'],
      ru: ['В океане потоков данных они — единственные призраки, всё ещё тёплые от человечности.', 'Настоящий город там, куда не достаёт неоновый свет.', 'Каждое дыхание сопровождается гулом цепей.'],
      ko: ['데이터의 바다에서 그들은 유일하게 인간성의 온기를 간직한 유령.', '네온 불빛이 닿지 않는 곳에 진정한 도시가 있다.', '모든 호흡은 회로의 윙윙거림과 함께한다.'],
    },
  },
  {
    id: 'medieval',
    name: { zh: '中世纪', ja: '中世', en: 'Medieval', ru: 'Средневековье', ko: '중세' },
    description: { zh: '角色是王国中的骑士、法师或流浪者，在剑与魔法的世界中冒险。', ja: 'キャラクターは王国の騎士、魔導士、または放浪者。', en: 'The character is a knight, mage, or wanderer in a realm of sword and sorcery.', ru: 'Персонаж — рыцарь, маг или странник в королевстве меча и колдовства.', ko: '캐릭터는 검과 마법의 왕국에서 기사, 마법사 또는 방랑자입니다.' },
    statMods: { str: +2, dex: 0, int: +1, cha: +1, vit: +2, luk: 0 },
    outfit: {
      zh: ['镀银骑士铠甲', '法师长袍与兜帽', '皮甲与斗篷', '教会修女服', '王室礼服'],
      ja: ['銀メッキの騎士鎧', '魔導士のローブとフード', '革鎧とマント', '教会の修道女服', '王室の礼装'],
      en: ['Silver-plated knight armor', 'Mage robe and hood', 'Leather armor and cloak', 'Church nun habit', 'Royal gown'],
      ru: ['Серебряные рыцарские доспехи', 'Мантия и капюшон мага', 'Кожаные доспехи и плащ', 'Монашеская ряса', 'Королевское платье'],
      ko: ['은도금 기사 갑옷', '마법사 로브와 후드', '가죽 갑옷과 망토', '교회 수녀복', '왕실 예복'],
    },
    background: {
      zh: ['王国骑士团的见习骑士', '被流放的皇族后裔', '流浪的药剂师', '守护古老遗迹的守卫', '追寻传说的吟游诗人'],
      ja: ['王国騎士団の見習い騎士', '追放された皇族の末裔', '放浪の薬剤師', '古代遺跡を守る番人', '伝説を追う吟遊詩人'],
      en: ['Squire of the royal knightly order', 'Exiled descendant of royalty', 'Wandering apothecary', 'Guardian of ancient ruins', 'Bard chasing legends'],
      ru: ['Оруженосец королевского рыцарского ордена', 'Изгнанный потомок королевской крови', 'Странствующий знахарь', 'Хранитель древних руин', 'Бард, гонящийся за легендами'],
      ko: ['왕국 기사단의 견습 기사', '추방된 왕족의 후예', '방랑하는 약제사', '고대 유적의 수호자', '전설을 쫓는 음유시인'],
    },
    flavor: {
      zh: ['他们的剑上刻着一个被遗忘的誓言。', '篝火旁的传说因他们而延续。', '古老的魔法在他们血脉中沉睡。'],
      ja: ['彼らの剣には忘れられた誓いが刻まれている。', '焚き火の傍らの伝説は彼らによって紡がれる。', '古の魔法が彼らの血に眠っている。'],
      en: ['Their blade bears a forgotten oath.', 'The legends by the campfire are woven by them.', 'Ancient magic slumbers in their blood.'],
      ru: ['На их клинке высечена забытая клятва.', 'Легенды у костра создаются благодаря им.', 'Древняя магия дремлет в их крови.'],
      ko: ['그들의 검에는 잊혀진 맹세가 새겨져 있다.', '모닥불 옆의 전설은 그들에 의해 이어진다.', '고대의 마법이 그들의 피 속에서 잠들어 있다.'],
    },
  },
  {
    id: 'post-apocalypse',
    name: { zh: '末日废土', ja: '終末荒廃地', en: 'Post-Apocalypse', ru: 'Постапокалипсис', ko: '종말 황무지' },
    description: { zh: '角色是废墟世界中的幸存者，在资源匮乏和危险环境中挣扎求生。', ja: 'キャラクターは廃墟世界の生存者。', en: 'The character is a survivor in a ruined world.', ru: 'Персонаж — выживший в разрушенном мире.', ko: '캐릭터는 폐허 세계의 생존자입니다.' },
    statMods: { str: +1, dex: +1, int: 0, cha: -2, vit: +3, luk: +1 },
    outfit: {
      zh: ['防辐射防护服', '自制皮革护甲', '护目镜与呼吸器', '补丁大衣', '绑腿与登山靴'],
      ja: ['放射線防護服', '自作の革鎧', 'ゴーグルと呼吸器', 'パッチワークコート', '脚絆と登山靴'],
      en: ['Radiation suit', 'Homemade leather armor', 'Goggles and respirator', 'Patchwork coat', 'Puttees and hiking boots'],
      ru: ['Радиационный костюм', 'Самодельная кожаная броня', 'Очки и респиратор', 'Лоскутное пальто', 'Обмотки и треккинговые ботинки'],
      ko: ['방사선 방호복', '자작 가죽 갑옷', '고글과 호흡기', '누더기 코트', '다리 붕대와 등산화'],
    },
    background: {
      zh: ['独自在废墟中生活了十年', '是某个幸存者营地的医生', '驾驶改装车辆在废土中穿行', '掌握着净化水源的技术', '失去了所有家人后在流浪'],
      ja: ['廃墟で一人で10年を生き延びた', '生存者キャンプの医者', '改造車で荒廃地を走る', '水を浄化する技術を持つ', '家族を全員失い放浪中'],
      en: ['Survived alone in the ruins for ten years', 'Doctor of a survivor camp', 'Drives a modified vehicle across the wasteland', 'Holds the technology to purify water', 'Wandering after losing all family'],
      ru: ['Десять лет выживал в одиночку в руинах', 'Врач лагеря выживших', 'Путешествует по пустоши на переделанном транспорте', 'Владеет технологией очистки воды', 'Скитается после потери всей семьи'],
      ko: ['폐허에서 혼자 10년을 생존', '생존자 캠프의 의사', '개조 차량으로 황무지를 질주', '물 정화 기술을 보유', '가족을 모두 잃고 방랑 중'],
    },
    flavor: {
      zh: ['在绝望的土壤上，希望是最顽强的野草。', '他们的眼中映着燃烧的世界，却依然向前走。', '每一次日出都是对死亡的嘲弄。'],
      ja: ['絶望の土壌に、希望は最もしぶとい雑草。', '彼らの目に映る燃える世界でも、なお前を向く。', '每一次の日の出は死への嘲笑。'],
      en: ['On the soil of despair, hope is the most stubborn weed.', 'Their eyes reflect a burning world, yet they still move forward.', 'Every sunrise is a mockery of death.'],
      ru: ['На почве отчаяния надежда — самый упрямый сорняк.', 'В их глазах отражается горящий мир, но они всё равно идут вперёд.', 'Каждый восход солнца — насмешка над смертью.'],
      ko: ['절망의 토양 위에서 희망은 가장 완강한 잡초.', '그들의 눈에 비치는 불타는 세계 속에서도 여전히 앞으로 나아간다.', '매일의 일출은 죽음에 대한 조롱이다.'],
    },
  },
  {
    id: 'magic-academy',
    name: { zh: '魔法学院', ja: '魔法学院', en: 'Magic Academy', ru: 'Академия магии', ko: '마법 학원' },
    description: { zh: '角色是魔法学院的学生或导师，在知识与魔法交织的塔楼中学习。', ja: 'キャラクターは魔法学院の生徒または導師。', en: 'The character is a student or mentor at a magic academy.', ru: 'Персонаж — студент или наставник в академии магии.', ko: '캐릭터는 마법 학원의 학생 또는导師입니다.' },
    statMods: { str: -1, dex: 0, int: +3, cha: +2, vit: 0, luk: +1 },
    outfit: {
      zh: ['学院制服长袍', '魔法书腰包', '元素属性徽章', '星辰图案披风', '魔法杖挂带'],
      ja: ['学院制服ローブ', '魔導書ポーチ', '属性エンブレム', '星柄マント', '杖ホルダー'],
      en: ['Academy uniform robe', 'Grimoire pouch', 'Element emblem', 'Star-patterned cloak', 'Wand holster'],
      ru: ['Академическая мантия', 'Сумка для гримуара', 'Эмблема стихии', 'Плащ со звёздным узором', 'Кобура для жезла'],
      ko: ['학원 제복 로브', '마도서 파우치', '속성 엠블럼', '별무늬 망토', '지팡이 홀더'],
    },
    background: {
      zh: ['被学院破格录取的天才', '因家族诅咒而学习魔法', '隐藏身份的异界来客', '在禁书区做管理员的留级生', '为寻找失踪导师而入学'],
      ja: ['学院に飛び級で合格した天才', '家の呪いを解くために魔法を学ぶ', '正体を隠した異世界の来訪者', '禁書区の管理人として留年した生徒', '行方不明の導師を探して入学'],
      en: ['Admitted as a prodigy', 'Studies magic to break a family curse', 'Otherworldly visitor hiding their identity', 'Repeat student working as the forbidden-section librarian', 'Enrolled to find a missing mentor'],
      ru: ['Зачислен как вундеркинд', 'Изучает магию, чтобы снять семейное проклятие', 'Пришелец из другого мира, скрывающий личность', 'Отчисленный студент, работающий библиотекарем запретного отдела', 'Поступил, чтобы найти пропавшего наставника'],
      ko: ['천재로 특별 입학', '가족의 저주를 풀기 위해 마법을 배움', '정체를 숨긴 이세계 방문자', '금서 구역 관리인으로 유급한 학생', '실종된导師를 찾아 입학'],
    },
    flavor: {
      zh: ['他们的魔法天赋被古老的封印所掩盖。', '图书馆最深处有一本只对他们开放的禁书。', '午夜的钟声响起时，他们的魔法最强大。'],
      ja: ['彼らの魔法の才能は古い封印に隠されている。', '図書館の最深部には彼らだけに開かれる禁書がある。', '真夜中の鐘が鳴る時、彼らの魔法は最も強くなる。'],
      en: ['Their magical talent is concealed by an ancient seal.', 'In the deepest part of the library lies a forbidden book open only to them.', 'When the midnight bell tolls, their magic is at its strongest.'],
      ru: ['Их магический талант скрыт древней печатью.', 'В самой глубине библиотеки лежит запретная книга, открытая только для них.', 'Когда бьёт полночный колокол, их магия достигает пика.'],
      ko: ['그들의 마법 재능은 고대의 봉인에 가려져 있다.', '도서관 가장 깊은 곳에는 그들만을 위해 열리는 금서가 있다.', '자정의 종이 울릴 때, 그들의 마법은 가장 강력해진다.'],
    },
  },
  {
    id: 'space-colony',
    name: { zh: '太空殖民', ja: '宇宙コロニー', en: 'Space Colony', ru: 'Космическая колония', ko: '우주 식민지' },
    description: { zh: '角色是太空殖民地中的居民，在浩瀚宇宙中建立新家园。', ja: 'キャラクターは宇宙コロニーの居住者。', en: 'The character is a resident of a space colony.', ru: 'Персонаж — житель космической колонии.', ko: '캐릭터는 우주 식민지의 주민입니다.' },
    statMods: { str: 0, dex: +2, int: +2, cha: 0, vit: +1, luk: +1 },
    outfit: {
      zh: ['太空服内衬', '零重力训练服', '殖民地制服', '外太空探索服', '智能纤维外套'],
      ja: ['宇宙服インナー', '無重力訓練服', 'コロニー制服', '宇宙探索服', 'スマートファイバーコート'],
      en: ['Spacesuit liner', 'Zero-G training suit', 'Colony uniform', 'EVA suit', 'Smart-fiber coat'],
      ru: ['Внутренняя обшивка скафандра', 'Костюм для тренировок в невесомости', 'Форма колонии', 'Скафандр для выхода в открытый космос', 'Пальто из умных волокон'],
      ko: ['우주복 이너', '무중력 훈련복', '식민지 복장', '우주 탐사복', '스마트 섬유 코트'],
    },
    background: {
      zh: ['出生在宇宙中的第一代殖民者', '负责维护空间站生态系统的工程师', '从地球逃难而来的难民', '在星际航线上长大的飞行员', '研究外星生物的科学家'],
      ja: ['宇宙で生まれた第一世代の入植者', 'ステーションの生態系を維持するエンジニア', '地球から逃れてきた難民', '星間航路で育ったパイロット', '地球外生物を研究する科学者'],
      en: ['First-generation colonist born in space', 'Engineer maintaining the station ecosystem', 'Refugee who fled Earth', 'Pilot raised on interstellar routes', 'Scientist studying alien life'],
      ru: ['Колонист первого поколения, рождённый в космосе', 'Инженер, поддерживающий экосистему станции', 'Беженец, спасшийся с Земли', 'Пилот, выросший на межзвёздных маршрутах', 'Учёный, изучающий инопланетную жизнь'],
      ko: ['우주에서 태어난 1세대 식민자', '스테이션 생태계를 유지하는 엔지니어', '지구에서 피난온 난민', '성간 항로에서 자란 파일럿', '외계 생명체를 연구하는 과학자'],
    },
    flavor: {
      zh: ['他们从舷窗望出去时，星星会回应他们的目光。', '在无重力的黑暗中，他们是唯一的光。', '他们的足迹将留在人类从未踏足过的星球上。'],
      ja: ['彼らが窓から外を見ると、星が視線に応える。', '無重力の闇の中で、彼らだけが光である。', '彼らの足跡は人類が未踏の惑星に残される。'],
      en: ['When they gaze out the porthole, the stars answer their gaze.', 'In the weightless darkness, they are the only light.', 'Their footprints will remain on planets no human has ever set foot on.'],
      ru: ['Когда они смотрят из иллюминатора, звёзды отвечают на их взгляд.', 'В невесомой тьме они — единственный свет.', 'Их следы останутся на планетах, где никогда не ступала нога человека.'],
      ko: ['그들이 창밖을 바라볼 때, 별들이 그들의 시선에 답한다.', '무중력의 어둠 속에서 그들은 유일한 빛.', '그들의 발자국은 인류가 한 번도 밟지 않은 행성에 남을 것이다.'],
    },
  },
  {
    id: 'steampunk',
    name: { zh: '蒸汽朋克', ja: 'スチームパンク', en: 'Steampunk', ru: 'Стимпанк', ko: '스팀펑크' },
    description: { zh: '角色是齿轮与蒸汽世界中的发明家或冒险家。', ja: 'キャラクターは歯車と蒸気の世界の発明家または冒険家。', en: 'The character is an inventor or adventurer in a world of gears and steam.', ru: 'Персонаж — изобретатель или авантюрист в мире шестерёнок и пара.', ko: '캐릭터는 톱니바퀴와 증기의 세계에서 발명가 또는 모험가입니다.' },
    statMods: { str: +1, dex: -1, int: +3, cha: +1, vit: 0, luk: +1 },
    outfit: {
      zh: ['黄铜护目镜', '蒸汽动力装甲', '齿轮装饰礼帽', '皮革工具腰带', '机械假肢'],
      ja: ['真鍮ゴーグル', '蒸気パワードアーマー', '歯車飾りのシルクハット', '革製工具ベルト', '機械義肢'],
      en: ['Brass goggles', 'Steam-powered armor', 'Gear-adorned top hat', 'Leather tool belt', 'Mechanical prosthetic'],
      ru: ['Латунные очки', 'Паровая броня', 'Цилиндр с шестерёнками', 'Кожаный пояс для инструментов', 'Механический протез'],
      ko: ['황동 고글', '증기 동력 갑옷', '톱니 장식 실크햇', '가죽 공구 벨트', '기계 의족'],
    },
    background: {
      zh: ['发明了改变世界的蒸汽引擎', '在飞艇上当机械师', '寻找失落的古代机械文明', '为贵族设计自动仆从', '因蒸汽爆炸事故失去了手臂'],
      ja: ['世界を変える蒸気機関を発明した', '飛行船の機関士', '失われた古代機械文明を探す', '貴族のために自動従者を設計', '蒸気爆発事故で腕を失った'],
      en: ['Invented a steam engine that changed the world', 'Airship mechanic', 'Searching for a lost ancient mechanical civilization', 'Designs automaton servants for nobility', 'Lost an arm in a steam explosion accident'],
      ru: ['Изобрёл паровой двигатель, изменивший мир', 'Механик дирижабля', 'Ищет затерянную древнюю механическую цивилизацию', 'Конструирует автоматонов-слуг для знати', 'Потерял руку в паровом взрыве'],
      ko: ['세상을 바꾸는 증기 기관을 발명', '비행선 기관사', '잃어버린 고대 기계 문명을 찾는 중', '귀족을 위해 자동 하인을 설계', '증기 폭발 사고로 팔을 잃음'],
    },
    flavor: {
      zh: ['他们的发明总是在即将成功时冒出故障的白烟。', '齿轮转动的声音是他们最熟悉的摇篮曲。', '在蒸汽与黄铜的世界里，想象力是最强大的引擎。'],
      ja: ['彼らの発明は成功寸前でいつも故障の白煙を上げる。', '歯車の回る音は彼らにとって最も馴染みのある子守唄。', '蒸気と真鍮の世界で、想像力は最も強力なエンジンである。'],
      en: ['Their inventions always emit a puff of failure white smoke at the brink of success.', 'The sound of turning gears is their most familiar lullaby.', 'In a world of steam and brass, imagination is the most powerful engine.'],
      ru: ['Их изобретения всегда выпускают клубок белого дыма неудачи на грани успеха.', 'Звук вращающихся шестерёнок — их самая знакомая колыбельная.', 'В мире пара и латуни воображение — самый мощный двигатель.'],
      ko: ['그들의 발명은 성공 직전에 항상 고장의 흰 연기를 내뿜는다.', '톱니바퀴 돌아가는 소리는 그들에게 가장 익숙한 자장가.', '증기와 황동의 세계에서 상상력은 가장 강력한 엔진이다.'],
    },
  },
  {
    id: 'horror-mansion',
    name: { zh: '恐怖洋馆', ja: '恐怖の洋館', en: 'Horror Mansion', ru: 'Дом ужасов', ko: '공포의 저택' },
    description: { zh: '角色被困在一座充满诡异事件的古老洋馆中。', ja: 'キャラクターは不気味な事件が起きる古い洋館に閉じ込められている。', en: 'The character is trapped in an old mansion full of eerie events.', ru: 'Персонаж заперт в старом особняке, полном жутких событий.', ko: '캐릭터는 기이한 사건이 가득한 오래된 저택에 갇혀 있습니다.' },
    statMods: { str: 0, dex: +2, int: +1, cha: -3, vit: -1, luk: -2 },
    outfit: {
      zh: ['沾满灰尘的晚礼服', '破损的睡袍', '沾血的围裙', '褪色的病号服', '破旧的人偶服装'],
      ja: ['埃まみれの夜会服', '破れた寝間着', '血染めのエプロン', '色褪せた患者服', 'ボロボロの人形服'],
      en: ['Dust-covered evening gown', 'Torn nightgown', 'Blood-stained apron', 'Faded hospital gown', 'Ragged doll costume'],
      ru: ['Вечернее платье в пыли', 'Порванная ночная рубашка', 'Фартук в крови', 'Выцветший больничный халат', 'Потрёпанный костюм куклы'],
      ko: ['먼지 쌓인 이브닝 드레스', '찢어진 잠옷', '피 묻은 앞치마', '빛바랜 환자복', '낡은 인형 옷'],
    },
    background: {
      zh: ['是这座洋馆最后一位继承人的后代', '醒来时发现自己失去了记忆', '被迫参与某种古老仪式', '能看见死去居民的幽灵', '是洋馆主人的实验品'],
      ja: ['この洋館の最後の相続人の末裔', '目が覚めると記憶を失っていた', '古い儀式に強制参加させられている', '死んだ住人の幽霊が見える', '館主の実験体'],
      en: ['Descendant of the mansion\'s last heir', 'Woke up with no memory', 'Forced to participate in an ancient ritual', 'Can see the ghosts of dead residents', 'The master\'s experiment subject'],
      ru: ['Потомок последнего наследника особняка', 'Проснулся без памяти', 'Вынужден участвовать в древнем ритуале', 'Видит призраков мёртвых жильцов', 'Объект экспериментов хозяина'],
      ko: ['이 저택의 마지막 상속자의 후예', '눈을 떠보니 기억을 잃었다', '고대 의식에 강제 참가당함', '죽은 주민의 유령이 보임', '저택 주인의 실험 대상'],
    },
    flavor: {
      zh: ['镜子里的倒影比他们慢了一秒才动。', '每到午夜，洋馆的走廊就会变长。', '他们的影子有时会独自行动。'],
      ja: ['鏡の中の倒影は彼らより1秒遅れて動く。', '真夜中になると、洋館の廊下が長くなる。', '彼らの影は時々独りで動く。'],
      en: ['The reflection in the mirror moves one second slower than them.', 'At midnight, the mansion corridors grow longer.', 'Their shadow sometimes moves on its own.'],
      ru: ['Отражение в зеркале движется на секунду медленнее их.', 'В полночь коридоры особняка удлиняются.', 'Их тень иногда движется сама по себе.'],
      ko: ['거울 속의 반영은 그들보다 1초 늦게 움직인다.', '자정이 되면 저택의 복도가 길어진다.', '그들의 그림자는 때때로 혼자 움직인다.'],
    },
  },
];

// ─── Helpers ───

function uid() {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getCopy(language: AppLanguage) {
  return UI_COPY[language] ?? UI_COPY.en;
}

function getTemplate(id: AuTemplateId): TemplateData | undefined {
  return AU_TEMPLATES.find((t) => t.id === id);
}

function clampStat(value: number): number {
  if (!Number.isFinite(value)) return 50;
  return Math.min(100, Math.max(1, Math.round(value)));
}

function defaultBaseCharacter(): BaseCharacter {
  return {
    name: '',
    personality: '',
    stats: { str: 50, dex: 50, int: 50, cha: 50, vit: 50, luk: 50 },
  };
}

function generateAuVersion(base: BaseCharacter, template: TemplateData, language: AppLanguage): AuVersion {
  const stats: Record<CoreStat, number> = { ...base.stats };
  (Object.keys(template.statMods) as CoreStat[]).forEach((key) => {
    const mod = template.statMods[key] ?? 0;
    stats[key] = clampStat(stats[key] + mod * 10 + (Math.random() * 10 - 5));
  });

  const pool = template.outfit[language] ?? template.outfit.en;
  const bgPool = template.background[language] ?? template.background.en;
  const flPool = template.flavor[language] ?? template.flavor.en;

  return {
    id: uid(),
    baseName: base.name,
    templateId: template.id,
    generatedStats: stats,
    outfit: pick(pool),
    background: pick(bgPool),
    flavor: pick(flPool),
    createdAt: new Date().toISOString(),
  };
}

const STORAGE_KEY = 'oc-maker.au-generator';

function readState(): AuGeneratorState {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw) as AuGeneratorState;
      if (parsed.base && parsed.versions) {
        return parsed;
      }
    }
  } catch { /* ignore */ }
  return { base: defaultBaseCharacter(), versions: [], activeVersionId: null };
}

function writeState(state: AuGeneratorState): boolean {
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    return true;
  } catch {
    return false;
  }
}

// ─── Component ───

export default function AuGeneratorPage({
  pageTitle,
  pageDescription,
  settings,
  language,
  onBack,
  onOpenSettings,
  onOpenDocs,
}: SharedPageProps) {
  const maybeConfirm = useMaybeConfirm(settings);
  const copy = getCopy(language);
  const [state, setState] = useState<AuGeneratorState>(readState);
  const [selectedTemplate, setSelectedTemplate] = useState<AuTemplateId>('modern-school');
  const [showExport, setShowExport] = useState(false);
  const [exportText, setExportText] = useState('');
  const [copied, setCopied] = useState(false);

  const { base, versions, activeVersionId } = state;
  const activeVersion = useMemo(() => versions.find((v) => v.id === activeVersionId) ?? null, [versions, activeVersionId]);

  useEffect(() => {
    writeState(state);
  }, [state]);

  useEffect(() => {
    if (!showExport) return;
    function handler(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        e.preventDefault();
        playSound('modalClose');
        setShowExport(false);
      }
    }
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [showExport]);

  const updateBase = useCallback((patch: Partial<BaseCharacter>) => {
    setState((prev) => ({ ...prev, base: { ...prev.base, ...patch } }));
  }, []);

  const updateStat = useCallback((key: CoreStat, value: number) => {
    setState((prev) => ({
      ...prev,
      base: { ...prev.base, stats: { ...prev.base.stats, [key]: clampStat(value) } },
    }));
  }, []);

  const generate = useCallback(() => {
    const template = getTemplate(selectedTemplate);
    if (!template) return;
    playSound('confirm');
    const version = generateAuVersion(base, template, language);
    setState((prev) => ({
      ...prev,
      versions: [...prev.versions, version],
      activeVersionId: version.id,
    }));
  }, [base, selectedTemplate, language]);

  const deleteVersion = useCallback((id: string) => {
    playSound('deleteSound');
    setState((prev) => {
      const nextVersions = prev.versions.filter((v) => v.id !== id);
      return {
        ...prev,
        versions: nextVersions,
        activeVersionId: prev.activeVersionId === id ? (nextVersions[0]?.id ?? null) : prev.activeVersionId,
      };
    });
  }, []);

  const generateExportText = useCallback((version: AuVersion): string => {
    const t = getTemplate(version.templateId);
    const tName = t?.name[language] ?? t?.name.en ?? version.templateId;
    const lines = [
      `# ${version.baseName} — ${tName}`,
      '',
      `**${copy.template}:** ${tName}`,
      `**${copy.outfit}:** ${version.outfit}`,
      `**${copy.background}:** ${version.background}`,
      '',
      `## ${copy.stats}`,
      '',
      ...(['str', 'dex', 'int', 'cha', 'vit', 'luk'] as CoreStat[]).map((k) => {
        const baseVal = base.stats[k];
        const auVal = version.generatedStats[k];
        const diff = auVal - baseVal;
        const arrow = diff > 0 ? copy.statUp : diff < 0 ? copy.statDown : copy.statSame;
        return `- ${copy[k]}: ${baseVal} ${arrow} ${auVal}`;
      }),
      '',
      `## ${copy.flavor}`,
      '',
      version.flavor,
      '',
      '---',
      `*${copy.generatedBy}*`,
    ];
    return lines.join('\n');
  }, [base.stats, copy, language]);

  const openExport = useCallback(() => {
    if (!activeVersion) return;
    playSound('modalOpen');
    setExportText(generateExportText(activeVersion));
    setShowExport(true);
  }, [activeVersion, generateExportText]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(exportText);
      setCopied(true);
      playSound('success');
      setTimeout(() => setCopied(false), 1500);
    } catch {
      playSound('error');
    }
  }, [exportText]);

  const statKeys: CoreStat[] = ['str', 'dex', 'int', 'cha', 'vit', 'luk'];

  return (
    <div className="page-container">
      {/* Header */}
      <div className="page-header-row">
        <div>
          <h2 className="page-title">{pageTitle}</h2>
          <p className="page-subtitle">{pageDescription}</p>
        </div>
        <div className="page-header-actions">
          {onOpenDocs && (
            <button className="secondary-button small-button" type="button" data-sfx-handled onClick={() => { playSound('buttonClick'); onOpenDocs('character-au'); }}>
              ?
            </button>
          )}
          <button className="secondary-button small-button" type="button" data-sfx-handled onClick={() => { playSound('buttonClick'); onOpenSettings(); }}>
            ⚙
          </button>
          <button className="secondary-button small-button" type="button" data-sfx-handled onClick={() => { playSound('back'); onBack(); }}>
            ←
          </button>
        </div>
      </div>

      <div className="au-generator-layout">
        {/* Base Character Panel */}
        <aside className="au-base-panel">
          <div className="au-panel-card">
            <h3 className="scene-section-title">{copy.baseCharacter}</h3>
            <input
              className="scene-input"
              id="au-base-name"
              type="text"
              placeholder={copy.name}
              value={base.name}
              onChange={(e) => updateBase({ name: e.target.value })}
            />
            <textarea
              className="scene-textarea"
              id="au-base-personality"
              rows={2}
              placeholder={copy.personality}
              value={base.personality}
              onChange={(e) => updateBase({ personality: e.target.value })}
            />
            <div className="au-stats-grid">
              {statKeys.map((key) => (
                <div key={key} className="au-stat-row">
                  <label className="au-stat-label" htmlFor={`au-stat-${key}`}>{copy[key]}</label>
                  <input
                    className="au-stat-input"
                    id={`au-stat-${key}`}
                    type="number"
                    min={1}
                    max={100}
                    value={base.stats[key]}
                    onChange={(e) => updateStat(key, Number(e.target.value))}
                  />
                  <input
                    className="au-stat-slider"
                    id={`au-stat-slider-${key}`}
                    type="range"
                    min={1}
                    max={100}
                    value={base.stats[key]}
                    onChange={(e) => updateStat(key, Number(e.target.value))}
                  />
                </div>
              ))}
            </div>
          </div>

          <div className="au-panel-card">
            <h3 className="scene-section-title">{copy.template}</h3>
            <div className="au-template-list">
              {AU_TEMPLATES.map((t) => (
                <button
                  key={t.id}
                  className={`choice-chip ${selectedTemplate === t.id ? 'active' : ''}`}
                  type="button"
                  data-sfx-handled
                  title={t.description[language] ?? t.description.en}
                  onClick={() => { playSound('select'); setSelectedTemplate(t.id); }}
                >
                  {t.name[language] ?? t.name.en}
                </button>
              ))}
            </div>
            {(() => {
              const td = getTemplate(selectedTemplate);
              return td ? (
                <p className="nemesis-type-description">{td.description[language] ?? td.description.en}</p>
              ) : null;
            })()}
            <button className="primary-button" type="button" data-sfx-handled onClick={generate} style={{ marginTop: 12, width: '100%' }}>
              ✦ {copy.generate}
            </button>
          </div>
        </aside>

        {/* Main Content */}
        <main className="au-main-panel">
          {!activeVersion ? (
            <div className="scene-empty-state">
              <div className="scene-empty-icon">🌀</div>
              <p>{copy.emptyVersions}</p>
            </div>
          ) : (
            <div className="au-version-detail">
              {/* Version Tabs */}
              <div className="au-version-tabs">
                {versions.map((v) => {
                  const t = getTemplate(v.templateId);
                  return (
                    <button
                      key={v.id}
                      className={`au-version-tab ${v.id === activeVersionId ? 'active' : ''}`}
                      type="button"
                      data-sfx-handled
                      onClick={() => { playSound('buttonClick'); setState((prev) => ({ ...prev, activeVersionId: v.id })); }}
                    >
                      {t?.name[language] ?? t?.name.en}
                      <span
                        className="au-version-tab-close"
                        role="button"
                        tabIndex={0}
                        aria-label={copy.delete}
                        onClick={(e) => {
                          e.stopPropagation();
                          maybeConfirm(copy.deleteConfirm, () => {
                            deleteVersion(v.id);
                          });
                        }}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter' || e.key === ' ') {
                            e.preventDefault();
                            e.stopPropagation();
                            maybeConfirm(copy.deleteConfirm, () => {
                              deleteVersion(v.id);
                            });
                          }
                        }}
                      >
                        ✕
                      </span>
                    </button>
                  );
                })}
              </div>

              {/* Comparison Cards */}
              <div className="au-comparison">
                {/* Original */}
                <div className="au-comparison-card">
                  <h4 className="au-card-title">{copy.original}</h4>
                  <div className="au-card-name">{base.name || copy.untitledScene}</div>
                  <div className="au-card-stats">
                    {statKeys.map((k) => (
                      <div key={k} className="au-card-stat">
                        <span className="au-card-stat-name">{copy[k]}</span>
                        <div className="au-card-stat-bar">
                          <div className="au-card-stat-fill" style={{ width: `${base.stats[k]}%` }} />
                        </div>
                        <span className="au-card-stat-value">{base.stats[k]}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* AU Version */}
                <div className="au-comparison-card au">
                  <h4 className="au-card-title">{copy.auVersion}</h4>
                  <div className="au-card-name">
                    {(getTemplate(activeVersion.templateId)?.name[language] ?? getTemplate(activeVersion.templateId)?.name.en) ?? activeVersion.templateId}
                  </div>
                  <div className="au-card-stats">
                    {statKeys.map((k) => {
                      const baseVal = base.stats[k];
                      const auVal = activeVersion.generatedStats[k];
                      const diff = auVal - baseVal;
                      return (
                        <div key={k} className={`au-card-stat ${diff > 0 ? 'up' : diff < 0 ? 'down' : ''}`}>
                          <span className="au-card-stat-name">{copy[k]}</span>
                          <div className="au-card-stat-bar">
                            <div className="au-card-stat-fill" style={{ width: `${auVal}%` }} />
                          </div>
                          <span className="au-card-stat-value">
                            {auVal}
                            {diff !== 0 && (
                              <span className={`au-card-stat-diff ${diff > 0 ? 'up' : 'down'}`}>
                                {diff > 0 ? `+${diff}` : diff}
                              </span>
                            )}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>

              {/* Details */}
              <div className="au-details">
                <div className="au-detail-item">
                  <label>{copy.outfit}</label>
                  <p>{activeVersion.outfit}</p>
                </div>
                <div className="au-detail-item">
                  <label>{copy.background}</label>
                  <p>{activeVersion.background}</p>
                </div>
                <div className="au-detail-item">
                  <label>{copy.flavor}</label>
                  <p className="au-flavor">{activeVersion.flavor}</p>
                </div>
              </div>

              <div className="au-export-bar">
                <button className="primary-button" type="button" data-sfx-handled onClick={openExport}>
                  {copy.exportText}
                </button>
              </div>
            </div>
          )}
        </main>
      </div>

      {/* Export Modal */}
      {showExport && (
        <div className="modal-backdrop" role="presentation" onClick={() => { playSound('modalClose'); setShowExport(false); }}>
          <div className="modal-surface" role="dialog" aria-modal="true" aria-label={copy.exportText} onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>{copy.exportText}</h3>
              <button className="icon-button" type="button" aria-label={copy.close} onClick={() => { playSound('modalClose'); setShowExport(false); }}>✕</button>
            </div>
            <div className="modal-body">
              <textarea className="scene-export-textarea" readOnly rows={16} value={exportText} aria-label={copy.exportText} />
              <div className="scene-export-actions">
                <button className="primary-button" type="button" data-sfx-handled onClick={handleCopy}>
                  {copied ? copy.copied : copy.copy}
                </button>
                <button className="secondary-button" type="button" data-sfx-handled onClick={() => { playSound('modalClose'); setShowExport(false); }}>
                  {copy.close}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
