import { useCallback, useEffect, useMemo, useState } from 'react';
import { playSound } from './audioEngine';
import type { AppLanguage, BaseCharacter, CoreStat, SettingsState } from './types';

// ─── Types ───

type SharedPageProps = {
  appSubtitle: string;
  backHome: string;
  openSettings: string;
  privacyNote: string;
  pageTitle: string;
  pageDescription: string;
  settings: SettingsState;
  language: AppLanguage;
  onBack: () => void;
  onOpenSettings: () => void;
  onSwitchTool?: (toolId: string) => void;
  onOpenDocs?: (toolId?: string, section?: string, errorCode?: string) => void;
};

export type NemesisType = 'opposite' | 'rival' | 'dark-mirror' | 'foil' | 'nemesis';

export type NemesisCharacter = {
  id: string;
  originalName: string;
  nemesisType: NemesisType;
  name: string;
  title: string;
  stats: Record<CoreStat, number>;
  personality: string;
  appearance: string;
  motivation: string;
  weakness: string;
  background: string;
  conflictScene: string;
  relationship: string;
  createdAt: string;
};

export type NemesisGeneratorState = {
  original: BaseCharacter;
  nemeses: NemesisCharacter[];
  activeNemesisId: string | null;
};

// ─── Localization ───

const UI_COPY: Record<string, Record<string, string>> = {
  zh: {
    baseCharacter: '基础角色',
    name: '角色名',
    personality: '性格描述',
    stats: '核心属性',
    str: '力量', dex: '敏捷', int: '智力', cha: '魅力', vit: '体质', luk: '幸运',
    generate: '生成宿敌',
    nemesisType: '宿敌类型',
    opposite: '性格反转',
    rival: '实力对手',
    'dark-mirror': '黑暗镜像',
    foil: '衬托对比',
    nemesis: '命运宿敌',
    generatedNemesis: '生成的宿敌',
    title: '称号',
    appearance: '外貌',
    motivation: '动机',
    weakness: '弱点',
    background: '背景',
    conflictScene: '冲突场景',
    relationship: '关系动态',
    comparison: '原版 vs 宿敌',
    original: '原版',
    delete: '删除',
    deleteConfirm: '确定删除这个宿敌吗？',
    emptyNemeses: '暂无宿敌，输入基础角色信息后点击生成',
    exportText: '导出文本',
    close: '关闭',
    copied: '已复制',
    copy: '复制',
    untitled: '未命名角色',
    generatedBy: '生成自 Original Character Maker',
    typeDescriptionOpposite: '性格与属性完全相反的对立面',
    typeDescriptionRival: '实力接近但方向不同的竞争者',
    typeDescriptionDarkMirror: '同样的属性，却走向黑暗',
    typeDescriptionFoil: '属性互补，形成鲜明对照',
    typeDescriptionNemesis: '命运交织的宿敌，背景故事相连',
  },
  ja: {
    baseCharacter: 'ベースキャラ',
    name: 'キャラ名',
    personality: '性格',
    stats: 'コアステータス',
    str: '筋力', dex: '敏捷', int: '知性', cha: '魅力', vit: '体力', luk: '運',
    generate: '宿敵を生成',
    nemesisType: '宿敵タイプ',
    opposite: '性格反転',
    rival: '実力のライバル',
    'dark-mirror': '暗黒の鏡像',
    foil: '対比のフォイル',
    nemesis: '運命の宿敵',
    generatedNemesis: '生成された宿敵',
    title: '称号',
    appearance: '外見',
    motivation: '動機',
    weakness: '弱点',
    background: '背景',
    conflictScene: '対峙シーン',
    relationship: '関係性',
    comparison: '原版 vs 宿敵',
    original: '原版',
    delete: '削除',
    deleteConfirm: 'この宿敵を削除しますか？',
    emptyNemeses: 'まだ宿敵がありません。ベース情報を入力して生成してください。',
    exportText: 'テキスト出力',
    close: '閉じる',
    copied: 'コピー完了',
    copy: 'コピー',
    untitled: '無名キャラ',
    generatedBy: 'Original Character Maker で生成',
    typeDescriptionOpposite: '性格とステータスが完全に反転した対極',
    typeDescriptionRival: '実力は近いが方向性の異なる競争者',
    typeDescriptionDarkMirror: '同じステータスを持ちながら闇へ堕ちた存在',
    typeDescriptionFoil: 'ステータスが補完し、鮮明な対照を形成',
    typeDescriptionNemesis: '運命が交錯し、背景が繋がる宿敵',
  },
  en: {
    baseCharacter: 'Base Character',
    name: 'Name',
    personality: 'Personality',
    stats: 'Core Stats',
    str: 'STR', dex: 'DEX', int: 'INT', cha: 'CHA', vit: 'VIT', luk: 'LUK',
    generate: 'Generate Nemesis',
    nemesisType: 'Nemesis Type',
    opposite: 'Opposite',
    rival: 'Rival',
    'dark-mirror': 'Dark Mirror',
    foil: 'Foil',
    nemesis: 'Nemesis',
    generatedNemesis: 'Generated Nemesis',
    title: 'Title',
    appearance: 'Appearance',
    motivation: 'Motivation',
    weakness: 'Weakness',
    background: 'Background',
    conflictScene: 'Conflict Scene',
    relationship: 'Relationship',
    comparison: 'Original vs Nemesis',
    original: 'Original',
    delete: 'Delete',
    deleteConfirm: 'Delete this nemesis?',
    emptyNemeses: 'No nemeses yet. Enter base info and click generate.',
    exportText: 'Export Text',
    close: 'Close',
    copied: 'Copied',
    copy: 'Copy',
    untitled: 'Unnamed Character',
    generatedBy: 'Generated by Original Character Maker',
    typeDescriptionOpposite: 'A polar opposite in personality and stats',
    typeDescriptionRival: 'A competitor of near-equal strength',
    typeDescriptionDarkMirror: 'The same stats, but fallen into darkness',
    typeDescriptionFoil: 'Complementary stats forming sharp contrast',
    typeDescriptionNemesis: 'A fated enemy with intertwined backstories',
  },
  ru: {
    baseCharacter: 'Базовый персонаж',
    name: 'Имя',
    personality: 'Характер',
    stats: 'Основные характеристики',
    str: 'СИЛ', dex: 'ЛОВ', int: 'ИНТ', cha: 'ХАР', vit: 'ЖИВ', luk: 'УДА',
    generate: 'Создать врага',
    nemesisType: 'Тип врага',
    opposite: 'Антипод',
    rival: 'Соперник',
    'dark-mirror': 'Тёмное зеркало',
    foil: 'Контраст',
    nemesis: 'Немезида',
    generatedNemesis: 'Созданный враг',
    title: 'Титул',
    appearance: 'Внешность',
    motivation: 'Мотивация',
    weakness: 'Слабость',
    background: 'Предыстория',
    conflictScene: 'Сцена конфликта',
    relationship: 'Отношения',
    comparison: 'Оригинал vs Враг',
    original: 'Оригинал',
    delete: 'Удалить',
    deleteConfirm: 'Удалить этого врага?',
    emptyNemeses: 'Пока нет врагов. Введите базовую информацию и нажмите «Создать».',
    exportText: 'Экспорт текста',
    close: 'Закрыть',
    copied: 'Скопировано',
    copy: 'Копировать',
    untitled: 'Безымянный персонаж',
    generatedBy: 'Создано в Original Character Maker',
    typeDescriptionOpposite: 'Полная противоположность в характере и характеристиках',
    typeDescriptionRival: 'Конкурент близкой силы',
    typeDescriptionDarkMirror: 'Те же характеристики, но павший во тьму',
    typeDescriptionFoil: 'Дополняющие характеристики, создающие резкий контраст',
    typeDescriptionNemesis: 'Судьбоносный враг со связанными предысториями',
  },
  ko: {
    baseCharacter: '베이스 캐릭터',
    name: '이름',
    personality: '성격',
    stats: '핵심 스탯',
    str: '힘', dex: '민첩', int: '지능', cha: '매력', vit: '활력', luk: '행운',
    generate: '숙적 생성',
    nemesisType: '숙적 타입',
    opposite: '성격 반전',
    rival: '실력 라이벌',
    'dark-mirror': '어두운 거울',
    foil: '대조의 포일',
    nemesis: '운명의 宿敵',
    generatedNemesis: '생성된 숙적',
    title: '칭호',
    appearance: '외모',
    motivation: '동기',
    weakness: '약점',
    background: '배경',
    conflictScene: '대립 장면',
    relationship: '관계성',
    comparison: '원판 vs 宿敵',
    original: '원판',
    delete: '삭제',
    deleteConfirm: '이 宿敵을 삭제하시겠습니까?',
    emptyNemeses: '아직 宿敵이 없습니다. 베이스 정보를 입력하고 생성하세요.',
    exportText: '텍스트 납품하기',
    close: '닫기',
    copied: '복사됨',
    copy: '복사',
    untitled: '이름 없는 캐릭터',
    generatedBy: 'Original Character Maker 에서 생성됨',
    typeDescriptionOpposite: '성격과 스탯이 완전히 반전된 대척점',
    typeDescriptionRival: '실력은 비슷하지만 방향이 다른 경쟁자',
    typeDescriptionDarkMirror: '같은 스탯을 가지고 어둠으로 빠진 존재',
    typeDescriptionFoil: '스탯이 서로 보완되어 선명한 대조를 이룸',
    typeDescriptionNemesis: '운명이 얽히고 배경이 연결된 宿敵',
  },
};

// ─── Nemesis Type Data ───

type NemesisTypeData = {
  id: NemesisType;
  statMods: Partial<Record<CoreStat, number>>;
  namePrefixes: Record<string, string[]>;
  nameSuffixes: Record<string, string[]>;
  titles: Record<string, string[]>;
  appearances: Record<string, string[]>;
  motivations: Record<string, string[]>;
  weaknesses: Record<string, string[]>;
  backgrounds: Record<string, string[]>;
  conflictScenes: Record<string, string[]>;
  relationships: Record<string, string[]>;
};

const NEMESIS_TYPES: NemesisTypeData[] = [
  {
    id: 'opposite',
    statMods: { str: -2, dex: -1, int: +2, cha: -2, vit: -1, luk: +1 },
    namePrefixes: {
      zh: ['反', '逆', '异', '背', '伪'], ja: ['反', '逆', '異', '背', '偽'], en: ['Anti-', 'Counter-', 'Reverse ', 'Shadow ', 'False '], ru: ['Анти-', 'Контр-', 'Обратный ', 'Теневой ', 'Ложный '], ko: ['반대의 ', '역의 ', '이면의 ', '배반의 ', '거짓의 '],
    },
    nameSuffixes: {
      zh: ['之影', '的反面', '的逆转', '的倒影', '的反面'], ja: ['の影', 'の反面', 'の逆転', 'の倒影', 'の裏'], en: [' the Opposite', ' the Inverse', ' the Reversal', ' the Shadow', ' the Counterpart'], ru: [' — Антипод', ' — Инверсия', ' — Обратная сторона', ' — Тень', ' — Двойник'], ko: ['의 그림자', '의 반면', '의 역전', '의 반영', '의 대척점'],
    },
    titles: {
      zh: ['对立之影', '逆转者', '反面镜像', '背道而驰者', '伪装的敌人'], ja: ['対極の影', '逆転者', '反面の鏡像', '背道馳者', '偽りの敵'], en: ['The Polar Shadow', 'The Reverser', 'The Mirror Inverse', 'The Contrary', 'The False Foe'], ru: ['Полярная тень', 'Обратитель', 'Зеркальное отражение', 'Противоположность', 'Ложный враг'], ko: ['대극의 그림자', '역전자', '반면의 거울상', '배도자', '위장된 적'],
    },
    appearances: {
      zh: ['发色与原角色完全相反', '穿着颜色对比强烈的服装', '眼神冷漠而疏离', '体型与原角色截然相反', '佩戴着象征对立的饰品'],
      ja: ['髪色は原キャラと完全に反対', '対照的な色の服装を着ている', '冷たく距離を置く眼神', '体型は原キャラと正反対', '対立を象徴する装飾品を身に着けている'],
      en: ['Hair color completely opposite to the original', 'Wears clothing in stark contrasting colors', 'Cold and distant gaze', 'Body type the exact opposite of the original', 'Wears accessories symbolizing opposition'],
      ru: ['Цвет волос полностью противоположен оригиналу', 'Носит одежду резко контрастных цветов', 'Холодный и отстранённый взгляд', 'Телосложение прямо противоположно оригиналу', 'Носит аксессуары, символизирующие противопоставление'],
      ko: ['원래 캐릭터와 완전히 반대되는 머리색', '강렬한 대비색의 의상을 착용', '차갑고 거리를 두는 눈빛', '원래 캐릭터와 정반대의 체형', '대립을 상징하는 액세서리를 착용'],
    },
    motivations: {
      zh: ['证明原角色的道路是错误的', '用相反的方式达到同样的目标', '让原角色质疑自己的信念', '建立一个与原角色对立的新秩序', '渴望被原角色认可却又否定对方'],
      ja: ['原キャラの道が間違っていることを証明する', '反対の方法で同じ目標を達成する', '原キャラに自身の信念を疑わせる', '原キャラと対立する新秩序を築く', '原キャラに認められたいのに相手を否定する'],
      en: ['To prove the original character\'s path is wrong', 'To reach the same goal through opposite means', 'To make the original character doubt their beliefs', 'To build a new order opposing the original', 'Craves recognition from the original yet denies them'],
      ru: ['Доказать, что путь оригинального персонажа ошибочен', 'Достичь той же цели противоположными средствами', 'Заставить оригинального персонажа усомниться в своих убеждениях', 'Построить новый порядок, противостоящий оригиналу', 'Жаждет признания от оригинала, но отрицает его'],
      ko: ['원래 캐릭터의 길이 잘못되었다는 것을 증명', '반대 방법으로 같은 목표 달성', '원래 캐릭터가 자신의 신념을 의심하게 만들기', '원래 캐릭터와 대립하는 새 질서 구축', '원래 캐릭터의 인정을 갈망하면서도 상대를 부정'],
    },
    weaknesses: {
      zh: ['无法真正理解原角色的信念', '过于极端而容易失衡', '内心深处其实羡慕原角色', '无法接受任何形式的合作', '在压力下容易自我怀疑'],
      ja: ['原キャラの信念を本当に理解できない', '極端すぎてバランスを崩しやすい', '内心では原キャラを羨んでいる', 'いかなる協力も受け入れられない', 'プレッシャー下で自己怀疑しやすい'],
      en: ['Cannot truly understand the original\'s convictions', 'Too extreme and prone to losing balance', 'Secretly envies the original deep down', 'Unable to accept any form of cooperation', 'Prone to self-doubt under pressure'],
      ru: ['Не может по-настоящему понять убеждения оригинала', 'Слишком крайний и склонен к потере равновесия', 'В глубине души тайно завидует оригиналу', 'Не способен принять любое сотрудничество', 'Склонен к сомнениям в себе под давлением'],
      ko: ['원래 캐릭터의 신념을 진정으로 이해하지 못함', '너무 극단적이라 균형을 잃기 쉬움', '속으로는 원래 캐릭터를 부러워함', '어떤 형태의 협력도 받아들일 수 없음', '압박 속에서 자기 의심에 빠지기 쉬움'],
    },
    backgrounds: {
      zh: ['曾经与原角色是最好的朋友，因理念分歧而决裂', '在原角色失败的地方取得了成功，却失去了更重要的东西', '被同一个导师收养，却走上了完全不同的道路', '原角色的实验失败品，带着缺陷诞生', '在原角色的光芒下长大，决心超越对方'],
      ja: ['かつて原キャラと親友だったが、理念の違いで決裂した', '原キャラが失敗した場所で成功したが、より大切なものを失った', '同じ導師に育てられたが、完全に異なる道を歩んだ', '原キャラの実験の失敗作で、欠陥を持って生まれた', '原キャラの光の下で育ち、彼女を超える決意をした'],
      en: ['Once the original\'s best friend, separated by ideological divergence', 'Succeeded where the original failed, but lost something more important', 'Raised by the same mentor, yet walked a completely different path', 'A failed experiment of the original, born with defects', 'Grew up in the original\'s shadow, determined to surpass them'],
      ru: ['Когда-то лучший друг оригинала, разделённые идеологическим расхождением', 'Добился успеха там, где потерпел неудачу оригинал, но потерял кое-что более важное', 'Воспитан тем же наставником, но пошёл совершенно другим путём', 'Неудачный эксперимент оригинала, рождённый с дефектами', 'Вырос в тени оригинала, полный решимости превзойти его'],
      ko: ['한때 원래 캐릭터와 절친이었으나 이념 차이로 결별', '원래 캐릭터가 실패한 곳에서 성공했지만 더 중요한 것을 잃음', '같은导師에게 길러졌지만 완전히 다른 길을 걸음', '원래 캐릭터의 실패한 실험체로 결함을 가지고 태어남', '원래 캐릭터의 그림자 아래 자라 상대를 뛰어넘을 결심을 함'],
    },
    conflictScenes: {
      zh: ['两人在雨中的废墟中对峙， lightning 照亮了彼此的脸', '在旧日的训练场上再次交手，每一招都带着过去的回忆', '在拥挤的市集人群中擦肩而过，认出对方却无言以对', '在山顶的祭坛上争夺同一件神器', '在梦境中相遇，互相质问对方的选择'],
      ja: ['雨の廃墟で対峙し、稲妻が互いの顔を照らす', '旧日の訓練場で再び手合わせ、一撃一撃に過去の思い出が宿る', '混雑した市場の人混みですれ違い、相手を認識しながら言葉を失う', '山頂の祭壇で同じ神器を巡って争う', '夢の中で出会い、互いの選択を問い質す'],
      en: ['They face off in rain-soaked ruins, lightning illuminating each other\'s faces', 'Crossing blades again on the old training ground, each strike carrying memories of the past', 'Brushing past each other in a crowded market, recognizing yet speechless', 'Fighting over the same artifact atop a mountain altar', 'Meeting in a dream, questioning each other\'s choices'],
      ru: ['Они противостоят друг другу в залитых дождём руинах, молния освещает их лица', 'Вновь скрестив мечи на старом тренировочном поле, каждый удар несёт воспоминания о прошлом', 'Расходятся в толпе на переполненном рынке, узнавая друг друга, но не находя слов', 'Сражаясь за один артефакт на горном алтаре', 'Встречаясь во сне, ставя под сомнение выбор друг друга'],
      ko: ['비에 젖은 폐허에서 대립하며 번개가 서로의 얼굴을 비춤', '옛 훈련장에서 다시 겨루며 매번의 타격에 과거의 추억이 담김', '붐비는 시장의 인파 속에서 스쳐 지나가며 서로를 알아보지만 말을 잃음', '산정의 제단 위에서 같은 신기를 두고 다툼', '꿈속에서 만나 서로의 선택을 추궁함'],
    },
    relationships: {
      zh: ['表面上互相憎恨，内心深处却彼此理解', '每次相遇都会让双方都变得更强大', '一方前进必然导致另一方后退', '既是最大的威胁也是最了解对方的人', '无法共存，却又无法彻底分离'],
      ja: ['表向きは互いを憎んでいるが、内心ではお互いを理解している', '出会うたびに双方がより強くなる', '一方が前進すれば必ず他方が後退する', '最大の脅威でありながら最も相手を理解している存在', '共存はできないが、完全に分離することもできない'],
      en: ['They outwardly despise each other, yet understand one another deep down', 'Every encounter makes both of them stronger', 'One\'s advance inevitably causes the other\'s retreat', 'Both the greatest threat and the one who understands them best', 'Unable to coexist, yet unable to fully separate'],
      ru: ['Внешне презирают друг друга, но в глубине души понимают друг друга', 'Каждая встреча делает обоих сильнее', 'Продвижение одного неизбежно влечёт отступление другого', 'И величайшая угроза, и тот, кто понимает лучше всех', 'Неспособны сосуществовать, но и полностью расстаться не могут'],
      ko: ['겉으로는 서로를 증오하지만 내면에서는 서로를 이해함', '만날 때마다 양쪽 모두 더 강해짐', '한쪽이 전진하면 반드시 다른 쪽이 후퇴함', '최대의 위협이면서도 가장 잘 이해하는 존재', '공존할 수 없지만 완전히 분리될 수도 없음'],
    },
  },
  {
    id: 'rival',
    statMods: { str: +1, dex: +2, int: -1, cha: +1, vit: +1, luk: 0 },
    namePrefixes: {
      zh: ['竞', '争', '敌', '对', '劲'], ja: ['競', '争', '敵', '対', '勁'], en: ['Rival ', 'Competing ', 'Challenger ', 'Opposing ', 'Equal '], ru: ['Соперник ', 'Конкурирующий ', 'Претендент ', 'Противостоящий ', 'Равный '], ko: ['경쟁하는 ', '대항하는 ', '도전하는 ', '라이벌 ', '맞서는 '],
    },
    nameSuffixes: {
      zh: ['二世', '的挑战者', '的劲敌', '的宿敌', '的竞敌'], ja: ['二世', 'の挑戦者', 'の強敵', 'の宿敵', 'の競敵'], en: [' the Second', ' the Challenger', ' the Rival', ' the Nemesis', ' the Competitor'], ru: [' — Второй', ' — Претендент', ' — Соперник', ' — Немезида', ' — Конкурент'], ko: ['2세', '의 도전자', '의 강적', '의 宿敵', '의 경쟁자'],
    },
    titles: {
      zh: ['永恒的对手', '势均力敌者', '追赶者', '并行者', '挑战者'], ja: ['永遠のライバル', '実力伯仲者', '追跡者', '並行者', '挑戦者'], en: ['The Eternal Rival', 'The Equal', 'The Chaser', 'The Parallel', 'The Challenger'], ru: ['Вечный соперник', 'Равный по силе', 'Преследователь', 'Параллельный', 'Претендент'], ko: ['영원한 라이벌', '실력 맞서는 자', '추적자', '나란히 가는 자', '도전자'],
    },
    appearances: {
      zh: ['穿着和原角色同级别的装备', '外貌和原角色有几分相似但更加锐利', '身材健美，充满力量感', '眼神中带着不服输的火焰', '身上有多处训练留下的伤痕'],
      ja: ['原キャラと同じレベルの装備を身に着けている', '外見は原キャラに似ているがより鋭い', '筋肉質で力強さに満ちている', '眼差しに負けない炎が宿っている', '訓練でできた傷が全身にある'],
      en: ['Wears equipment on par with the original', 'Appearance somewhat similar to the original but sharper', 'Athletic build exuding strength', 'Eyes burn with an unyielding flame', 'Body covered in training scars'],
      ru: ['Носит экипировку не ниже оригинала', 'Внешность несколько похожа на оригинал, но острее', 'Атлетическое телосложение, излучающее силу', 'В глазах горит неукротимое пламя', 'Всё тело покрыто шрамами от тренировок'],
      ko: ['원래 캐릭터와 동급의 장비를 착용', '외모가 원래 캐릭터와 몇 분 닮았지만 더 날카로움', '근육질이며 힘이 넘침', '눈빛에 지지 않겠다는 불꽃이 타오름', '훈련으로 생긴 상처가 온몸에 있음'],
    },
    motivations: {
      zh: ['超越原角色成为最强', '证明自己比原角色更适合那个位置', '赢得所有人都认可的胜利', '在原角色擅长的领域击败对方', '获得原角色所拥有的认可和尊重'],
      ja: ['原キャラを超えて最強になる', '原キャラよりその地位にふさわしいことを証明する', '誰もが認める勝利を収める', '原キャラが得意とする分野で打ち負かす', '原キャラが持つ認可と尊敬を得る'],
      en: ['To surpass the original and become the strongest', 'To prove more deserving of the original\'s position', 'To earn a victory recognized by all', 'To defeat the original in their own specialty', 'To gain the recognition and respect the original holds'],
      ru: ['Превзойти оригинала и стать сильнейшим', 'Доказать, что достойнее позиции оригинала', 'Завоевать победу, признанную всеми', 'Победить оригинала в его собственной специальности', 'Получить признание и уважение, которыми обладает оригинал'],
      ko: ['원래 캐릭터를 뛰어넘어 최강이 되기', '원래 캐릭터보다 그 자리에 더 어울린다는 것을 증명', '모두가 인정하는 승리를 거두기', '원래 캐릭터가 자신 있는 분야에서 패배시키기', '원래 캐릭터가 가진 인정과 존경을 얻기'],
    },
    weaknesses: {
      zh: ['过于关注原角色而忽视自己的成长', '无法接受失败，容易自暴自弃', '有时会低估原角色的决心', '在追求胜利的过程中伤害了重要的人', '被情绪左右，容易做出冲动的决定'],
      ja: ['原キャラに注目しすぎて自身の成長を見失う', '敗北を受け入れられず自暴自棄になりやすい', '時々原キャラの決意を過小評価する', '勝利を追い求める過程で大切な人を傷つける', '感情に左右され、衝動的な決定をしやすい'],
      en: ['Too focused on the original to notice their own growth', 'Unable to accept defeat, prone to self-destruction', 'Sometimes underestimates the original\'s resolve', 'Hurt important people in the pursuit of victory', 'Led by emotions, prone to impulsive decisions'],
      ru: ['Слишком сфокусирован на оригинале, чтобы заметить собственный рост', 'Не способен принять поражение, склонен к саморазрушению', 'Иногда недооценивает решимость оригинала', 'Ранит важных людей в погоне за победой', 'Управляем эмоциями, склонен к импульсивным решениям'],
      ko: ['원래 캐릭터에 너무 집중하여 자신의 성장을 놓침', '패배를 받아들이지 못하고 자포자기에 빠지기 쉬움', '가끔 원래 캐릭터의 결의를 과소평가함', '승리를 추구하는 과정에서 중요한 사람을 다침', '감정에 휘둘려 충동적인 결정을 내리기 쉬움'],
    },
    backgrounds: {
      zh: ['和原角色在同一所学校/组织，但总是排名第二', '曾经是原角色的徒弟，后来自立门户', '在原角色离开后才加入，一直被拿来比较', '通过非正统途径获得了和原角色相近的实力', '家族世代与原角色的家族竞争'],
      ja: ['原キャラと同じ学校/組織にいて、いつも2位', 'かつて原キャラの弟子だったが、後に独立した', '原キャラが去ってから加入し、常に比較されていた', '非正統な方法で原キャラに近い実力を得た', '代々原キャラの家と競い合う家系'],
      en: ['Attended the same school/organization as the original, always ranked second', 'Once the original\'s apprentice, later struck out on their own', 'Joined after the original left, constantly compared to them', 'Gained strength near the original\'s level through unorthodox means', 'Family has competed with the original\'s family for generations'],
      ru: ['Учился в той же школе/организации, что и оригинал, всегда второй', 'Когда-то ученик оригинала, позже обрёл независимость', 'Присоединился после ухода оригинала, постоянно сравниваемый с ним', 'Достиг силы, близкой к оригиналу, нетрадиционными путями', 'Семья веками соперничает с семьёй оригинала'],
      ko: ['원래 캐릭터와 같은 학교/조직에 다녔지만 항상 2위', '한때 원래 캐릭터의 제자였으나 후에 독립', '원래 캐릭터가 떠난 후 들어와 계속 비교당함', '비정통적인 방법으로 원래 캐릭터에 근접한 실력을 얻음', '대대로 원래 캐릭터의 가문과 경쟁하는 가문'],
    },
    conflictScenes: {
      zh: ['在竞技场上公开对决，观众为两人欢呼', '在狭窄的巷道中追逐，每一步都考验着速度和反应', '在图书馆的禁区争夺同一份古老文献', '在暴风雪中的山路上互相阻挡对方的去路', '在宴会上暗中较劲，表面上却谈笑风生'],
      ja: ['競技場で公開対決し、観客が二人に歓声を上げる', '狭い路地での追跡で、一歩一歩が速度と反応を試す', '図書館の禁書区で同じ古文書を巡って争う', '吹雪の山道で互いの行く手を阻む', '宴の席で陰で張り合い、表向きは談笑している'],
      en: ['A public duel in the arena, the crowd cheering for both', 'A chase through narrow alleys, every step testing speed and reflexes', 'Fighting over the same ancient manuscript in the library\'s forbidden section', 'Blocking each other\'s path on a mountain road during a blizzard', 'Secretly competing at a banquet while appearing to chat amiably'],
      ru: ['Открытая дуэль на арене, толпа приветствует обоих', 'Погоня по узким переулкам, каждый шаг — проверка скорости и рефлексов', 'Борьба за одну древнюю рукопись в запретном отделе библиотеки', 'Преграждение пути друг другу на горной дороге во время метели', 'Тайное соперничество на банкете при внешне дружеской беседе'],
      ko: ['경기장에서 공개 대결하며 관중들이 둘에게 환호', '좁은 골목에서 추격하며 매 걸음이 속도와 반응을 시험', '도서관 금서 구역에서 같은 고문서를 두고 다툼', '눈보라 속 산길에서 서로의 앞길을 막음', '연회장에서 은밀히 경쟁하면서 겉으로는 환담'],
    },
    relationships: {
      zh: ['彼此是最了解对方的对手', '竞争让双方都不断突破极限', '一方胜利时另一方会真心祝福（然后更加努力）', '即使敌对也保持着某种尊重', '是彼此成长的最大推动力'],
      ja: ['互いに最も相手を理解しているライバル', '競争が双方の限界を突破させる', '一方が勝利すると他方は心から祝福する（そしてさらに努力する）', '敵対しながらも一定の敬意を保っている', '互いの成長の最大の推進力である'],
      en: ['They know each other better than anyone else', 'Competition pushes both to constantly break their limits', 'When one wins, the other sincerely congratulates them (then tries even harder)', 'Even as enemies, they maintain a certain respect', 'They are the greatest driving force behind each other\'s growth'],
      ru: ['Они знают друг друга лучше, чем кто-либо другой', 'Соперничество постоянно толкает обоих за пределы возможного', 'Когда один побеждает, другой искренне поздравляет его (а затем старается ещё сильнее)', 'Даже будучи врагами, сохраняют определённое уважение', 'Они — величайшая движущая сила роста друг друга'],
      ko: ['서로를 누구보다 잘 아는 라이벌', '경쟁이 양쪽 모두의 한계를 끊임없이 돌파시킴', '한쪽이 승리하면 다른 쪽은 진심으로 축하함(그리고 더 열심히 노력함)', '적대 관계임에도 일정한 존중을 유지', '서로의 성장에 가장 큰 동력이 되는 존재'],
    },
  },
  {
    id: 'dark-mirror',
    statMods: { str: +1, dex: +1, int: +1, cha: -2, vit: +1, luk: -1 },
    namePrefixes: {
      zh: ['暗', '邪', '堕', '黑', '腐'], ja: ['暗', '邪', '堕', '黒', '腐'], en: ['Dark ', 'Corrupt ', 'Fallen ', 'Black ', 'Twisted '], ru: ['Тёмный ', 'Искажённый ', 'Падший ', 'Чёрный ', 'Испорченный '], ko: ['어둠의 ', '사악한 ', '타락한 ', '흑암의 ', '부패한 '],
    },
    nameSuffixes: {
      zh: ['之暗', '的堕落', '的暗影', '的腐化', '的反面'], ja: ['の闇', 'の堕落', 'の暗影', 'の腐敗', 'の裏'], en: [' the Dark', ' the Fallen', ' the Shadow', ' the Corrupt', ' the Inverse'], ru: [' — Тьма', ' — Падший', ' — Тень', ' — Искажение', ' — Инверсия'], ko: ['의 어둠', '의 타락', '의 그림자', '의 부패', '의 반대'],
    },
    titles: {
      zh: ['堕落镜像', '暗影化身', '腐化之影', '黑暗倒影', '堕落的原罪'], ja: ['堕落の鏡像', '暗影の化身', '腐敗の影', '暗黒の倒影', '堕落の原罪'], en: ['The Fallen Mirror', 'The Shadow Incarnate', 'The Corrupt Shade', 'The Dark Reflection', 'The Original Sin'], ru: ['Падшее отражение', 'Воплощение тени', 'Искажённая тень', 'Тёмное отражение', 'Первозданный грех'], ko: ['타락한 거울상', '그림자의 화신', '부패한 그림자', '어두운 반영', '타락의 원죄'],
    },
    appearances: {
      zh: ['外表和原角色几乎一模一样，但眼神中透着邪气', '穿着和原角色相似但颜色暗沉的服装', '身上散发着不祥的气息', '皮肤苍白，仿佛从未见过阳光', '某处有着和原角色完全相反的标记'],
      ja: ['外見は原キャラとほぼ同じだが、眼差しに邪悪さが宿る', '原キャラに似た服装を着ているが色合いが暗い', '不吉な気配を漂わせている', '肌が青白く、まるで日の光を見たことがないよう', 'どこかに原キャラと完全に反対の印がある'],
      en: ['Appearance nearly identical to the original, but eyes hold malice', 'Wears clothing similar to the original but in dark muted tones', 'Exudes an ominous aura', 'Pale skin, as if never touched by sunlight', 'Bears a mark perfectly opposite to the original\'s somewhere'],
      ru: ['Внешность почти идентична оригиналу, но в глазах — злоба', 'Носит одежду, похожую на оригинал, но в тёмных приглушённых тонах', 'Испускает зловещую ауру', 'Бледная кожа, словно никогда не касалась солнечного света', 'Где-то носит знак, полностью противоположный оригиналу'],
      ko: ['외모가 원래 캐릭터와 거의 같지만 눈빛에 사악함이 깃듦', '원래 캐릭터와 비슷한 의상을 입고 있지만 색감이 어둡고 침침함', '불길한 기운을 풍김', '피부가 창백하여 마치 햇빛을 본 적이 없는 듯', '어딘가에 원래 캐릭터와 정반대의印이 있음'],
    },
    motivations: {
      zh: ['证明原角色的善良只是一种软弱', '用同样的力量做相反的事', '让原角色体验失去一切的痛苦', '用黑暗的方式实现原角色的理想', '摧毁原角色所珍视的一切'],
      ja: ['原キャラの善良さはただの弱さだと証明する', '同じ力で反対のことをする', '原キャラに全てを失う苦しみを味あわせる', '暗黒の方法で原キャラの理想を実現する', '原キャラが大切にする全てを破壊する'],
      en: ['To prove the original\'s kindness is merely weakness', 'To use the same power for opposite ends', 'To make the original experience the pain of losing everything', 'To realize the original\'s ideals through dark means', 'To destroy everything the original holds dear'],
      ru: ['Доказать, что доброта оригинала — лишь слабость', 'Использовать ту же силу для противоположных целей', 'Заставить оригинала испытать боль утраты всего', 'Осуществить идеалы оригинала тёмными путями', 'Разрушить всё, что дорого оригиналу'],
      ko: ['원래 캐릭터의 선량함은 단지 나약함이라는 것을 증명', '같은 힘으로 반대의 일을 하기', '원래 캐릭터에게 모든 것을 잃는 고통을 맛보게 하기', '어두운 방법으로 원래 캐릭터의 이상을 실현하기', '원래 캐릭터가 소중히 여기는 모든 것을 파괴하기'],
    },
    weaknesses: {
      zh: ['内心深处仍然记得自己善良时的样子', '被原角色的微笑所动摇', '无法彻底摧毁和原角色相关的美好回忆', '在独处时会表现出脆弱的一面', '对某种原角色喜欢的事物仍然有反应'],
      ja: ['内心では善良だった頃の自分を覚えている', '原キャラの微笑みに動揺する', '原キャラに関連する美しい思い出を完全には破壊できない', '一人の時には脆い一面を見せる', '原キャラが好きだった何かに未だ反応する'],
      en: ['Deep down still remembers what it was like to be kind', ' shaken by the original\'s smile', 'Unable to completely destroy beautiful memories tied to the original', 'Shows vulnerability when alone', 'Still reacts to something the original once loved'],
      ru: ['В глубине души всё ещё помнит, каково это — быть добрым', 'Раскачивается от улыбки оригинала', 'Не в состоянии полностью уничтожить прекрасные воспоминания, связанные с оригиналом', 'Проявляет уязвимость, когда остаётся один', 'Всё ещё реагирует на что-то, что когда-то любил оригинал'],
      ko: ['속으로는 선량했을 때의 자신을 기억함', '원래 캐릭터의 미소에 동요함', '원래 캐릭터와 연결된 아름다운 추억을 완전히 파괴하지 못함', '혼자 있을 때 연약한 면을 드러냄', '원래 캐릭터가 좋아하던 무언가에 여전히 반응함'],
    },
    backgrounds: {
      zh: ['原角色在一次危机中选择了牺牲自己拯救他人，而TA选择了相反', '被同样的力量诅咒，但走向了黑暗的极端', '原角色的复制体或分身，产生了自我意识后背叛', '曾经和原角色是同一阵营，因一次背叛而堕落', '被黑暗力量选中作为原角色的"另一面"'],
      ja: ['原キャラは危機の中で自己犠牲を選んだが、彼は反対を選んだ', '同じ力に呪われたが、闇の極端へと進んだ', '原キャラの複製体や分身で、自己意識を持った後に裏切った', 'かつて原キャラと同じ陣営だったが、一度の裏切りで堕ちた', '闇の力に選ばれ、原キャラの「もう一つの面」として存在する'],
      en: ['While the original chose self-sacrifice in a crisis, they chose the opposite', 'Cursed by the same power, but walked to the extreme of darkness', 'A clone or copy of the original that gained self-awareness and turned against them', 'Once in the same faction as the original, fell after a single betrayal', 'Chosen by dark forces to exist as the "other side" of the original'],
      ru: ['В то время как оригинал выбрал самопожертвование в кризисе, они выбрали противоположное', 'Прокляты той же силой, но пошли к крайности тьмы', 'Клон или копия оригинала, обретшая самосознание и восставшая против него', 'Когда-то состоял в той же фракции, что и оригинал, пал после одного предательства', 'Избран тёмными силами, чтобы существовать как «другая сторона» оригинала'],
      ko: ['원래 캐릭터는 위기 속에서 자신을 희생하며 다른 이를 구했지만, 그는 반대를 선택', '같은 힘에 저주받았으나 어둠의 극단으로 나아감', '원래 캐릭터의 복제체 또는 분신으로, 자아를 얻은 후 배신', '한때 원래 캐릭터와 같은 진영이었으나 한 번의 배신으로 타락', '어두운 힘에 선택받아 원래 캐릭터의 "다른 면"으로 존재'],
    },
    conflictScenes: {
      zh: ['在破碎的镜子迷宫中对峙，每一面镜子都映出不同的自己', '在曾经一起训练的地方再次相遇，物是人非', '在黑暗中只有两人的呼吸声，却看不见彼此', '在原角色的重要之人面前揭露黑暗的秘密', '在梦境与现实的交界处战斗'],
      ja: ['砕けた鏡の迷宮で対峙し、一面一面が異なる自分を映す', 'かつて一緒に訓練した場所で再会し、人は変わり物は変わらず', '闇の中で二人の呼吸音だけが聞こえ、互いを見ることができない', '原キャラの大切な人の前で暗黒の秘密を暴く', '夢と現実の境界で戦う'],
      en: ['Facing off in a shattered mirror maze, each surface reflecting a different self', 'Meeting again where they once trained together, people changed but things remain', 'In the darkness, only each other\'s breathing can be heard, unable to see one another', 'Revealing dark secrets before the original\'s loved one', 'Battling at the boundary between dream and reality'],
      ru: ['Противостояние в лабиринте разбитых зеркал, каждое отражает другого себя', 'Встреча там, где когда-то вместе тренировались, люди изменились, но всё осталось', 'В темноте слышен лишь дыхание друг друга, но увидеть друг друга невозможно', 'Разоблачение тёмных секретов перед любимым человеком оригинала', 'Сражение на границе между сном и реальностью'],
      ko: ['부서진 거울 미로에서 대립하며 각 거울이 다른 자신을 비춤', '한때 함께 훈련했던 곳에서 다시 만나 사람은 변했지만 물건은 그대로', '어둠 속에서 서로의 숨소리만 들리지만 서로를 볼 수 없음', '원래 캐릭터의 소중한 이의 앞에서 어두운 비밀을 폭로', '꿈과 현실의 경계에서 싸움'],
    },
    relationships: {
      zh: ['是原角色最不愿面对的敌人', '两人的命运像两根交织的绳索', '原角色的每一次成功都让TA更加痛苦', 'TA的存在不断提醒原角色"你也可能变成这样"', '最了解原角色的弱点，因为曾经拥有同样的力量'],
      ja: ['原キャラが最も向き合いたくない敵', '二人の運命は絡み合う二つの縄のよう', '原キャラの成功のたびに彼はより苦しむ', '彼の存在は原キャラに「君もこうなり得た」と思い出させる', 'かつて同じ力を持っていたため、原キャラの弱点を最もよく知っている'],
      en: ['The enemy the original least wants to face', 'Their fates are like two intertwined ropes', 'Every success of the original causes them more pain', 'Their existence constantly reminds the original "you could have become this"', 'Knows the original\'s weaknesses best, having once wielded the same power'],
      ru: ['Враг, с которым оригинал меньше всего хочет столкнуться', 'Их судьбы словно две переплетённые верёвки', 'Каждый успех оригинала причиняет им ещё больше боли', 'Их существование постоянно напоминает оригиналу: «ты мог стать таким»', 'Лучше всех знает слабости оригинала, когда-то владев того же силой'],
      ko: ['원래 캐릭터가 가장 마주하고 싶지 않은 적', '두 사람의 운명은 서로 얽힌 두 개의 밧줄과 같음', '원래 캐릭터의 성공이 있을 때마다 그는 더 고통스러워함', '그의 존재는 원래 캐릭터에게 "너도 이렇게 될 수 있었다"를 끊임없이 상기시킴', '한때 같은 힘을 가졌기에 원래 캐릭터의 약점을 가장 잘 앎'],
    },
  },
  {
    id: 'foil',
    statMods: { str: -1, dex: +2, int: +2, cha: -1, vit: -2, luk: +2 },
    namePrefixes: {
      zh: ['辅', '衬', '配', '伴', '映'], ja: ['輔', '衬', '配', '伴', '映'], en: ['Foil ', 'Complementary ', 'Contrasting ', 'Paired ', 'Twin '], ru: ['Дополняющий ', 'Контрастный ', 'Парный ', 'Двойной ', 'Сопутствующий '], ko: ['보완의 ', '첩의 ', '배의 ', '반대의 ', '동반의 '],
    },
    nameSuffixes: {
      zh: ['的衬托', '的映照', '的伴侣', '的另一半', '的对比'], ja: ['の対比', 'の映し', 'の伴侶', 'の半分', 'の照らし'], en: [' the Foil', ' the Contrast', ' the Complement', ' the Other Half', ' the Mirror'], ru: [' — Контраст', ' — Отражение', ' — Дополнение', ' — Вторая половина', ' — Зеркало'], ko: ['의 대조', '의 비춤', '의 동반자', '의 반쪽', '의 거울'],
    },
    titles: {
      zh: ['衬托之光', '对照者', '互补之影', '双生花', '阴阳之伴'], ja: ['対比の光', '照らし者', '補完の影', '双生花', '陰陽の伴'], en: ['The Foil Light', 'The Contraster', 'The Complementary Shade', 'The Twin Bloom', 'The Yin-Yang Companion'], ru: ['Свет контраста', 'Контрастёр', 'Дополняющая тень', 'Двойной цветок', 'Спутник инь-ян'], ko: ['대조의 빛', '비추는 자', '보완의 그림자', '쌍생화', '음양의 동반자'],
    },
    appearances: {
      zh: ['发色和原角色形成鲜明对比', '身材娇小但灵活，和原角色形成对照', '穿着风格完全不同的服装', '表情温和，和原角色的气质形成反差', '某处有着和原角色互补的特征'],
      ja: ['髪色は原キャラと鮮明な対比をなす', '小柄だが敏捷で、原キャラと対照をなす', '全く異なるスタイルの服装を着ている', '表情が穏やかで、原キャラの雰囲気と対比する', 'どこかに原キャラを補完する特徴がある'],
      en: ['Hair color forms a vivid contrast with the original', 'Small but agile, forming a contrast with the original', 'Wears clothing in a completely different style', 'Gentle expression contrasting with the original\'s aura', 'Has features complementary to the original somewhere'],
      ru: ['Цвет волос образует яркий контраст с оригиналом', 'Мелкий, но ловкий, образуя контраст с оригиналом', 'Носит одежду совершенно другого стиля', 'Мягкое выражение лица контрастирует с аурой оригинала', 'Где-то имеет черты, дополняющие оригинал'],
      ko: ['머리색이 원래 캐릭터와 선명한 대조를 이룸', '작지만 민첩하여 원래 캐릭터와 대조를 이룸', '완전히 다른 스타일의 의상을 입고 있음', '온화한 표정이 원래 캐릭터의 분위기와 대비됨', '어딘가에 원래 캐릭터를 보완하는 특징이 있음'],
    },
    motivations: {
      zh: ['用自己的方式守护原角色所守护的东西', '证明不同的道路可以到达同一个终点', '让原角色看到事物的另一面', '在原角色忽略的地方发挥作用', '成为原角色不可缺少的一部分'],
      ja: ['自分の方法で原キャラが守るものを守る', '異なる道でも同じ終点にたどり着けることを証明する', '原キャラに物事のもう一つの面を見せる', '原キャラが見落とした場所で役割を果たす', '原キャラにとって欠かせない存在になる'],
      en: ['To protect what the original protects, but in their own way', 'To prove different paths can lead to the same destination', 'To show the original the other side of things', 'To play a role where the original overlooks', 'To become an indispensable part of the original'],
      ru: ['Защищать то, что защищает оригинал, но своим путём', 'Доказать, что разные пути могут вести к одной цели', 'Показать оригиналу другую сторону вещей', 'Играть роль там, где оригинал не замечает', 'Стать неотъемлемой частью оригинала'],
      ko: ['자신의 방식으로 원래 캐릭터가 지키는 것을 지키기', '다른 길도 같은 종점에 도달할 수 있다는 것을 증명', '원래 캐릭터에게 사물의 다른 면을 보여주기', '원래 캐릭터가 간과한 곳에서 역할을 하기', '원래 캐릭터에게 없어서는 안 될 존재가 되기'],
    },
    weaknesses: {
      zh: ['过于依赖原角色的保护', '在原角色不在时容易迷失方向', '有时会因为过度互补而缺乏主见', '在必须独立做决定时犹豫不决', '容易被利用来威胁原角色'],
      ja: ['原キャラの保護に依存しすぎる', '原キャラがいない時に方向を見失いやすい', '補完しすぎて時々主見を欠く', '独力で決断しなければならない時に優柔不断になる', '原キャラを脅すために利用されやすい'],
      en: ['Overly dependent on the original\'s protection', 'Easily loses direction when the original is absent', 'Sometimes lacks initiative from being too complementary', 'Hesitates when forced to make independent decisions', 'Easily used as leverage to threaten the original'],
      ru: ['Чрезмерно зависит от защиты оригинала', 'Легко теряет направление, когда оригинала нет рядом', 'Иногда не хватает инициативы от чрезмерного дополнения', 'Колеблется, когда вынужден принимать самостоятельные решения', 'Легко используется как рычаг для угрозы оригиналу'],
      ko: ['원래 캐릭터의 보호에 지나치게 의존', '원래 캐릭터가 없을 때 방향을 잃기 쉬움', '너무 보완적이라 때때로 주관이 부족함', '독립적으로 결정을 내려야 할 때 망설임', '원래 캐릭터를 위협하는 수단으로 이용당하기 쉬움'],
    },
    backgrounds: {
      zh: ['和原角色在同一场灾难中幸存，但选择了不同的治愈方式', '被原角色救过，从此决定用自己的方式回报', '和原角色有着互补的出身背景', '曾经是原角色的搭档，后来各自发展但保持联系', '天生就拥有和原角色互补的能力'],
      ja: ['原キャラと同じ災害で生き延びたが、異なる癒し方を選んだ', '原キャラに救われ、以来自分の方法で報いようと決意した', '原キャラと補完し合う出自を持つ', 'かつて原キャラの相棒だったが、後に別々の道を歩みながら連絡を保った', '生まれつき原キャラを補完する能力を持つ'],
      en: ['Survived the same disaster as the original, but chose a different way to heal', 'Saved by the original, ever since determined to repay in their own way', 'Has a background complementary to the original', 'Once the original\'s partner, later walked separate paths but stayed in touch', 'Born with abilities complementary to the original'],
      ru: ['Пережил ту же катастрофу, что и оригинал, но выбрал другой путь исцеления', 'Спасён оригиналом, с тех пор решил отплатить своим путём', 'Имеет предысторию, дополняющую оригинала', 'Когда-то был партнёром оригинала, позже пошёл своим путём, но сохранил связь', 'Рождён сі способностями, дополняющими оригинала'],
      ko: ['원래 캐릭터와 같은 재난에서 살아남았지만 다른 치유 방식을 선택', '원래 캐릭터에게 구해진 후 자신의 방식으로 보답하기로 결심', '원래 캐릭터와 보완되는 출신 배경을 가짐', '한때 원래 캐릭터의 파트너였으나 후에 각자의 길을 걸으며 연락을 유지', '태어날 때부터 원래 캐릭터를 보완하는 능력을 가짐'],
    },
    conflictScenes: {
      zh: ['两人背靠背面对共同的敌人，配合得天衣无缝', '在争论中用相反的观点帮助原角色找到正确答案', '在原角色陷入绝望时出现，用不同的方式带来希望', '在需要智慧和力量的考验中互补完成', '在分离多年后重逢，发现彼此都成长了'],
      ja: ['背中合わせで共通の敵に立ち向かい、完璧な連携を見せる', '議論の中で反対の意見から原キャラが正解を見つけるのを助ける', '原キャラが絶望に陥った時に現れ、異なる方法で希望をもたらす', '知恵と力を必要とする試練で補完し合って完遂する', '長年の別れ後に再会し、互いに成長したことに気づく'],
      en: ['Standing back-to-back against a common enemy, coordinating flawlessly', 'Helping the original find the right answer through opposing viewpoints in debate', 'Appearing when the original falls into despair, bringing hope through different means', 'Complementing each other to complete a trial requiring both wisdom and strength', 'Reuniting after years apart, realizing both have grown'],
      ru: ['Стоя спина к спине против общего врага, действуя безупречно скоординированно', 'Помогая оригиналу найти правильный ответ через противоположные точки зрения в споре', 'Появляясь, когда оригинал впадает в отчаяние, принося надежду иными средствами', 'Дополняя друг друга, чтобы пройти испытание, требующее и мудрости, и силы', 'Воссоединившись после долгих лет разлуки, осознавая, что оба выросли'],
      ko: ['등을 맞대고 공통의 적에 맞서 완벽한 호흡을 보임', '논쟁 중 반대 의견을 통해 원래 캐릭터가 정답을 찾도록 도움', '원래 캐릭터가 절망에 빠졌을 때 나타나 다른 방식으로 희망을 가져다줌', '지혜와 힘을 모두 필요로 하는 시련에서 서로 보완하며 완수', '오랜 이별 후 재회하여 서로 성장했음을 깨달음'],
    },
    relationships: {
      zh: ['彼此是对方最理想的互补者', '分开时各自强大，合起来几乎无敌', '一方的优点恰好是另一方的缺点', '即使意见不合，最终也会走向同一个目标', '是彼此最信任的搭档'],
      ja: ['互いにとって最も理想的な補完者', '別々の時も強いが、合わさるとほぼ無敵', '一方の長所は他方の短所にぴったり合う', '意見が合わなくても、最終的には同じ目標に向かう', '互いに最も信頼する相棒である'],
      en: ['They are each other\'s ideal complement', 'Strong alone, nearly unstoppable together', 'One\'s strengths perfectly match the other\'s weaknesses', 'Even when disagreeing, they ultimately head toward the same goal', 'They are each other\'s most trusted partner'],
      ru: ['Они — идеальное дополнение друг друга', 'Сильны по отдельности, почти неостановимы вместе', 'Сильные стороны одного идеально соответствуют слабостям другого', 'Даже когда не согласны, в конечном итоге идут к одной цели', 'Они — самые доверенные партнёры друг друга'],
      ko: ['서로에게 가장 이상적인 보완자', '따로 있을 때도 강하지만 함께할 때는 거의 무적', '한쪽의 장점이 다른 쪽의 단점과 완벽하게 맞음', '의견이 맞지 않아도 결국 같은 목표를 향함', '서로가 가장 신뢰하는 파트너'],
    },
  },
  {
    id: 'nemesis',
    statMods: { str: +2, dex: 0, int: +2, cha: -1, vit: +2, luk: -2 },
    namePrefixes: {
      zh: ['宿', '劫', '孽', '逆', '劫'], ja: ['宿', '劫', '孽', '逆', '劫'], en: ['Nemesis ', 'Doomed ', 'Fated ', 'Cursed ', 'Eternal '], ru: ['Немезида ', 'Обречённый ', 'Судьбоносный ', 'Проклятый ', 'Вечный '], ko: ['宿', '劫', '孽', '역', '劫'],
    },
    nameSuffixes: {
      zh: ['的宿敌', '的劫难', '的孽缘', '的命运', '的轮回'], ja: ['の宿敵', 'の劫難', 'の孽縁', 'の運命', 'の輪廻'], en: [' the Nemesis', ' the Doomed', ' the Fated', ' the Cursed', ' the Eternal'], ru: [' — Немезида', ' — Обречённый', ' — Судьбоносный', ' — Проклятый', ' — Вечный'], ko: ['의 宿敵', '의 劫難', '의 孽緣', '의 운명', '의 윤회'],
    },
    titles: {
      zh: ['宿命之敌', '轮回对手', '劫数之人', '命运纠缠者', '永世宿敌'], ja: ['宿命の敵', '輪廻の対手', '劫数の人', '運命の絡み合い者', '永世の宿敵'], en: ['The Fated Enemy', 'The Cyclical Rival', 'The Doomed One', 'The Entwined Fate', 'The Eternal Nemesis'], ru: ['Судьбоносный враг', 'Циклический соперник', 'Обречённый', 'Сплетённые судьбы', 'Вечная немезида'], ko: ['숙명의 적', '윤회의 상대', '劫數의 인', '운명의 얽힌 자', '영원한 宿敵'],
    },
    appearances: {
      zh: ['身上有着和原角色相似但更加不祥的印记', '眼神中透着宿命般的沉重', '穿着带有古老诅咒纹样的服装', '某处有着和原角色配对的伤痕', '身上散发着命运纠缠的气息'],
      ja: ['原キャラに似たがより不吉な印を身に着けている', '眼差しに宿命のような重みが宿る', '古い呪いの紋様が入った服装を着ている', 'どこかに原キャラと対になった傷がある', '運命が絡み合う気配を漂わせている'],
      en: ['Bears a mark similar to but more ominous than the original\'s', 'Eyes carry the weight of destiny', 'Wears clothing adorned with ancient curse patterns', 'Has a scar paired with the original\'s somewhere', 'Exudes an aura of intertwined fate'],
      ru: ['Носит знак, похожий на оригинал, но более зловещий', 'Взгляд несёт тяжесть судьбы', 'Носит одежду с древними проклятыми узорами', 'Где-то имеет шрам, парный к шраму оригинала', 'Испускает ауру переплетённых судеб'],
      ko: ['원래 캐릭터와 비슷하지만 더 불길한印을 지니고 있음', '눈빛에 숙명 같은 무게가 깃듦', '고대 저주 문양이 새겨진 의상을 입고 있음', '어딘가에 원래 캐릭터와 짝이 되는 상처가 있음', '운명이 얽혀 있는 기운을 풍김'],
    },
    motivations: {
      zh: ['打破纠缠两代人的宿命诅咒', '让原角色体验自己所经历的一切', '证明自己才是命运选中的真正继承人', '用原角色的死亡来终结永恒的轮回', '让两个家族的血债血偿'],
      ja: ['二代にわたる宿命の呪いを打ち破る', '原キャラに自分が経験した全てを味あわせる', '自分こそが運命に選ばれた真の継承者だと証明する', '原キャラの死で永遠の輪廻を終わらせる', '両家の血の復讐を果たす'],
      en: ['To break the fated curse binding two generations', 'To make the original experience everything they have endured', 'To prove they are the true heir chosen by destiny', 'To end the eternal cycle with the original\'s death', 'To settle the blood debt between both families'],
      ru: ['Разрушить судьбоносное проклятие, связывающее два поколения', 'Заставить оригинала пережить всё, что выпало на их долю', 'Доказать, что они — истинный наследник, избранный судьбой', 'Положить конец вечному циклу смертью оригинала', 'Расплатиться кровью за долги обеих семей'],
      ko: ['두 세대를 묶은 숙명의 저주를 깨뜨리기', '원래 캐릭터에게 자신이 겪은 모든 것을 맛보게 하기', '자신이야말로 운명이 선택한 진정한 후계자라는 것을 증명', '원래 캐릭터의 죽음으로 영원한 윤회를 끝내기', '두 가문의 피의 복수를 갚기'],
    },
    weaknesses: {
      zh: ['被宿命所束缚，无法选择自己的道路', '内心深处渴望打破轮回', '在原角色表现出善意时会犹豫', '无法伤害和原角色有血缘关系的人', '宿命预言必须在特定条件下才会实现'],
      ja: ['宿命に縛られ、自分の道を選べない', '内心では輪廻を打ち破ることを渇望している', '原キャラが善意を示すとためらう', '原キャラと血縁関係にある人を傷つけられない', '宿命の予言は特定の条件下でしか実現しない'],
      en: ['Bound by fate, unable to choose their own path', 'Deep down yearns to break the cycle', 'Hesitates when the original shows kindness', 'Unable to harm those blood-related to the original', 'The prophesied fate only manifests under specific conditions'],
      ru: ['Связан судьбой, не способен выбрать свой путь', 'В глубине души жаждет разорвать цикл', 'Колеблется, когда оригинал проявляет доброту', 'Не способен причинить вред тем, кто состоит в кровном родстве с оригиналом', 'Предсказанная судьба сбывается лишь при определённых условиях'],
      ko: ['숙명에 묶여 자신의 길을 선택할 수 없음', '속으로는 윤회를 깨뜨리기를 갈망함', '원래 캐릭터가 선의를 보이면 망설임', '원래 캐릭터와 혈연 관계인 사람을 해칠 수 없음', '숙명의 예언은 특정 조건에서만 실현됨'],
    },
    backgrounds: {
      zh: ['两个家族世代为敌，诅咒代代相传', '原角色在某次事件中无意中导致了TA的悲剧', '两人是失散多年的双胞胎/兄弟姐妹', '古老的预言说两人中必有一人毁灭另一人', '两人共享同一个灵魂的两面'],
      ja: ['二つの家は代々敵対し、呪いは代々伝わる', '原キャラがある事件で偶々彼の悲劇を引き起こした', '二人は長年離れ離れになった双子/兄弟姉妹', '古の予言によれば、二人のうち必ず一方が他方を滅ぼす', '二人は同じ魂の両面を共有している'],
      en: ['Two families have been enemies for generations, the curse passed down', 'The original inadvertently caused their tragedy in an incident', 'They are long-lost twins/siblings', 'An ancient prophecy states one must destroy the other', 'They share two sides of the same soul'],
      ru: ['Две семьи веками враждуют, проклятие передаётся из поколения в поколение', 'Оригинал невольно стал причиной их трагедии в одном инциденте', 'Они — давно потерянные близнецы/братья и сёстры', 'Древнее пророчество гласит: один должен уничтожить другого', 'Они разделяют две стороны одной души'],
      ko: ['두 가문은 대대로 적대하며 저주가 대대로 전해짐', '원래 캐릭터가 어떤 사건에서 우연히 그의 비극을 야기함', '두 사람은 오래 전에 헤어진 쌍둥이/남매', '고대 예언에 따르면 둘 중 한 명이 반드시 다른 한 명을 멸망시킨다', '두 사람은 같은 영혼의 두 면을 공유함'],
    },
    conflictScenes: {
      zh: ['在古老的祭坛上进行宿命对决，周围刻满了两家族的历史', '在雷雨交加的夜晚，两人同时感应到命运的召唤', '在原角色的家族墓地中，揭露隐藏百年的秘密', '在两人共同出生的地方重逢，一切都回到了原点', '在预言中提到的那个时刻，两人不得不做出最终选择'],
      ja: ['古の祭壇で宿命の対決を行い、周囲には両家の歴史が刻まれている', '雷雨の夜、二人同時に運命の召喚を感じる', '原キャラの家の墓地で、百年隠されていた秘密を暴く', '二人が生まれた場所で再会し、全てが原点に戻る', '予言に語られたその時刻に、二人は最終選択を迫られる'],
      en: ['A fated duel on an ancient altar, surrounded by the histories of both families', 'On a stormy night, both simultaneously feel destiny\'s call', 'In the original\'s family graveyard, uncovering a secret hidden for centuries', 'Reuniting where both were born, everything returning to the origin', 'At the prophesied hour, both are forced to make the final choice'],
      ru: ['Судьбоносная дуэль на древнем алтаре, окружённом историями обеих семей', 'В грозовую ночь оба одновременно чувствуют зов судьбы', 'На семейном кладбище оригинала, раскрывая тайну, скрытую веками', 'Воссоединение там, где оба родились, всё возвращается к истокам', 'В предсказанный час оба вынуждены сделать последний выбор'],
      ko: ['고대 제단에서 숙명의 대결을 벌이며 주변에는 양가의 역사가 새겨져 있음', '뇌우가 치는 밤, 둘이 동시에 운명의 소명을 느낌', '원래 캐릭터의 가문 묘지에서 백년 동안 숨겨진 비밀을 폭로', '둘이 태어난 곳에서 재회하며 모든 것이 원점으로 돌아감', '예언에서 언급된 그 시각에 두 사람은 최종 선택을 강요받음'],
    },
    relationships: {
      zh: ['两人的命运从出生起就纠缠在一起', '一方死亡另一方也会受到重创', '是彼此最不愿杀死却不得不杀死的人', '两人的战斗会让旁观者感到一种悲壮的美', '无论相隔多远，总会被命运拉回彼此身边'],
      ja: ['二人の運命は生まれた時から絡み合っている', '一方が死ねば他方も重傷を負う', '互いに殺したくないが殺さなければならない存在', '二人の戦いは傍観者に悲壮な美しさを感じさせる', 'どれだけ離れても、運命が互いを引き寄せる'],
      en: ['Their fates have been entwined since birth', 'If one dies, the other suffers grievous harm', 'The person each least wants to kill yet must', 'Their battle evokes a tragic beauty in onlookers', 'No matter how far apart, fate always draws them back together'],
      ru: ['Их судьбы сплетены с рождения', 'Если один умрёт, другой понесёт тяжёлую рану', 'Тот, кого каждый меньше всего хочет убить, но вынужден', 'Их битва вызывает трагическую красоту у наблюдателей', 'Как бы далеко они ни были, судьба всегда возвращает их друг к другу'],
      ko: ['두 사람의 운명은 태어날 때부터 얽혀 있음', '한쪽이 죽으면 다른 쪽도 중상을 입음', '서로가 가장 죽이고 싶지 않지만 죽여야만 하는 존재', '두 사람의 전투는 방관자에게 비장한 아름다움을 느끼게 함', '아무리 멀리 떨어져 있어도 운명이 서로를 끌어당김'],
    },
  },
];

// ─── Helpers ───

function uid() {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getCopy(language: AppLanguage) {
  return UI_COPY[language] ?? UI_COPY.en;
}

function getNemesisTypeData(id: NemesisType): NemesisTypeData | undefined {
  return NEMESIS_TYPES.find((t) => t.id === id);
}

function clampStat(value: number): number {
  if (!Number.isFinite(value)) return 50;
  return Math.min(100, Math.max(1, Math.round(value)));
}

function defaultBaseCharacter(): BaseCharacter {
  return {
    name: '',
    personality: '',
    stats: { str: 50, dex: 50, int: 50, cha: 50, vit: 50, luk: 50 },
  };
}

function generateNemesisName(originalName: string, typeData: NemesisTypeData, language: AppLanguage): string {
  const prefixes = typeData.namePrefixes[language] ?? typeData.namePrefixes.en;
  const suffixes = typeData.nameSuffixes[language] ?? typeData.nameSuffixes.en;
  if (!originalName) return pick(prefixes) + pick(suffixes);
  // 50% chance prefix, 50% suffix
  if (Math.random() < 0.5) {
    return pick(prefixes) + originalName;
  }
  return originalName + pick(suffixes);
}

function generateNemesisCharacter(
  original: BaseCharacter,
  typeData: NemesisTypeData,
  language: AppLanguage
): NemesisCharacter {
  const stats: Record<CoreStat, number> = { ...original.stats };
  (Object.keys(typeData.statMods) as CoreStat[]).forEach((key) => {
    const mod = typeData.statMods[key] ?? 0;
    stats[key] = clampStat(stats[key] + mod * 10 + (Math.random() * 10 - 5));
  });

  const appPool = typeData.appearances[language] ?? typeData.appearances.en;
  const motPool = typeData.motivations[language] ?? typeData.motivations.en;
  const weakPool = typeData.weaknesses[language] ?? typeData.weaknesses.en;
  const bgPool = typeData.backgrounds[language] ?? typeData.backgrounds.en;
  const scenePool = typeData.conflictScenes[language] ?? typeData.conflictScenes.en;
  const relPool = typeData.relationships[language] ?? typeData.relationships.en;
  const titlePool = typeData.titles[language] ?? typeData.titles.en;

  return {
    id: uid(),
    originalName: original.name,
    nemesisType: typeData.id,
    name: generateNemesisName(original.name, typeData, language),
    title: pick(titlePool),
    stats,
    personality: '',
    appearance: pick(appPool),
    motivation: pick(motPool),
    weakness: pick(weakPool),
    background: pick(bgPool),
    conflictScene: pick(scenePool),
    relationship: pick(relPool),
    createdAt: new Date().toISOString(),
  };
}

const STORAGE_KEY = 'oc-maker.nemesis-generator';

function readState(): NemesisGeneratorState {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw) as NemesisGeneratorState;
      if (parsed.original && parsed.nemeses) {
        return parsed;
      }
    }
  } catch { /* ignore */ }
  return { original: defaultBaseCharacter(), nemeses: [], activeNemesisId: null };
}

function writeState(state: NemesisGeneratorState): boolean {
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    return true;
  } catch {
    return false;
  }
}

function useMaybeConfirm(settings: SettingsState) {
  return useCallback((message: string, action: () => void) => {
    if (!settings.others.confirmDestructiveActions || window.confirm(message)) {
      action();
    }
  }, [settings.others.confirmDestructiveActions]);
}

// ─── Component ───

export default function CharacterNemesisPage({
  pageTitle,
  pageDescription,
  settings,
  language,
  onBack,
  onOpenSettings,
  onOpenDocs,
}: SharedPageProps) {
  const copy = getCopy(language);
  const maybeConfirm = useMaybeConfirm(settings);
  const [state, setState] = useState<NemesisGeneratorState>(readState);
  const [selectedType, setSelectedType] = useState<NemesisType>('opposite');
  const [showExport, setShowExport] = useState(false);
  const [exportText, setExportText] = useState('');
  const [copied, setCopied] = useState(false);

  const { original, nemeses, activeNemesisId } = state;
  const activeNemesis = useMemo(() => nemeses.find((n) => n.id === activeNemesisId) ?? null, [nemeses, activeNemesisId]);

  useEffect(() => {
    writeState(state);
  }, [state]);

  useEffect(() => {
    if (!showExport) return;
    function handler(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        e.preventDefault();
        playSound('modalClose');
        setShowExport(false);
      }
    }
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [showExport]);

  const updateBase = useCallback((patch: Partial<BaseCharacter>) => {
    setState((prev) => ({ ...prev, original: { ...prev.original, ...patch } }));
  }, []);

  const updateStat = useCallback((key: CoreStat, value: number) => {
    setState((prev) => ({
      ...prev,
      original: { ...prev.original, stats: { ...prev.original.stats, [key]: clampStat(value) } },
    }));
  }, []);

  const generate = useCallback(() => {
    const typeData = getNemesisTypeData(selectedType);
    if (!typeData) return;
    playSound('confirm');
    const nemesis = generateNemesisCharacter(original, typeData, language);
    setState((prev) => ({
      ...prev,
      nemeses: [...prev.nemeses, nemesis],
      activeNemesisId: nemesis.id,
    }));
  }, [original, selectedType, language]);

  const deleteNemesis = useCallback((id: string) => {
    playSound('deleteSound');
    setState((prev) => {
      const nextNemeses = prev.nemeses.filter((n) => n.id !== id);
      return {
        ...prev,
        nemeses: nextNemeses,
        activeNemesisId: prev.activeNemesisId === id ? (nextNemeses[0]?.id ?? null) : prev.activeNemesisId,
      };
    });
  }, []);

  const generateExportText = useCallback((nemesis: NemesisCharacter): string => {
    const typeData = getNemesisTypeData(nemesis.nemesisType);
    const typeName = typeData ? (copy[nemesis.nemesisType] ?? nemesis.nemesisType) : nemesis.nemesisType;
    const lines = [
      `# ${nemesis.originalName} vs ${nemesis.name}`,
      '',
      `**${copy.title}:** ${nemesis.title}`,
      `**${copy.nemesisType}:** ${typeName}`,
      `**${copy.appearance}:** ${nemesis.appearance}`,
      `**${copy.motivation}:** ${nemesis.motivation}`,
      `**${copy.weakness}:** ${nemesis.weakness}`,
      `**${copy.background}:** ${nemesis.background}`,
      '',
      `## ${copy.stats}`,
      '',
      ...(['str', 'dex', 'int', 'cha', 'vit', 'luk'] as CoreStat[]).map((k) => {
        const baseVal = original.stats[k];
        const nemVal = nemesis.stats[k];
        const diff = nemVal - baseVal;
        const arrow = diff > 0 ? copy.statUp : diff < 0 ? copy.statDown : copy.statSame;
        return `- ${copy[k]}: ${baseVal} ${arrow} ${nemVal}`;
      }),
      '',
      `## ${copy.conflictScene}`,
      '',
      nemesis.conflictScene,
      '',
      `## ${copy.relationship}`,
      '',
      nemesis.relationship,
      '',
      '---',
      `*${copy.generatedBy}*`,
    ];
    return lines.join('\n');
  }, [original.stats, copy]);

  const openExport = useCallback(() => {
    if (!activeNemesis) return;
    playSound('modalOpen');
    setExportText(generateExportText(activeNemesis));
    setShowExport(true);
  }, [activeNemesis, generateExportText]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(exportText);
      setCopied(true);
      playSound('success');
      setTimeout(() => setCopied(false), 1500);
    } catch {
      playSound('error');
    }
  }, [exportText]);

  const statKeys: CoreStat[] = ['str', 'dex', 'int', 'cha', 'vit', 'luk'];

  const typeDescriptions: Record<NemesisType, string> = {
    opposite: copy.typeDescriptionOpposite,
    rival: copy.typeDescriptionRival,
    'dark-mirror': copy.typeDescriptionDarkMirror,
    foil: copy.typeDescriptionFoil,
    nemesis: copy.typeDescriptionNemesis,
  };

  return (
    <div className="page-container">
      {/* Header */}
      <div className="page-header-row">
        <div>
          <h2 className="page-title">{pageTitle}</h2>
          <p className="page-subtitle">{pageDescription}</p>
        </div>
        <div className="page-header-actions">
          {onOpenDocs && (
            <button className="secondary-button small-button" type="button" data-sfx-handled onClick={() => { playSound('buttonClick'); onOpenDocs('character-nemesis'); }}>
              ?
            </button>
          )}
          <button className="secondary-button small-button" type="button" data-sfx-handled onClick={() => { playSound('buttonClick'); onOpenSettings(); }}>
            ⚙
          </button>
          <button className="secondary-button small-button" type="button" data-sfx-handled onClick={() => { playSound('back'); onBack(); }}>
            ←
          </button>
        </div>
      </div>

      <div className="nemesis-generator-layout">
        {/* Base Character Panel */}
        <aside className="nemesis-base-panel">
          <div className="nemesis-panel-card">
            <h3 className="scene-section-title">{copy.baseCharacter}</h3>
            <input
              className="scene-input"
              id="nemesis-base-name"
              type="text"
              placeholder={copy.name}
              value={original.name}
              onChange={(e) => updateBase({ name: e.target.value })}
            />
            <textarea
              className="scene-textarea"
              id="nemesis-base-personality"
              rows={2}
              placeholder={copy.personality}
              value={original.personality}
              onChange={(e) => updateBase({ personality: e.target.value })}
            />
            <div className="nemesis-stats-grid">
              {statKeys.map((key) => (
                <div key={key} className="nemesis-stat-row">
                  <label className="nemesis-stat-label" htmlFor={`nemesis-stat-${key}`}>{copy[key]}</label>
                  <input
                    className="nemesis-stat-input"
                    id={`nemesis-stat-${key}`}
                    type="number"
                    min={1}
                    max={100}
                    value={original.stats[key]}
                    onChange={(e) => updateStat(key, Number(e.target.value))}
                  />
                  <input
                    className="nemesis-stat-slider"
                    id={`nemesis-stat-slider-${key}`}
                    type="range"
                    min={1}
                    max={100}
                    value={original.stats[key]}
                    onChange={(e) => updateStat(key, Number(e.target.value))}
                  />
                </div>
              ))}
            </div>
          </div>

          <div className="nemesis-panel-card">
            <h3 className="scene-section-title">{copy.nemesisType}</h3>
            <div className="nemesis-type-list">
              {NEMESIS_TYPES.map((t) => (
                <button
                  key={t.id}
                  className={`choice-chip ${selectedType === t.id ? 'active' : ''}`}
                  type="button"
                  data-sfx-handled
                  onClick={() => { playSound('select'); setSelectedType(t.id); }}
                  title={typeDescriptions[t.id]}
                >
                  {copy[t.id]}
                </button>
              ))}
            </div>
            <p className="nemesis-type-description">{typeDescriptions[selectedType]}</p>
            <button className="primary-button" type="button" data-sfx-handled onClick={generate} style={{ marginTop: 12, width: '100%' }}>
              ✦ {copy.generate}
            </button>
          </div>
        </aside>

        {/* Main Content */}
        <main className="nemesis-main-panel">
          {!activeNemesis ? (
            <div className="scene-empty-state">
              <div className="scene-empty-icon">⚔️</div>
              <p>{copy.emptyNemeses}</p>
            </div>
          ) : (
            <div className="nemesis-detail">
              {/* Tabs */}
              <div className="nemesis-tabs">
                {nemeses.map((n) => {
                  const t = getNemesisTypeData(n.nemesisType);
                  return (
                    <button
                      key={n.id}
                      className={`nemesis-tab ${n.id === activeNemesisId ? 'active' : ''}`}
                      type="button"
                      data-sfx-handled
                      onClick={() => { playSound('buttonClick'); setState((prev) => ({ ...prev, activeNemesisId: n.id })); }}
                    >
                      {n.name || copy.untitled}
                      <span
                        className="nemesis-tab-close"
                        role="button"
                        tabIndex={0}
                        aria-label={copy.delete}
                        onClick={(e) => {
                          e.stopPropagation();
                          maybeConfirm(copy.deleteConfirm, () => {
                            deleteNemesis(n.id);
                          });
                        }}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter' || e.key === ' ') {
                            e.preventDefault();
                            e.stopPropagation();
                            maybeConfirm(copy.deleteConfirm, () => {
                              deleteNemesis(n.id);
                            });
                          }
                        }}
                      >
                        ✕
                      </span>
                    </button>
                  );
                })}
              </div>

              {/* Nemesis Header */}
              <div className="nemesis-header-card">
                <div className="nemesis-header-name">{activeNemesis.name || copy.untitled}</div>
                <div className="nemesis-header-title">{activeNemesis.title}</div>
                <div className="nemesis-header-type">
                  {copy[activeNemesis.nemesisType]} · {typeDescriptions[activeNemesis.nemesisType]}
                </div>
              </div>

              {/* Comparison */}
              <div className="nemesis-comparison">
                <div className="nemesis-comparison-card">
                  <h4 className="nemesis-card-title">{copy.original}</h4>
                  <div className="nemesis-card-name">{original.name || copy.untitled}</div>
                  <div className="nemesis-card-stats">
                    {statKeys.map((k) => (
                      <div key={k} className="nemesis-card-stat">
                        <span className="nemesis-card-stat-name">{copy[k]}</span>
                        <div className="nemesis-card-stat-bar">
                          <div className="nemesis-card-stat-fill" style={{ width: `${original.stats[k]}%` }} />
                        </div>
                        <span className="nemesis-card-stat-value">{original.stats[k]}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div className="nemesis-comparison-card nemesis">
                  <h4 className="nemesis-card-title">{copy[activeNemesis.nemesisType]}</h4>
                  <div className="nemesis-card-name">{activeNemesis.name || copy.untitled}</div>
                  <div className="nemesis-card-stats">
                    {statKeys.map((k) => {
                      const baseVal = original.stats[k];
                      const nemVal = activeNemesis.stats[k];
                      const diff = nemVal - baseVal;
                      return (
                        <div key={k} className={`nemesis-card-stat ${diff > 0 ? 'up' : diff < 0 ? 'down' : ''}`}>
                          <span className="nemesis-card-stat-name">{copy[k]}</span>
                          <div className="nemesis-card-stat-bar">
                            <div className="nemesis-card-stat-fill" style={{ width: `${nemVal}%` }} />
                          </div>
                          <span className="nemesis-card-stat-value">
                            {nemVal}
                            {diff !== 0 && (
                              <span className={`nemesis-card-stat-diff ${diff > 0 ? 'up' : 'down'}`}>
                                {diff > 0 ? `+${diff}` : diff}
                              </span>
                            )}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>

              {/* Details */}
              <div className="nemesis-details">
                <div className="nemesis-detail-item">
                  <label>{copy.appearance}</label>
                  <p>{activeNemesis.appearance}</p>
                </div>
                <div className="nemesis-detail-item">
                  <label>{copy.motivation}</label>
                  <p>{activeNemesis.motivation}</p>
                </div>
                <div className="nemesis-detail-item">
                  <label>{copy.weakness}</label>
                  <p>{activeNemesis.weakness}</p>
                </div>
                <div className="nemesis-detail-item">
                  <label>{copy.background}</label>
                  <p>{activeNemesis.background}</p>
                </div>
                <div className="nemesis-detail-item">
                  <label>{copy.conflictScene}</label>
                  <p className="nemesis-scene">{activeNemesis.conflictScene}</p>
                </div>
                <div className="nemesis-detail-item">
                  <label>{copy.relationship}</label>
                  <p className="nemesis-relationship">{activeNemesis.relationship}</p>
                </div>
              </div>

              <div className="nemesis-export-bar">
                <button className="primary-button" type="button" data-sfx-handled onClick={openExport}>
                  {copy.exportText}
                </button>
              </div>
            </div>
          )}
        </main>
      </div>

      {/* Export Modal */}
      {showExport && (
        <div className="modal-backdrop" role="presentation" onClick={() => { playSound('modalClose'); setShowExport(false); }}>
          <div className="modal-surface" role="dialog" aria-modal="true" aria-label={copy.exportText} onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>{copy.exportText}</h3>
              <button className="icon-button" type="button" aria-label={copy.close} onClick={() => { playSound('modalClose'); setShowExport(false); }}>✕</button>
            </div>
            <div className="modal-body">
              <textarea className="scene-export-textarea" readOnly rows={18} value={exportText} aria-label={copy.exportText} />
              <div className="scene-export-actions">
                <button className="primary-button" type="button" data-sfx-handled onClick={handleCopy}>
                  {copied ? copy.copied : copy.copy}
                </button>
                <button className="secondary-button" type="button" data-sfx-handled onClick={() => { playSound('modalClose'); setShowExport(false); }}>
                  {copy.close}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
